---
title: "Untitled"
author: "cmm"
date: '2022-06-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gratia)
library(tidyverse)
library(mgcv)
source('12.gam_fns.R')
hab_loc_codes <- read_csv('data/habtypes.csv')
hab_loc_codes <- hab_loc_codes %>% select(SETTING_ID, habclass, locationcode)
bai.train <- readRDS('data/bai.train.7_5_22.rds')
bai.train <- left_join(bai.train, hab_loc_codes, by = "SETTING_ID")

bai.spmx <- bai.train %>% 
  select(SETTING_ID, stand, MEASUREMENT_NO, myear, PLOT, cluster, unique_tree_id, 
         bai, DIAMETER, treeba, log.diam, log.bai, grwth.yr, mean_si, aspect_deg, 
         heatload, slope_deg, elev_m, NF, CROWN_RATIO, tpa.pl.all, tpa.pl.cutoff,
         ba.pl, bal.pl, ccf.pl, ccf.nospp, qmd.pl.all, qmd.pl.cutoff, dq.pl.all, dq.pl.cutoff, tpa.cl.all, tpa.pl.cutoff, HabType, habclass,
         locationcode, larch.ba.fraction.pl, shade.tol.pl, dom.spp.pl.ba) %>% 
  mutate(slope_pct = tan(slope_deg*(pi/180))*100, 
         asp_sin = sin(aspect_deg*(pi/180)),
         asp_cos = cos(aspect_deg*(pi/180))) %>%
  mutate(sl_asp_sin = asp_sin*slope_pct, 
         sl_asp_cos = asp_cos*slope_pct, 
         asp.trasp = trasp(aspect_deg), 
         HabType = as.factor(HabType),
         cr = CROWN_RATIO/100,
         bal.pl.ratio = bal.pl/ba.pl,
         unique_tree_id = factor(unique_tree_id)) %>% 
  filter(bai != 0)


bai.spmx.ids <- bai.spmx %>% 
  group_by(stand) %>% 
  mutate(unique.stand = group_indices()) %>%
  ungroup() %>% 
  mutate(unique.cluster = (1000*unique.stand)+cluster, 
         unique.plot = (1000*unique.stand)+PLOT) %>% 
  mutate(unique.cluster.meas = as.factor(unique.cluster + MEASUREMENT_NO), 
         unique.plot.meas = as.factor(unique.plot + MEASUREMENT_NO),
         unique.cluster.f = as.factor(unique.cluster), 
         unique.plot.f = as.factor(unique.plot), 
         unique.tree.f = as.factor(unique_tree_id)) %>% 
  filter(unique_tree_id != 15431)

#null model to compare to for results
re.tree.1alt <- readRDS('data/model_objects.1/re.tree.1alt.rds')
#larch fraction - alternative with random 
spmx.gam.alt.lf <- readRDS('data/model_objects.1/spmx.gam.alt.lf.rds')
#shade tol - alternative with random
spmx.gam.alt.st <- readRDS('data/model_objects.1/spmx.gam.alt.st.rds')

ccf_noslope <- readRDS('data/model_objects.1/ccf_noslope.rds')

#ccf model
# ccf.gam <- gamm(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(asp_sin, asp_cos) + s(ccf.pl), random = list(unique_tree_id=~1) , family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))
# ccf.gam1 <- gamm4::gamm4(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(asp_sin, asp_cos) + s(ccf.pl), random=~(1|unique_tree_id) , family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML')
# 
# summary(ccf.gam$gam)
# ccf.gam$lme
# 
# ff <- exp(fitted(ccf.gam$lme))

a <- summary(re.tree.1alt)
aa <- summary(ccf_noslope)
b <- summary(spmx.gam.alt.lf)
c <- summary(spmx.gam.alt.st)
```

```{r}
#### Here is where I fit models which look at a weighted density metric (BASAL AREA). Comparing larch % weighted ba, shade intolerancce weighted ba, and crown competition factor. 

### Interestingly, the functional relationship among all of them is very similar.

## Curious what I will see after accounting for random effets
## curious what it would look like if instead these were accounted for through the addition of a interaction term. 
## This may mean that crown competition factor is perfectly adequately accounting for species mixing.. HOWEVER.. the ba term also functionally looks the same, which might suggest that CCF is mostly accounting for density..(which is what we already knew..)
## how do i figure out how much of species mixture is accounted for by ccf?

#### Next step is to parse this out and add random effects. Also evaluate 

bai.shade <- bai.spmx.ids %>% 
  mutate(shade.tol.ba = ba.pl*shade.tol.pl, larch.ba = larch.ba.fraction.pl*ba.pl)

ba.shade <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(shade.tol.ba) + s(asp_sin, asp_cos), family = 'Gamma'(link = log), data = bai.shade, method = 'ML', control = list(nthreads = 3))
ba.lf <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(larch.ba) + s(asp_sin, asp_cos), family = 'Gamma'(link = log), data = bai.shade, method = 'ML', control = list(nthreads = 3))
ccf.abc <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos), family = 'Gamma'(link = log), data = bai.shade, method = 'ML', control = list(nthreads = 3))

summary(ba.shade)
plot(ba.shade)

summary(ba.lf)
plot(ba.lf)

summary(ccf.abc)
plot(ccf.abc)

plot(re.tree.1alt)
# saveRDS(spmx.gam.lf, 'data/model_objects.1/spmx.gam.lf.rds')
```


```{r}
#compare spp mix models to null model
my.rmse.2(re.tree.1alt)[[2]]
my.rmse.2(spmx.gam.alt.lf)[[2]]
my.rmse.2(spmx.gam.alt.st)[[2]]

a$dev.expl
b$dev.expl
c$dev.expl
```

```{r}
#fit nospp ccf and spp-informed ccf models
bai.nospp <- bai.spmx.ids %>% mutate(ccf.pl = ccf.nospp)

ccf.model <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))

ccf.nospp <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos), family = 'Gamma'(link = log), data = bai.nospp, method = 'ML', control = list(nthreads = 3))

plot.gam(ccf.model, rug = F)
plot.gam(ccf.nospp, rug = F)


comp <- compare_smooths(ccf.model, ccf.nospp, smooths = 's(ccf.pl)')
draw(comp)

#most of what ccf is accounting for is density. There is a slight difference in these two curves, but I'm fairly confident that if ccf is accounting for species mix, that its relatively un-impactful. 

my.rmse.2(ccf.model)
my.rmse.2(ccf.nospp)
```

```{r}
#1 bai~dbh + bal + CR + BA + Asp.
re.tree.1alt

#2 bai~dbh + bal + CR + ccf + Asp.

ccf_noslope
  #gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(unique.tree.f, bs = 're'), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))
# saveRDS(mod_2, 'data/model_objects.1/ccf_noslope.rds')
# saveRDS(mod_2, 'C:/Users/cm165878/Box/research_/ccf_noslope.rds')

#3 bai~dbh + bal + CR + (BA * %larch) + Asp.
spmx.gam.alt.lf #this is not an interaction version, this just has ba and larch% separately

#4 bai~dbh + bal + CR + (BA * shade) + Asp.
spmx.gam.alt.st #this does not include interaction, just ba and shade separately

#4 bai~dbh + bal + CR + (ccf * shade)??? + Asp.

```

```{r}
#how much does species mixing matter?
models <- c('ba_model', 'ccf_model', 'larch%', 'shade')
rmses <- c(my.rmse.2(re.tree.1alt)[[2]],
  my.rmse.2(ccf_noslope)[[2]],
  my.rmse.2(spmx.gam.alt.lf)[[2]],
  my.rmse.2(spmx.gam.alt.st)[[2]])*6.452
dev.exp <- 100*c(a$dev.expl, aa$dev.expl, b$dev.expl, c$dev.expl)
aics <- c(AIC(re.tree.1alt), AIC(ccf_noslope), AIC(spmx.gam.alt.lf), AIC(spmx.gam.alt.st))


tibble(models, rmses, dev.exp, aics)

lf.sm <- smooth_estimates(spmx.gam.alt.lf, smooth = 's(larch.ba.fraction.pl)') %>% add_confint()
st.sm <- smooth_estimates(spmx.gam.alt.st, 's(shade.tol.pl)') %>% add_confint()

ggplot(lf.sm, aes(x = larch.ba.fraction.pl, y = est)) + 
  geom_line() + geom_ribbon(aes(ymin = est-se, ymax = est+se), alpha = 0.2) + geom_hline(yintercept = 0, linetype = 'dashed') + 
  geom_line(data = st.sm, aes(x = shade.tol.pl, y = est), color = 'blue') + 
  geom_ribbon(inherit.aes = F, data = st.sm, aes(ymin = est-se, ymax = est+se, x = shade.tol.pl), alpha = 0.2, fill = 'blue') + 
  geom_rug(inherit.aes = F, data = bai.spmx.ids, aes(x = larch.ba.fraction.pl),alpha = 0.2) +
  geom_rug(inherit.aes = F, data = bai.spmx.ids, aes(x = shade.tol.pl), alpha = 0.2, color = 'blue', sides = 't') + labs(x = 'larch fraction (black) & shade-intolerance (blue)')

```

```{r}
#original models
spmx.re.gam.lf <- readRDS('data/model_objects.1/spmx.re.gam.lf.rds')
spmx.re.gam.st <- readRDS('data/model_objects.1/spmx.re.gam.st.rds')
lf.smest <- smooth_estimates(spmx.re.gam.lf, smooth = 's(larch.ba.fraction.pl)') %>% add_confint()

st.smest <- smooth_estimates(spmx.re.gam.st, smooth = 's(shade.tol.pl)') %>% add_confint()

f1a <- ggplot(lf.smest, aes(x = larch.ba.fraction.pl, y = est)) + 
  geom_ribbon(alpha = 0.2, aes(ymin = lower_ci, ymax = upper_ci, x = larch.ba.fraction.pl)) + 
  geom_line() +
  labs(x = 'Larch proportion') +
  scale_y_continuous(breaks = seq(-2, 8, by = 2)) + geom_hline(yintercept = 0, linetype = 'dashed')

f1b <- ggplot(st.smest, aes(x = shade.tol.pl, y = est)) +
  geom_ribbon(alpha = 0.2, aes(ymin = lower_ci, ymax = upper_ci, x = shade.tol.pl)) + 
  geom_line() +
  labs(x = 'Shade intolerance') +
  scale_y_continuous(breaks = seq(-2, 8, by = 2)) +
  scale_x_continuous(n.breaks = 5) + geom_hline(yintercept = 0, linetype = 'dashed')
f1a
f1b

ggplot() + geom_line(data = lf.smest, aes(x = larch.ba.fraction.pl, y = est)) + geom_ribbon(data = lf.smest, aes(x= larch.ba.fraction.pl, y = est, ymin = est-se, ymax = est+se), alpha = 0.2) + 
  geom_line(data = st.smest, aes(x = shade.tol.pl, y = est), color = 'blue') + geom_ribbon(data = st.smest, aes(x = shade.tol.pl, ymin = est-se, ymax = est+se), alpha = 0.2, fill = 'blue') +
  geom_hline(yintercept = 0, linetype = 'dashed') + geom_rug(inherit.aes = F, data = bai.spmx.ids, aes(x = larch.ba.fraction.pl),alpha = 0.2) +
  geom_rug(inherit.aes = F, data = bai.spmx.ids, aes(x = shade.tol.pl), alpha = 0.2, color = 'blue', sides = 't') + labs(x = 'larch fraction (black) & shade-intolerance (blue)')
```

