---
title: "density_plot"
author: "Christian M"
date: "December 9, 2020"
output: html_document
---

```{r setup, include=FALSE}
#RUN THS
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
source("1.readformat.R")
```

```{r}
# drop the SE and CI purpose code data - these are done in "off" years  
#  and seem to involve variable radius plot sampling; I think they
#  represent other data coll efforts --> need to check tho
lolo1 <- lolo1[!(lolo1$PURPOSE_CODE %in% c("SE","CI")),]
table(lolo1$PURPOSE_CODE) # need to figure out what "RR" is? Replacement?

# check whether all installations had 3 plots per cluster; info is needed because 
#  TPA is recorded as 20 tr/ac not 20/3 tr/ac
plot_structure <- aggregate(lolo1$PLOT,
                               by=list(SETTING_ID=lolo1$SETTING_ID,
                                       PURPOSE_CODE=lolo1$PURPOSE_CODE,
                                       myear=lolo1$myear,
                                       cluster=lolo1$cluster),
                            FUN=function(x){length(unique(x))})
unique(plot_structure$x)


# check whether all plots had 3 subplots
lolo1a <- lolo1[!is.na(lolo1$SUBPLOT),]
subplot_structure <- aggregate(lolo1a$SUBPLOT,
                               by=list(SETTING_ID=lolo1a$SETTING_ID,
                                       PURPOSE_CODE=lolo1a$PURPOSE_CODE,
                                       cluster=lolo1a$cluster,
                                       PLOT=lolo1a$PLOT),
                               FUN=function(x){length(unique(x))})
unique(subplot_structure$x)


# just live trees
lolo1_live <- lolo1[!is.na(lolo1$TPA_EQUIV) & lolo1$LIVE_DEAD=="L",]
unique(lolo1_live$TPA_EQUIV)

# what is RR? Looks like it used 20th acre plots for large and 100th acre for small?
unique(lolo1_live$TPA_EQUIV[lolo1_live$PURPOSE_CODE=="RR"])

# all other small tree plots appear to 300th acre
unique(lolo1_live$TPA_EQUIV[lolo1_live$PURPOSE_CODE!="RR" & !is.na(lolo1_live$SUBPLOT)]) %% 300
unique(lolo1_live$TPA_EQUIV[lolo1_live$PURPOSE_CODE!="RR" & is.na(lolo1_live$SUBPLOT)]) 

# fix tpa to account for multiplicity of plots, subplots per cluster
lolo1_live$TPA_EQUIV <- with(lolo1_live, TPA_EQUIV/ifelse(is.na(SUBPLOT),3,9))

# obtain basal area equivalents
lolo1_live$BA_EQUIV <- with(lolo1_live,
                            ifelse(!is.na(DIAMETER),DIAMETER,0)^2 * 
                              (pi/576)* TPA_EQUIV )

# sum to the cluster level
stand_char <- aggregate(lolo1_live[,c("TPA_EQUIV","BA_EQUIV")],
                        by=list(SETTING_ID=lolo1_live$SETTING_ID,
                                myear=lolo1_live$myear,
                                PURPOSE_CODE=lolo1_live$PURPOSE_CODE,
                                cluster=lolo1_live$cluster),
                        sum)
stand_char$DBH_Q <- with(stand_char, sqrt(576*BA_EQUIV/TPA_EQUIV/pi) )
```


```{r}
#density plot
stand_density <- function(settingID){
  a <- stand_char %>% filter(SETTING_ID %in% settingID) %>% mutate("lnDq" = log(DBH_Q), "lnTPA" = log(TPA_EQUIV))
  
ggplot(a, aes(x = lnDq, y = lnTPA, color = as.factor(cluster == 100))) + geom_point() + geom_smooth(se = F)
}

stand_density(unique(stand_char$SETTING_ID))
```

Density/top height
```{r}

#This produces a table which includes setting id, species, measure year, purpose code, and mean height (excluding subplot trees). This is grouped by control plots vs. treatment plots, therefore, this looks at the stand-level

ht <- 
  lolo1_live %>%
  filter(SUBPLOT != c(5,6,7)) %>%
  select(SETTING_ID, SPECIES_SYMBOL, myear, PURPOSE_CODE, cluster, HEIGHT, TPA_EQUIV) %>%
  group_by(SETTING_ID, SPECIES_SYMBOL, myear, PURPOSE_CODE) %>% summarise(mean_ht = mean(HEIGHT))

#going down a rabbith hole to figure out which setting ids have NA's in order to plot ht over time. 
ht %>% group_by(SETTING_ID) %>% summarise(!anyNA(mean_ht)) %>% select(SETTING_ID)

#try it with 1 setting before putting it in a function
#NOTE - cannot get the line to work out. Also had to add species code in filter, but that can be built into function. 
ht1 <-
  lolo1_live %>%
  filter(SUBPLOT != c(5,6,7)) %>%
  select(SETTING_ID, SPECIES_SYMBOL, myear, PURPOSE_CODE, cluster, HEIGHT) %>%
  group_by(SETTING_ID, SPECIES_SYMBOL, myear, PURPOSE_CODE, cluster) %>% summarise(mean_ht = mean(HEIGHT)) %>%
  filter(SETTING_ID == "01160306010006", SPECIES_SYMBOL == "ABLA")

ggplot(ht1, aes(x = myear, y = mean_ht, color = as.factor(cluster))) + geom_point() + geom_smooth(method = "lm")


lo <- lowess(ht1$mean_ht~ht1$myear)
plot(ht1$myear, ht1$mean_ht, col = as.factor(ht1$cluster))
lines(ht1$myear, ht1$mean_ht, col = as.factor(ht1$cluster))

ht_time <- function(settingid){

  
  ggplot(ht, aes(x = myear, y = mean_ht), color = ) + geom_point()
}

#lets try ht vs. density

#filter down to the stand level, and then plot treatment and control ht. density curves(is it a curve?)
abc <- lolo1_live %>% filter(SUBPLOT != c(5,6,7), SETTING_ID == "01160625020040") %>%
  select(SETTING_ID, SPECIES_SYMBOL, myear, PURPOSE_CODE, cluster, HEIGHT, TPA_EQUIV) %>%
  group_by(SETTING_ID, SPECIES_SYMBOL, myear) %>% summarise(mean_ht = mean(HEIGHT))

ggplot()

```

