---
title: "larch.results"
author: "Christian Mercado"
date: "5/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

source('14.results_larch.R')

cm.sq <- 6.4516
cm <- 2.54
```


```{r}
#RMSE table
rmse_size
rmse_dcomp
rmse_site
rmse_re
(rmse_spp.mix.in <- rmse_spp_mix %>% rename('Model' = 'model', 'RMSE \n selected model' = rmse.selected, 'RMSE \nselected alternative' = rmse.sel.alt, 'RMSE \n single best' = rmse.best1, 'RMSE \n FVS' = fvs))
(rmse_spp_mix.t <- rmse_spp_mix %>% mutate(across(c(rmse.selected, rmse.sel.alt, rmse.best1, fvs), ~.x*cm.sq)) %>% rename('Model' = 'model', 'RMSE \n selected model' = rmse.selected, 'RMSE \nselected alternative' = rmse.sel.alt, 'RMSE \n single best' = rmse.best1, 'RMSE \n FVS' = fvs))

rmse_spp_mix.cm <- rmse_spp_mix %>% mutate(across(c(rmse.selected), ~.x*cm.sq)) %>% select(model, rmse.selected) %>% rename('Model' = 'model', 'RMSE \n selected model' = rmse.selected) %>% filter(Model %in% c('NULL', 'Site', 'Random tree', 'Larch Fraction w/ RE', 'Shade tolerance w/ RE'))

a <- summary(re.tree.1)
b <- summary(spmx.re.gam.lf)
c <- summary(spmx.re.gam.st)
d <- summary(site5a.2)
rmses <- c(my.rmse.2(site5a.2)[[2]], my.rmse.2(re.tree.1)[[2]], my.rmse.2(spmx.re.gam.lf)[[2]], my.rmse.2(spmx.re.gam.st)[[2]])
deviance.explained <- 100*c(d$dev.expl, a$dev.expl, b$dev.expl, c$dev.expl)
models <- c('Base model', 'Base model w/ RE', 'Larch proportion', 'Shade-tolerance')

tibble(models, rmses, deviance.explained)


rmse_tb <- tableGrob(rmse_spp_mix.t)
grid.newpage()
grid.draw(rmse_tb)
```

```{r}
concurvity(re.tree.1)
concrvity(re.tree.1, type = 'estimate', pairwise = T)
concrvity(spmx.re.gam.lf, type = 'estimate', pairwise = T)
concrvity(spmx.re.gam.st, type = 'estimate', pairwise = T)
```


```{r partial response curves}
lf.smest <- smooth_estimates(spmx.re.gam.lf, smooth = 's(larch.ba.fraction.pl)') %>% add_confint()
st.prt <- add_partial_residuals(spmx.re.gam.st$model, spmx.re.gam.st, select = 8)
st.smest <- smooth_estimates(spmx.re.gam.st, smooth = 's(shade.tol.pl)') %>% add_confint()
lf.a.smest <- smooth_estimates(spmx.gam.alt.lf, smooth = 's(larch.ba.fraction.pl)') %>% add_confint()
st.a.smest <- smooth_estimates(spmx.gam.alt.st, smooth = 's(shade.tol.pl)') %>% add_confint()

wrk.st <- residuals.gam(spmx.gam.alt.st, type = 'working')
#str(spmx.gam.alt.st$smooth)

#larch fraction
ggplot(lf.smest, aes(x = larch.ba.fraction.pl, y = cm.sq*exp(est))) + 
  geom_ribbon(alpha = 0.2, aes(ymin = cm.sq*exp(lower_ci), ymax = cm.sq*exp(upper_ci), x = larch.ba.fraction.pl)) + 
  geom_line() +
  labs(x = 'Larch ratio', y = 'BAI(cm^2)', title = 'BAI partial response to non-larch:larch') +
  scale_y_continuous(breaks = seq(5, 13.5, by = 1)) + geom_hline(yintercept = cm.sq, linetype = 'dashed')
#shade tolerance
ggplot(st.smest, aes(x = shade.tol.pl, y = cm.sq*exp(est))) +
  geom_ribbon(alpha = 0.2, aes(ymin = cm.sq*exp(lower_ci), ymax = cm.sq*exp(upper_ci), x = shade.tol.pl)) + 
  geom_line() +
  labs(x = 'Shade intolerance', y = 'BAI(cm^2)', title = 'BAI partial response to shade-intolerance') +
  scale_y_continuous(breaks = seq(5, 13.5, by = 1)) + geom_hline(yintercept = cm.sq, linetype = 'dashed') #+
  #geom_point(data = st.prt, aes(x = shade.tol.pl, y = `s(shade.tol.pl)`))
```  

```{r more partial response}
draw(spmx.re.gam.lf, select = 8, rug = F, residuals = T)
draw(spmx.re.gam.st, select = 8, rug = F, residuals = T)
draw(spmx.re.gam.st, select = 8, rug = F, residuals = T, fun = exp)

ggplot(lf.smest, aes(x = larch.ba.fraction.pl, y = exp(est))) + 
  geom_ribbon(alpha = 0.2, aes(ymin = exp(lower_ci), ymax = exp(upper_ci), x = larch.ba.fraction.pl)) + 
  geom_ribbon(alpha = 0.2, data = st.smest, 
              aes(ymin = exp(lower_ci), ymax = exp(upper_ci), x = shade.tol.pl), fill = 'blue') +
  geom_line() +
  geom_line(data = st.smest, aes(x = shade.tol.pl, y = exp(est)), color = 'blue')+
  labs(x = 'larch ratio (black), shade tolerance (blue)', y = 'BAI(in^2)')

ggplot(lf.a.smest, aes(x = larch.ba.fraction.pl, y = exp(est))) + 
  geom_ribbon(alpha = 0.2, aes(ymin = exp(lower_ci), ymax = exp(upper_ci), x = larch.ba.fraction.pl)) + 
  geom_ribbon(alpha = 0.2, data = st.a.smest, 
              aes(ymin = exp(lower_ci), ymax = exp(upper_ci), x = shade.tol.pl), fill = 'blue') +
  geom_line() +
  geom_line(data = st.a.smest, aes(x = shade.tol.pl, y = exp(est)), color = 'blue')+
  labs(x = 'larch ratio (black), shade tolerance (blue)', y = 'BAI(in^2)')

hist((1/(bai.spmx.ids$shade.tol.pl)))

```

```{r diameter curves}
dbh.smest.re <- smooth_estimates(re.tree.1, 's(DIAMETER)') %>% add_confint()
dbh.smest.lf <- smooth_estimates(spmx.re.gam.lf, 's(DIAMETER)')
dbh.smest.st <- smooth_estimates(spmx.re.gam.st, 's(DIAMETER)')

dbh.smest.re.a <- smooth_estimates(re.tree.1alt, 's(DIAMETER)') %>% add_confint()
dbh.smest.lf.a <- smooth_estimates(spmx.gam.alt.lf, 's(DIAMETER)')
dbh.smest.st.a <- smooth_estimates(spmx.gam.alt.st, 's(DIAMETER)')

ggplot() + 
  geom_line(data = dbh.smest.re, aes(x = DIAMETER*cm, y = cm.sq*exp(est)), color = 'black') +
  geom_line(data = dbh.smest.lf, aes(x = DIAMETER*cm, y = cm.sq*exp(est)), color = 'blue') +
  geom_line(data = dbh.smest.st, aes(x = DIAMETER*cm, y = cm.sq*exp(est)), color = 'orange') #+ geom_ribbon(data = dbh.smest.re, aes(ymin = exp(est)-exp(se), ymax = exp(est)+exp(se), x = DIAMETER), linetype = 'dashed', outline.type = 'both', color = 'black', alpha = 0) 
#+
#   geom_ribbon(data = dbh.smest.lf, aes(ymin = est-se, ymax = est+se, x = DIAMETER), 
#                        linetype = 'dashed', outline.type = 'both', color = 'blue', alpha = 0) +
#   geom_ribbon(data = dbh.smest.st, aes(ymin = est-se, ymax = est+se, x = DIAMETER), 
#                        linetype = 'dashed', outline.type = 'both', color = 'orange', alpha = 0) +
  
# draw(re.tree.1, select = 1, rug = F, fun = inv_link(re.tree.1))
# 
# ggplot() + 
#   geom_line(data = dbh.smest.re, aes(x = DIAMETER, y = exp(est)), color = 'black') +
#   geom_ribbon(data = dbh.smest.re, aes(ymin = exp(lower_ci), ymax = exp(upper_ci), x = DIAMETER), 
#                         linetype = 'dashed', outline.type = 'both', color = 'black', alpha = 0.2)

ggplot() + 
  geom_line(data = dbh.smest.re.a, aes(x = DIAMETER*cm, y = cm.sq*exp(est)), color = 'black') +
  geom_line(data = dbh.smest.lf.a, aes(x = DIAMETER*cm, y = cm.sq*exp(est)), color = 'blue') +
  geom_line(data = dbh.smest.st.a, aes(x = DIAMETER*cm, y = cm.sq*exp(est)), color = 'orange')
```

```{r comp-dense curves}

cr.smest.re <- smooth_estimates(re.tree.1, 's(cr)')
cr.smest.lf <- smooth_estimates(spmx.re.gam.lf, 's(cr)')
cr.smest.st <- smooth_estimates(spmx.re.gam.st, 's(cr)')



bal.smest.re <- smooth_estimates(re.tree.1, 's(bal.pl.ratio)')
bal.smest.lf <- smooth_estimates(spmx.re.gam.lf, 's(bal.pl.ratio)')
bal.smest.st <- smooth_estimates(spmx.re.gam.st, 's(bal.pl.ratio)')



ccf.smest.re <- smooth_estimates(re.tree.1, 's(ccf.pl)')
ccf.smest.lf <- smooth_estimates(spmx.re.gam.lf, 's(ccf.pl)')
ccf.smest.st <- smooth_estimates(spmx.re.gam.st, 's(ccf.pl)')



ggplot() + 
  geom_line(data = cr.smest.re, aes(x = cr, y = cm.sq*exp(est)), color = 'black') +
  geom_line(data = cr.smest.lf, aes(x = cr, y = cm.sq*exp(est)), color = 'blue') +
  geom_line(data = cr.smest.st, aes(x = cr, y = cm.sq*exp(est)), color = 'orange')
ggplot() + 
  geom_line(data = bal.smest.re, aes(x = bal.pl.ratio, y = cm.sq*exp(est)), color = 'black') +
  geom_line(data = bal.smest.lf, aes(x = bal.pl.ratio, y = cm.sq*exp(est)), color = 'blue') +
  geom_line(data = bal.smest.st, aes(x = bal.pl.ratio, y = cm.sq*exp(est)), color = 'orange')
ggplot() + 
  geom_line(data = ccf.smest.re, aes(x = ccf.pl, y = cm.sq*exp(est)), color = 'black') +
  geom_line(data = ccf.smest.lf, aes(x = ccf.pl, y = cm.sq*exp(est)), color = 'blue') +
  geom_line(data = ccf.smest.st, aes(x = ccf.pl, y = cm.sq*exp(est)), color = 'orange')



```

```{r alt }
formula(re.tree.1alt)
cr.smest.re.a <- smooth_estimates(re.tree.1alt, 's(cr)')
cr.smest.lf.a <- smooth_estimates(spmx.gam.alt.lf, 's(cr)')
cr.smest.st.a <- smooth_estimates(spmx.gam.alt.st, 's(cr)')

bal.smest.re.a <- smooth_estimates(re.tree.1alt, 's(bal.pl.ratio)')
bal.smest.lf.a <- smooth_estimates(spmx.gam.alt.lf, 's(bal.pl.ratio)')
bal.smest.st.a <- smooth_estimates(spmx.gam.alt.st, 's(bal.pl.ratio)')

ba.smest.re.a <- smooth_estimates(re.tree.1alt, 's(ba.pl)')
ba.smest.lf.a <- smooth_estimates(spmx.gam.alt.lf, 's(ba.pl)')
ba.smest.st.a <- smooth_estimates(spmx.gam.alt.st, 's(ba.pl)')

ggplot() + 
  geom_line(data = cr.smest.re.a, aes(x = cr, y = cm.sq*exp(est)), color = 'black') +
  geom_line(data = cr.smest.lf.a, aes(x = cr, y = cm.sq*exp(est)), color = 'blue') +
  geom_line(data = cr.smest.st.a, aes(x = cr, y = cm.sq*exp(est)), color = 'orange')
ggplot() + 
  geom_line(data = bal.smest.re.a, aes(x = bal.pl.ratio, y = cm.sq*exp(est)), color = 'black') +
  geom_line(data = bal.smest.lf.a, aes(x = bal.pl.ratio, y = cm.sq*exp(est)), color = 'blue') +
  geom_line(data = bal.smest.st.a, aes(x = bal.pl.ratio, y = cm.sq*exp(est)), color = 'orange')
ggplot() + 
  geom_line(data = ba.smest.re.a, aes(x = cm.sq*ba.pl, y = cm.sq*exp(est)), color = 'black') +
  geom_line(data = ba.smest.lf.a, aes(x = cm.sq*ba.pl, y = cm.sq*exp(est)), color = 'blue') +
  geom_line(data = ba.smest.st.a, aes(x = cm.sq*ba.pl, y = cm.sq*exp(est)), color = 'orange')

```


```{r site curves}
formula.gam(re.tree.1)

#asp.smest.re <- smooth_estimates(re.tree.1, 's(asp_sin,asp_cos)')
# asp.smest.lf <- smooth_estimates(spmx.re.gam.lf, 's(asp_sin, asp_cos)')
# asp.smest.st <- smooth_estimates(spmx.re.gam.st, 's(asp_sin, asp_cos)')

sl.smest.re <- smooth_estimates(re.tree.1, 's(slope_pct)')
sl.smest.lf <- smooth_estimates(spmx.re.gam.lf, 's(slope_pct)')
sl.smest.st <- smooth_estimates(spmx.re.gam.st, 's(slope_pct)')

draw(re.tree.1, select = 's(asp_sin,asp_cos)', fun = function(x){cm.sq*exp(x)})
draw(spmx.re.gam.lf, select = 's(asp_sin,asp_cos)', fun = cm.sq*exp)
draw(spmx.re.gam.st, select = 's(asp_sin,asp_cos)', fun = cm.sq*exp)

ggplot() + 
  geom_line(data = sl.smest.re, aes(x = slope_pct, y = cm.sq*exp(est)), color = 'black') +
  geom_line(data = sl.smest.lf, aes(x = slope_pct, y = cm.sq*exp(est)), color = 'blue') +
  geom_line(data = sl.smest.st, aes(x = slope_pct, y = cm.sq*exp(est)), color = 'orange')

```

```{r site alt}
draw(re.tree.1alt, select = 's(asp_sin,asp_cos)', fun = exp)
draw(spmx.gam.alt.lf, select = 's(asp_sin,asp_cos)', fun = exp)
draw(spmx.gam.alt.st, select = 's(asp_sin,asp_cos)', fun = exp)
```



```{r size category curves}
#size
dbh.size

# #dens-comp
# dbh.dcomp
# 
# #site
# dbh.site
# 
# #re
dbh.re

#re w/ larch fraction
dbh.lf

#re w/ shade tol
dbh.st
```

```{r size - ba model}
#ba model versions
dbh.dcomp.a
dbh.site.a
dbh.re.a
dbh.lf.a
dbh.st.a
```

```{r dense-comp curves}

dbh.dcomp
cr.dcomp
bal.dcomp
ccf.dcomp


```

```{r dense-comp curves ba model}
dbh.dcomp.a
cr.dcomp.a
ba.dcomp.a
bal.dcomp.a


```

```{r site curves}

dbh.site
cr.site
bal.site
ccf.site
asp.site
sl.site

```

```{r site curves ba model}
dbh.site.a
cr.site.a
bal.site.a
ba.site.a
asp.site.a

```

```{r re model curves}
dbh.re
cr.re

ccf.re
asp.re
sl.re
bal.re
bal.lf

cr.re
cr.lf

cr.re.a
cr.lf.a

ccf.re
ccf.lf


```

```{r re model ba version}
dbh.re.a
cr.re.a
bal.re.a
ba.re.a
asp.re.a


```

```{r larch fraction}

dbh.lf
cr.lf
bal.lf
ccf.lf
asp.lf
sl.lf


```

```{r larch fraction ba version}

dbh.lf.a
cr.lf.a
bal.lf.a
ba.lf.a
asp.lf.a

```

```{r shade tol}

dbh.st
cr.st
bal.st
ccf.st
asp.st
sl.st


```

```{r shade tol ba version}

dbh.st.a
cr.st.a
bal.st.a
ba.st.a
asp.st.a


```

```{r}
larch.frac.tpa(bai.train) %>% select(larch.ba.fraction.pl, larch.tpa.fraction.pl)
```


