---
title: "species.mixing"
author: "Christian Mercado"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#load packages
library(tidyverse)
library(mgcv)
library(gratia)
library(ggrepel)
library(corrplot)
library(GGally)
library(mgcViz)
source('12.gam_fns.R')
source('12a.models_fit_read.R')

```

```{r load models, include = F}
re.stand.1 <- readRDS('data/model_objects.1/re.stand.1.rds')
re.cluster.1 <- readRDS('data/model_objects.1/re.cluster.1.rds')
re.plot.1 <- readRDS('data/model_objects.1/re.plot.1.rds')
re.tree.1 <- readRDS('data/model_objects.1/re.tree.1.rds')

spmx.re.gam.lf <- readRDS('data/model_objects.1/spmx.re.gam.lf.rds')
spmx.re.gam.st <- readRDS('data/model_objects.1/spmx.re.gam.st.rds')

spmx.gam.alt.lf <- readRDS('data/model_objects.1/spmx.gam.alt.lf.rds')
spmx.gam.alt.st <- readRDS('data/model_objects.1/spmx.gam.alt.st.rds')

# spmx.gam.alt.lf <- readRDS('data/model_objects.1/spmx.gam.alt.lf.rds')
# spmx.gam.alt.st <- readRDS('data/model_objects.1/spmx.gam.alt.st.rds')

re.tree.1alt <- readRDS('data/model_objects.1/re.tree.1alt.rds')


spmx.gam.lf <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(slope_pct) + s(larch.ba.fraction.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))

spmx.gam.st <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(slope_pct) + s(shade.tol.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))

re.list.1 <- list('re.stand.1' = re.stand.1 ,'re.cluster.1' = re.cluster.1, 're.plot.1' = re.plot.1, 're.tree.1' = re.tree.1)

site5a.2 <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(slope_pct), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML')

gam.s1a <- gam(bai~s(DIAMETER), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML') 

gam.null <- gam(bai~1, family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML')

best.6a <- gam(bai~s(DIAMETER) + s(ccf.pl) + s(cr, k = 9), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML')

compd.pl4 <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML')

compd.ba1 <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ba.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML')

site.n5a <-update(compd.pl4, . ~ . + s(asp_sin, asp_cos))

site.n5b <- readRDS('data/model_objects.1/site.n5b.rds')

fvs.full <- gam(bai~elev_m + I(elev_m^2) + sl_asp_sin + sl_asp_cos + slope_pct + I(slope_pct^2) + I(ccf.cl/100) + log.diam + I(bal.cl/100) + cr + I(cr^2) + I(DIAMETER^2) + I(bal.cl/(100*log(DIAMETER+1))) + factor(habclass), data = bai.spmx.ids, family = 'Gamma'(link = log), method = 'ML')

fvs.sz.cmp <- gam(bai~I(ccf.cl/100) + log.diam + I(bal.cl/100) + cr + I(cr^2) + I(DIAMETER^2) + I(bal.cl/(100*log(DIAMETER+1))) + factor(habclass), data = bai.spmx.ids, family = 'Gamma'(link = log), method = 'ML')
summary(fvs.sz.cmp)

fvs.size1 <- gam(bai~log.diam + I(DIAMETER^2), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML')


```

```{r RMSE table}


model <- c('null', 'size', 'density.comp', 'site', 'random.tree', 'larch_fraction.random.tree', 'shade.tol.random.tree')

rmse.selected <- c(my.rmse.2(gam.null)[[2]], my.rmse.2(gam.s1a)[[2]], my.rmse.2(compd.pl4)[[2]], my.rmse.2(site5a.2)[[2]], my.rmse.2(re.tree.1)[[2]], my.rmse.2(spmx.re.gam.lf)[[2]], my.rmse.2(spmx.re.gam.st)[[2]])

rmse.sel.alt <- c(my.rmse.2(gam.null)[[2]], my.rmse.2(gam.s1a)[[2]], my.rmse.2(compd.ba1)[[2]], my.rmse.2(site.n5b)[[2]], my.rmse.2(re.tree.1alt)[[2]], my.rmse.2(spmx.gam.alt.lf)[[2]], my.rmse.2(spmx.gam.alt.st)[[2]])

rmse.best1 <- c(my.rmse.2(gam.null)[[2]], my.rmse.2(gam.s1a)[[2]], my.rmse.2(best.6a)[[2]], my.rmse.2(site.n5a)[[2]], NA, NA, NA)

fvs <- c(my.rmse.2(gam.null)[[2]], my.rmse.2(fvs.size1)[[2]], my.rmse.2(fvs.sz.cmp)[[2]], my.rmse.2(fvs.full)[[2]], NA, NA, NA)

tibble(model, rmse.selected, rmse.sel.alt, rmse.best1, fvs) #rmse.selected.old

# re.model <- c('Stand', 'Cluster', 'Plot', 'Tree')
# rmse.re <- data.frame(t(as.data.frame(lapply(re.list.1, my.rmse.2), )[2,]))
# rmse.re

```

```{r visualtions}

term_names(spmx.re.gam.lf)[2]


gam.visual.comp(site5a.2, site.n5b)

#gam.visual.comp()


gam.visual.comp(spmx.gam.alt.lf, spmx.gam.alt.st)



```



```{r RE spp. mix model}
#library(gamm4)
spmx.re.gam.lf <- readRDS('data/model_objects.1/spmx.re.gam.lf.rds')
  #gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(slope_pct) + s(unique.tree.f, bs = 're') + s(larch.ba.fraction.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 5))

#spmx.re.gam.st <- bam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(slope_pct) + s(unique.tree.f, bs = 're') + s(shade.tol.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 5))

#saveRDS(spmx.re.gam.lf, 'data/model_objects.1/spmx.re.gam.lf.rds')

spmx.re.gam.st <- readRDS('data/model_objects.1/spmx.re.gam.st.rds')
  #gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(slope_pct) + s(unique.tree.f, bs = 're') + s(shade.tol.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 4))


spmx.re.gam.st1 <- readRDS('data/model_objects.1/spmx.re.gam.st1_gamm4.rds')
              #gamm4(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(slope_pct) +  + s(shade.tol.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, REML = F, random = ~(1|unique.tree.f)))

summary(spmx.re.gam.st)
summary(spmx.re.gam.st1$mer)

plot(spmx.re.gam.st, scheme = 1, rug = F, residuals = T, ylim = c(-2.3, 2.5))
plot(spmx.re.gam.st1$gam, scheme = 1, rug = F, residuals = T, ylim = c(-2.3, 2.5))

par(mfrow = c(2,2))
gam.check(spmx.re.gam.st)
gam.check(spmx.re.gam.st1$gam)
```

```{r re spp mix for ALT model}


spmx.gam.alt.lf <- readRDS('data/model_objects.1/spmx.gam.alt.lf.rds')
  #gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ba.pl) + s(asp_sin, asp_cos) + s(unique.tree.f, bs = 're') + s(larch.ba.fraction.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))

spmx.gam.alt.st <- readRDS('data/model_objects.1/spmx.gam.alt.st.rds')
  #gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ba.pl) + s(asp_sin, asp_cos) + s(unique.tree.f, bs = 're') + s(shade.tol.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))

# saveRDS(spmx.gam.alt.lf, 'data/model_objects.1/spmx.gam.alt.lf.rds')
# saveRDS(spmx.gam.alt.st, 'data/model_objects.1/spmx.gam.alt.st.rds')
# 
# saveRDS(spmx.gam.alt.lf, 'C:/Users/cm165878/Box/research_/spmx.gam.alt.lf.rds')
# saveRDS(spmx.gam.alt.st, 'C:/Users/cm165878/Box/research_/spmx.gam.alt.st.rds')

summary(spmx.gam.alt.lf)
summary(spmx.gam.alt.st)


my.rmse.2(spmx.gam.alt.lf)
my.rmse.2(spmx.gam.alt.st)
```


```{r spp. mix no re}


spmx.gam.lf <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(slope_pct) + s(larch.ba.fraction.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))

spmx.gam.st <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ccf.pl) + s(asp_sin, asp_cos) + s(slope_pct) + s(shade.tol.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))

summary(spmx.gam.lf)
summary(spmx.gam.st)

plot.gam(spmx.gam.lf, rug = F, residuals = T, ylim = c(-4,2))
plot.gam(spmx.gam.st, rug = F, residuals = T, ylim = c(-4,2))

gam.check(spmx.gam.lf)
gam.check(spmx.gam.st)

my.rmse.2(spmx.gam.lf)
my.rmse.2(spmx.gam.st)
```

```{r spp. mix no re ALT}

spmx.gam.lf.alt <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ba.pl) + s(asp_sin, asp_cos) + s(larch.ba.fraction.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))

spmx.gam.st.alt <- gam(bai~s(DIAMETER) + s(cr, k = 9) + s(bal.pl.ratio) + s(ba.pl) + s(asp_sin, asp_cos) + s(shade.tol.pl), family = 'Gamma'(link = log), data = bai.spmx.ids, method = 'ML', control = list(nthreads = 3))

summary(spmx.gam.lf.alt)
summary(spmx.gam.st.alt)

for(i in 1:6){
  par(mfrow = c(1,2))
  plot.gam(spmx.gam.lf.alt, rug = F, residuals = F, ylim = c(-4, 2.5), scheme = 1, select = i, main = 'larch fraction')
  plot.gam(spmx.gam.st.alt, rug = F, residuals = F, ylim = c(-4, 2.5), scheme = 1, select = i, main = 'shade tol.')
}

draw(spmx.gam.lf, select = 5)

par(mfrow = c(2,2))
gam.check(spmx.gam.lf.alt)
gam.check(spmx.gam.st.alt)

my.rmse.2(spmx.gam.lf.alt)
my.rmse.2(spmx.gam.st.alt)



```





