

Western larch (\emph{Larix occidentalis} Nutt.) is an important tree species
in the inland northwest region of the USA because of its contribution to
ecological, economic, and cultural values across the region. \emph{L. occidentalis}
is endemic and nearly exclusive to the upper Columbia river watershed within 
Montana, Idaho, Washington, Oregon, and southern British Columbia, and is
well-adapted to the historic climate of the region \citep{Knudsen1968,Schmidt1976,Schmidt1995}.
Additionally, its wood is characterized with desirable lumber qualities 
such as high specific gravity, straight grains, and tight knots 
\citep{KeeganIII1995}. It is the most productive of
the three North American larch species \citep{Rehfeldt2010} and its lumber is often 
commercially available in a mix with Douglas-fir, adding a unique and
localized product value. Further, western larch and its associated
forests provide important habitat to native birds, bears, and ungulates 
\citep{McClelland1999,Schmidt1976}. In the US northern Rocky Mountains,
where fire is historically and currently prevalent, western larch is both uniquely 
fire resistant and a prolific pioneer species on sites following fire \citep{Schmidt1995b}
due to its thick bark, deciduous needles, well-dispersed seeds, and germination 
preference for bare-mineral soil \citep{Schmidt1976,Crotteau2019}. 
\emph{Larix} species also provide unique aesthetic characteristics
throughout the year, coloring hillsides shades of green,
yellow, and brown, depending on the season, adding a colorful representation of
seasonality. 

% However, projected future climate scenarios are likely to impact the
% bioclimatic processes, like precipitation patterns and fire-return intervals, 
% which currently allow larch to fill its niche within this region \citep{Rehfeldt2010}. 
% Adaptive management strategies may ameliorate how these impacts translate to 
% changes in biophysical processes, like evapotranspiration, for instance, that 
% affect tree and forest dynamics \citep{Crotteau2019}. These types of strategies 
% require long-term monitoring to evaluate their efficacy, and 
% threatening these unique values. 


% Western larch naturally grows across a compositional gradient of mixed-species
% forests \citep{Schmidt1988} where interactions among species attributes could impact
% growth and development at individual tree and stand levels.

Western larch naturally grows across a gradient of species-mixtures\citep{Schmidt1995a}. 
It is found in communities with:
Douglas-fir (\emph{Pseudotsuga menziesii} var.\emph{glauca}), 
lodgepole pine (\emph{Pinus contorta}), Engelmann spruce (\emph{Picea engelmanii}),
subalpine fir (\emph{Abies lasiocarpa}), ponderosa pine (\emph{Pinus ponderosa}),
western hemlock (\emph{Tsuga heterophylla}), mountain hemlock (\emph{Tsuga mertensiana}),
and western redcedar (\emph{Thuja plicata}) \citep{Schmidt1995b,Schmidt1995a}. 
It is sometimes managed in even-aged, homogeneous plantations, but more 
typically in mixed-conifer settings where interactions among species 
(or species-mixing) at tree and stand levels may occur. 
Additionally, western larch is classified 
as very intolerant of shade and one of the fastest-growing within
its communities \citep{Baker1949,Schmidt1995a}. 
Larch's prolific regeneration and rapid juvenile growth allows it to 
out-compete other trees and leads to high stand densities \citep{Schmidt1998}.  
Thus, it responds well to density management early in stand development, 
which can have lasting impacts on tree and stand growth \citep{Schaedel2017a}.


% Since stand density closely relates to tree growth \citep{Reineke1933}, 
% the effects of species-mixing on density can translate 
% to modified competition impact tree growth.

The effects that stand density has on tree and stand productivity 
can vary at different levels of species purity in a stand 
depending on community species composition \citep{Condes2013,Brunner2020}. 
Weiskittel et al. (\citeyear{Weiskittel2009a}) found that the 
density of a stand at which self-thinning occurs for a given species was positively 
associated with stand purity, meaning an increase in diversity 
could reduce a site's maximum potential density. In contrast, Pretzsch and Biber 
(\citeyear{Pretzsch2016}) showed that stand carrying capacity was 
positively impacted in more diverse stands. A similar study found that 
maximum density increased in shade intolerant \emph{Pinus ponderosa} and 
\emph{Pseudotsuga menziesii} stands when species-diversity was higher, but in 
shade-tolerant \emph{Abies grandis} stands, the relative impact 
of stand purity on stand density was unimportant \citep{Kimsey2019}. 

Density also modifies inter-tree competition and tree growth, 
where higher density is associated with smaller tree sizes and vice versa
\citep{Oliver1996,Sjolte-Jorgensen1967,Smith1986}. However, 
since species-mixing may be positively, negatively, or not at all 
associated with stand density, the effect of species-mixing on growth can vary. 
Brunner \& Forrester (\citeyear{Brunner2020}) demonstrated that species mixture 
affected tree growth only at high densities for their studied mixture.
Concurrently, in a study of \emph{Abies grandis} and \emph{Pinus ponderosa} mixtures in Oregon,
Maguire and Mainwaring (\citeyear{Maguire2021}) found that 
mixing impacted tree size only at high density at one study site. 
At the other site, however, the number of observations suggesting no species-mixing effect on growth 
outweighed those that did \citep{Maguire2021}. A study of two European 
\emph{Pinus} species showed positive growth associated with 
species-mixing for one species across densities, but no effect at 
all for the other species \citep{Riofrio2019}. Given these results, 
species-mixing effects on tree growth (albeit equivocally) may be more relevant 
at high densities, but the mechanisms that produce 
these effects must be understood for further insight.

% A common thread 
% among the findings of all of these studies is the discussion of 
% shade-tolerance and complementary or competitive relationships among species


% and was attributed 
% to the mixed shade tolerance between species
% 
% 
% resulting effects of mixing-induced density modifications on tree growth may vary
% Given this evidence, and since , and 
% 
% , 
% 
% and density can vary across mixtures, then tree growth is expected to vary 
% across species-mixtures. This effect, however, depends on the species 
% mixture type, as well as on the level of density. 
% 
% 
% 
% As the level of stand purity modifies density, it in turn can alter tree growth, 
% but this effect may vary depending on the level of stocking.
% So if density can vary depending on species-mixture, 
% then competition may be modified, leading to an impact on tree growth.


% Further evidence suggests that species-mixing can interact with stand density 
% in the long term, and that the interplay between the two likely depends
% on the characteristics of species-mixtures and stand types \citep{Brunner2020, Condes2013}.

% These conifer species collectively span the range of shade tolerance and growth rates. 
Variation in shade-tolerance, height growth rate, water use efficiency,
tree architecture, and other species characteristics within mixed-species 
communities can lead to modifications in competitive and/or complementary 
relationships among species \citep{Forrester2017}. 
In these communities, even small differences in such attributes 
can result in altered species growth rates \citep{Riofrio2017,Forrester2017}.
Moreover, ecological niche theory suggests that mixture effects are stronger 
for highly complementary species \citep{Loreau2010}.
Species shade tolerance relates to the physiological and 
morphological characteristics which drive growth \citep{Reich1998}, 
and thus relates to inter-tree competitive dynamics \citep{Canham2006}.
For example, productivity in forests can be enhanced by mixing shade tolerant and 
intolerant species \citep{Zhang2012,Williams2017} where different species' 
light requirement niches (or shade tolerances) are complementary \citep{Thurm2016}. 
Furthermore, quantifying community competition for light may sufficiently 
capture the effects of biodiversity on productivity \citep{Morin2011}, provided 
that inter-tree competition for other resources is accounted for. 
For instance, \cite{Jucker2014} found that the degree of light-use  
complementarity depended on whether below-ground resources were adequate to 
sustain high rates of photosynthesis, and they showed that increases in 
competition for water negated such effects. There is also evidence indicating 
that below-ground competition for resources can be asymmetric among species \citep{Rewald2009}, 
however the resulting effects on productivity may vary 
over time with environmental conditions, as species exploit resources 
differently depending on their growth strategies \citep{delRio2014}. 
\cite{Searle2020} found that positive complementary effects on individual 
tree growth increase with both community shade-tolerance and phylogenetic 
dissimilarity. Specifically, they showed that shade-tolerance can encapsulate 
its effects on inter-specific competition, and that positive niche complementary 
effects on tree growth increase with competition intensity.

% \cite{delRio2014} found 
% that temporal variability may be tied to whether competitive or 
% facilitative effects on growth between species

For stands in the inland northwest region of the United States, 
where relatively low intensity management occurs over a broad area and across 
tree, stand, and site conditions, managers and researchers commonly use the 
Forest Vegetation Simulator \citep[FVS;][]{Dixon2020} to estimate future 
stand dynamics. FVS uses a distance-independent individual tree growth model 
\citep{Stage1973,Wykoff1990} that does not require individual tree locations 
to account for competition, and projects tree growth using tree size, stand density, 
competition, and site variables. 
Its formulation is paralleled by growth models in other regions and countries, 
like the multiple US and Canada regional variants of FVS or PROGNAUS \citep{Monserud1996} 
in Austria. These types of models are widely used because they 
provide an accurate, simple, and efficient basis for projecting tree and stand 
growth \citep{Weiskittel2011}. 
Various studies have evaluated species-mixing effects on tree growth
using the vetted framework of such models. 
One study showed that when incorporated into an individual 
tree growth model, and after accounting for tree, stand, and site conditions, 
species-mixing effects improved predictions \citep{Riofrio2019}. 
\cite{Vospernik2021} found that individual tree basal area increment %\citep{Vospernik2021}
was significantly modified in mixtures after accounting for other factors. 
They observed species-mixing effects on \emph{Larix decidua} in mixtures 
with \emph{Picea abies}, \emph{Pinus cembra}, \emph{Fagus sylvatica}, 
and \emph{Betulus spp.}, where it mutually benefited in mixtures
with \emph{Picea abies} \citep{Vospernik2021}. These findings are similar to 
those of Z\"{o}hrer (\citeyear{Zohrer1969}) where incremental growth was increased %Z&ouml;hrer \citep{Zohrer1969}
in mixtures between shade-tolerant \emph{Picea abies} and shade-intolerant
\emph{Larix decidua}.

Since individual tree growth models can be improved 
by accounting for species-mixing in addition to other variables, it may 
be pertinent to characterizing individual tree growth in mixed-conifer forests 
in the western US. Additionally, since there is evidence of this in 
phylogenetically similar European larch, species-mixing effects may be relevant 
for characterizing western larch growth, as it is a fast growing and 
shade-intolerant species that mixes with various other conifers across the inland northwest. 
The foci of the present study then are to describe 
(i) how community composition impacts the growth of western larch 
given other variables known to impact its growth and 
(ii) how to characterize species-mixing effects on western larch 
within the context of distance-independent, individual-tree 
growth modeling in the inland northwest. 

% Given that density is modified by species-mixing, that larch growth 
% is sensitive to density, and larch's intolerance to shade, 

The objectives of the present study were: 
(i) to identify a 
distance-independent individual tree basal area increment (BAI) model to 
statistically control for variations in tree size, competition, stand density, 
and site productivity in long-term forest inventory data, 
% (ii) identify different types of mixtures that western 
% larch grows in where its growth may be impacted, 
(ii) to determine if western larch BAI varies in pure larch stands versus 
larch-Douglas-fir mixtures or larch-lodgepole pine mixtures after 
accounting for other factors, and
(iii) to compare generalizable species-mixing measures and identify 
if these improve growth estimation across a broad spectrum of mixtures. 
I expected that for a given size, density, and site productivity, larch 
growth would be greater when a larger portion of stand density was made up of 
more shade-tolerant species. This follows the idea that shade-intolerant 
western larch would face less competition for light if neighboring trees 
were more shade-tolerant. For the same reason, I expected that species-mixing 
effects would best be captured by a measure that accounts for different species' 
shade tolerance, as this would address the primary mechanisms behind variations 
in growth, as opposed to simple measures of stand species purity or more complex 
measures of size-density relative to potential maximum crown area (i.e., crown 
competition factor, CCF). 

% larch growth would be positively impacted 
% when in mixtures with more shade-tolerant species, and 
% negatively impacted when mixed with shade-intolerant species as well as in 
% pure western larch stands. 
% Additionally, 




% Western larch grows within pure stands and mixed-species stands alike, 
% and is an important species that is unique to the inland northwest 
% region of north america. Evidence shows that ecological dynamics within 
% mixed species stands can lead to modified density-competition dynamics,
% leading to modified tree growth and stand productivity. 
% Ecological niche theory provides a theoretical foundation for these observed effects.
% Capturing these dynamics can improve estimates of tree growth and stand productivity, 
% aiding in management and research efforts. 
% This study aims to explore the impacts of species-mixing on 
% western larch within the context of individual tree growth models. 

% questions
% \bf{How does community composition (species-mixing) influence the growth of western larch?} 
% \bf{Comparing species-informed measures, how can the effects of species-mixing be best accounted for within an individual-tree growth model?}

% The Forest Vegetation Simulator (FVS;\cite{Dixon2020}), 
% which is used across the region for management planning and research, 
% is driven primarily by an individual tree growth model \citep(Stage1973,Wykoff1990)
 
% Since western larch forests range in species-composition 
% and occur across biophysical conditions, western larch may 
% be subject to the effects of modified competitive or complementary 
% relationships within communities that it grows. 

% due to complementary effects, quantifying community competition for 
% light can sufficiently capture the effects of biodiversity on productivity \citep{Morin2011}.
%  Lebourgeois \citep{Lebourgeois2013}
% found that species mixture modified the growth of \emph{Abies abla} through
% facilitative interactions under drought conditions. In northwestern Montana,
% facilitative and competitive interactions were found to modify growth rates 
% of \emph{Abies lasiocarpa} and \emph{Pinus albicaulis}, depending on environmental
% stressors \citep{Callaway1997}. 

% Additionally, variation of shade tolerance within a community can lead to 
% enhancements on overall community productivity \citep{Zhang2012}. 

% Thus, a shade tolerance informed metric may capture complementarity 
% effects on tree growth and lead to improved estimates thereof. 

% In the case where one focal species is dissimilar 
% from others within its community, competitive 
% dynamics may be effectively captured through a coarse 
% measure of the proportion of the focal species to all others, or stand purity.
% and capturing mixing effects with a stand purity 
% metric can provide insights into this relationship.

% When quantified, shade tolerance may aid in characterizing 
% competition and/or complementarity among species in a mixed-species forest.

% --- Niche complementarity 
% - steed and goeking 2020 talks about niche differentiation in terms of larch and climate
% - phylogenetically dissimilarity may affect tree growth through a reduction in suspeptibility to species specific pests, pathogens, predators. (quote from Searle \& Chen 2020)
% - Original papers (janzen 1970 and Connell 1978)
% - Theory etended to mature plants through resource concentration hypothesis (Parker et al. 2015, groosman et al. 2018)
% - Mature plant communities with more phylogenetically close host species are more susceptable to specialized pest and pathogen outbreak. Thus a tree with phylogenetically distant neighbors may experience less competition and may experience higher growth rates. (Searle \& Chen 2020)

% The mixing of phylogenetically dissimilar species

% Niche complementarity (CITE), or more specifically, the resource concentration 
% hypothesis (CITE parker, grossman), describes conditions where phylogenically
% dissimilar species growing together may experience higher rates 
% of growth from the mixing of traits in a mixed-species forest (CITE. .. .). 
% Previous studies have identified complementary effects among trees with
% differing shade tolerances. \citep{Searle2020} SEARLE 2020 found that such complementary 
% effects on individual tree growth increased with competition intensity. 

% point: It's important to have models that account for processes that drive tree growth which are easy to measure or acquire.
% Individual tree growth models are commonly used to estimate future stand characteristics 
% and conditions to aid in forest management and research. Such models rely on previously identified 
% empirical relationships to estimate growth from tree size, inter-tree competitive dynamics, site conditions, 
% and other readily measured or acquired attributes. Since variables in empirical tree growth models 
% are meant to represent ecological processes from relatively simple metrics and are sometimes meant to 
% be generalized across large geographical areas or conditions, they may fail to accurately estimate 
% tree growth under some conditions. ***X provides evidence here. Y says this.***

% point: empirical growth models are used to estimate future conditions 
% from variables that represent ecological dynamics

% - get after niche complementarity, shade tolerance, weighted density metrics, etc. 
% - add some kind of discussion regarding crown competition factor (ccf paper where he says something about mixed species forests)

% Capturing the effects of species-mixing can be accomplished by various 
% methods, one simply being the incorporation of species-identity into density metrics (CITE?). 
% Several such methods rely on a comparison between mixed-species stands 
% and mono-specific stands (Forrester et al? pretzsch?).
% In the north american west, empirical models such as FVS (CITE) 
% are used to estimate tree growth across a variety of conditions 
% where the model relies on averages from extensive growth samples within 
% a region to provide estimates. Under this paradigm, and where conditions vary so broadly, 
% how can the effects of species-mixing and niche complementarity best be captured in an empirical modeling framework?
% FVS uses crown competition factor (CCF; \citep{Krajicek1961}) which is a species-weighted percent of basal area
% occupied by the theoretical maximum crown area for trees of a given diameter, if they were open grown. 
% This measure is effectively a density that is informed by species crown allometry 
% from which one could infer the relative light use of trees at a site given the stand density, 
% but not the interspecific environmental effects of light-use-diversity on tree growth. 
% 
% Other measures 
% 
% CCF measures density based on a verified relationship between crown width and dbh \citep{Krajicek1961}, 
% and generally follows the following form: \begin{equation}
% \label{eq:}
% CCF = \sum\limits_{i}^{n} \beta_0 + \beta_1 D + \beta_2 D^2
% \end{equation}, where $\beta_i$ parameters represent species-specific coefficents. 
% Values are summed across observations and the measure ultimately provides a percentage of 
% stand basal area occupied by tree crowns. 
% 
% but for the purpose of including species-mixing in empirical models, 

% Evidence of how species-mixing impacts tree growth can shed light on
% relationships that are not currently well-understood if new research is
% expanded to more forest-types. Various studies in Europe have revealed that
% facilitation or competitive reduction in mixed-species stands can lead to
% enhanced productivity when compared to monocultures \citep{Pretzsch2009}.
% This effect is sometimes termed overyielding, with reference to the potential
% for higher than anticipated biomass or volume \citep{Pretzsch2009,Loreau2010}.

% Further evidence suggests that species-mixing can interact with stand density 
% in the long term, and that the interplay between the two likely depends
% on the characteristics of species-mixtures and stand types \citep{Brunner2020, Condes2013}.
% 
% Interactions in communities of variable- and similar- trait
% species within North American \emph{Larix} forests are not well-understood, and 
% thus motivate further investigation to characterize how stand species composition 
% modifies western larch growth dynamics. 

% Reich (\citeyear{Reich1998}) found that \emph{L. laricina} had high levels of growth in both high and low light conditions, compared to other coniferous trees.

% \subsection{Research questions}
% 
% \bf{How does community composition (species-mixing) influence the growth of western larch?} 
% 
% \bf{Comparing species-informed measures, how can the effects of species-mixing be best accounted for within an individual-tree growth model?}

%%% old research questions stuff %%%

% Since there is evidence indicating that species-mixing can impact long-term
% development in temperate forests \citep{Pretzsch2009, Pretzsch2010, Zhang2012},
% I posited that the different physiological drivers motivating growth that
% relate to light interception (i.e. shade tolerance) within an interspecific
% environment can produce appreciable differences in the growth of a species,
% after accounting for tree size, inter-tree competition, site productivity, and stand density. 
% This may happen through the enhancement of competition between species of
% similar shade-tolerance, or competitive reduction between
% species of dissimilar shade-tolerance through niche complementarity
% \citep{Callaway1997, Condes2013,Pretzsch2015, Riofrio2017}. Moreover, 
% complementary or competitive effects of species traits in
% a stand can modify how a species interacts with stand density, 
% and in turn, modify a tree's allometry \citep{Weiskittel2009a}. For example,
% it is known that the density of western larch stands impacts how western 
% larch grows \citep{Schaedel2017a}. However, complementary or competitive interactions
% among species have not been explicitly acknowledged within the context of western larch growth, 
% and may modify density effects on western larch growth, (e.g., a western larch in a high
% density stand may grow more in a mixture with shade-tolerant species than a
% western larch at the same density in a mixture with shade-intolerant species). 

% I predicted that the growth of western larch can respond to species-mixing
% across a gradient of species and may depend on how its surrounding community 
% interacts with light. Specifically, I presume \emph{L. occidentalis} growth will
% be modified positively in mixtures with shade-tolerant species such as 
% \emph{Picea engallmanii}, \emph{Abies grandis}, and \emph{Abies lasiocarpa}. Conversely, 
% I expect that \emph{L. occidentalis} growth will be negatively impacted in mixtures 
% with shade-intolerant \emph{Pinus contorta} and \emph{Pinus ponderosa}. I expect that the 
% roles of mid-tolerant species such as \emph{Pseudotsuga menziesii} in modifying 
% \emph{L. occidentalis} growth will vary, from positive to negative. 

% Therefore, my related research objectives were:
%(i) to identify variables that capture the effect of species-mixing on growth 
% (i) determine if western larch growth varies depending on which type of mixture it is in 
% after accounting for other factors that influence tree growth
% and quantify their respective influences on growth
% quantify the degree to which species-mixing impacts western larch growth, 
% (ii) to determine whether a species shade tolerance informed metric improves growth estimates of western larch trees
% effectively captures the effects of niche complementarity on western larch
% identify whether shade-tolerance, as a measure of interspecificity, captures the effects of mixing,
% (ii) identify, quantify, and compare different species-composition informed metrics within an empirical modelling framework
% the effectiveness of different measures of species-mixing

