\documentclass[12pt, oneside, letterpaper, fleqn]{book}
% fleqn is for left aligned equations
% change oneside to twoside if chapters should all start on odd-numbered pages

%%% Import a bunch of formatting commands, packages
\SweaveInput{options.rnw}

%%% Decide if you want to have figures/tables/floats at the end, or not
\usepackage[tablesfirst,notablist,nofiglist]{endfloat} % or comment out

%%% Line numbering
\linenumbers % or comment this out to suppress line numbering

%%% Actual document begins here
\begin{document}
\SweaveOpts{concordance=TRUE}

%%%% FRONT MATTER
\frontmatter
\thispagestyle{empty} % no header, page number centered on bottom

%%%% TITLE PAGE
% ...can input separate files like this
\SweaveInput{title_page.Rnw}

\pagestyle{plain}

%%%% Other prelim sections...can instead be inserted directly in this file
\chapter*{Acknowledgements}
\addcontentsline{toc}{chapter}{Acknowledgements}

Thanks.

\chapter*{Abstract}
\addcontentsline{toc}{chapter}{Abstract}

The abstract.

\tableofcontents

\addcontentsline{toc}{chapter}{\listfigurename}
\listoftables

\addcontentsline{toc}{chapter}{\listtablename}
\listoffigures

%%%% BODY
\mainmatter
\setlength{\baselineskip}{22pt} % begin double spacing
\chapter{}
\section{Introduction}

Western larch (\emph{Larix occidentalis} Nutt.) is an important tree species
in the inland northwest region of the USA because of its contribution to
ecological, economic, and cultural values across the region. \emph{L. occidentalis}
is endemic and nearly exclusive to the upper Columbia river watershed throughout
Montana, Idaho, Washington, Oregon, and southern British Columbia, and is
well-adapted to the historic climate of the region \citep{Knudsen1968, Schmidt1976,Schmidt1995}.
Additionally, its wood possesses desirable qualities such as high specific gravity,
straight grains, and tight knots \citep{KeeganIII1995}, and it is the most productive of
the three North American larch species \citep{Rehfeldt2010}, adding a unique and
localized product value in the region. Further, western larch and its associated
forests provide important habitat to native birds, bears, and ungulates 
\citep{McClelland1999, Schmidt1976}. In a setting where fire is historically and
currently prevalent, western larch is the most fire resistant of the Northern
Rocky Mountain conifers due to its thick bark and uniquely deciduous needles
\citep{Schmidt1976}. \emph{Larix} species also provide unique aesthetic characteristics
throughout the year with their phenology, coloring hillsides shades of green,
yellow, and brown, depending on the season, adding a colorful representation of
seasonality. However, projected climate scenarios are likely to impact the
biophysical processes that allow larch to fill its niche within this region \citep{Rehfeldt2010},
threatening these unique values. 


Western larch naturally grows across a compositional gradient of mixed-species
forests \citep{Schmidt1988} where interactions among species attributes could impact
growth and development at the individual- and stand-level. Western larch is
classified as very intolerant of shade and one of the fastest-growing within
its communities \citep{Baker1949, Schmidt1988}. It is found in communities with:
Douglas-fir (\emph{Pseudotsuga menziesii}(Mirb.) Franco var. \emph{glauca}), 
lodgepole pine (\emph{Pinus contorta}(Dougl.)), Engelmann spruce (*Picea engellmanii*),
subalpine fir (\emph{Abies lasiocarpa}), ponderosa pine (\emph{Pinus ponderosa}),
western hemlock (\emph{Tsuga heterophylla}), mountain hemlock (\emph{Tsuga mertensiana}),
and western redcedar (\emph{Thuja plicata}) \citep{Schmidt1981a, Schmidt1988}. 
These conifer species collectively span the range of shade tolerance and growth rates. 
A combination of shade-tolerance, height growth rate, water use efficiency,
tree architecture, and other traits within mixed-species communities may lead to
competitive and/or complementary relationships among species \citep{Forrester2017}.
Mixing these characteristics can result in altered species growth rates \citep{Forrester2017},
even from small differences in such traits \citep{Riofrio2017}. Lebourgeois \citep{Lebourgeois2013}
found that species mixture modified the growth of \emph{Abies abla} through
facilitative interactions under drought conditions. In northwestern Montana,
facilitative and competitive interactions were found to modify growth rates 
of \emph{Abies lasiocarpa} and \emph{Pinus albicaulis}, depending on environmental
stressors \citep{Callaway1997}. Since larch forests range in species-composition 
and occur across biophysical conditions, western larch may be subject to 
competitive or complementary relationships within communities that it grows.  

--- Niche complementarity 
- steed and goeking 2020 talks about niche differentiation in terms of larch and climate
- phylogenetically dissimilarity may affect tree growth through a reduction in suspeptibility to species specific pests, pathogens, predators. (quote from Searle \& Chen 2020)
- Original papers (janzen 1970 and Connell 1978)
- Theory etended to mature plants through resource concentration hypothesis (Parker et al. 2015, groosman et al. 2018)
- Mature plant communities with more phylogenetically close host species are more susceptable to specialized pest and pathogen outbreak. Thus a tree with phylogenetically distant neighbors may experience less competition and may experience higher growth rates. (Searle \& Chen 2020)

Niche complementarity (CITE), or more specifically, the resource concentration 
hypothesis (CITE parker, grossman), describes conditions where phylogenically
dissimilar species growing together may experience higher rates 
of growth from the mixing of traits in a mixed-species forest (CITE. .. .). 
Previous studies have identified complementary effects among trees with
differing shade tolerances. \citep{Searle2020} SEARLE 2020 found that such complementary 
effects on individual tree growth increased with competition intensity. 

point: It's important to have models that account for processes that drive tree growth which are easy to measure or acquire.
Individual tree growth models are commonly used to estimate future stand characteristics 
and conditions to aid in forest management and research. Such models rely on previously identified 
empirical relationships to estimate growth from tree size, inter-tree competitive dynamics, site conditions, 
and other readily measured or acquired attributes. Since variables in empirical tree growth models 
are meant to represent ecological processes from relatively simple metrics and are sometimes meant to 
be generalized across large geographical areas or conditions, they may fail to accurately estimate 
tree growth under some conditions. ***X provides evidence here. Y says this.***

point: species mixing can be captured by different metrics, but not always in the same way? 
- get after niche complementarity, shade tolerance, weighted density metrics, etc. 
- add some kind of discussion regarding crown competition factor (ccf paper where he says something about mixed species forests)



Capturing the effects of species-mixing can be accomplished by various 
methods, one simply being the incorporation of species-identity into density metrics (CITE?). 
Several such methods rely on a comparison between mixed-species stands 
and mono-specific stands (Forrester et al? pretzsch?).
In the north american west, empirical models such as FVS (CITE) 
are used to estimate tree growth across a variety of conditions 
where the model relies on averages from extensive growth samples within 
a region to provide estimates. Under this paradigm, and where conditions vary so broadly, 
how can the effects of species-mixing and niche complementarity best be captured in an empirical modeling framework?
FVS uses crown competition factor (CCF; \citep{Krajicek1961}) which is a species-weighted percent of basal area
occupied by the theoretical maximum crown area for trees of a given diameter, if they were open grown. 
This measure is effectively a density that is informed by species crown allometry 
from which one could infer the relative light use of trees at a site given the stand density, 
but not the interspecific environmental effects of light-use-diversity on tree growth. 


Other measures 

CCF measures density based on a verified relationship between crown width and dbh \citep{Krajicek1961}, 
and generally follows the following form: \begin{equation}
\label{eq:}
CCF = \sum\limits_{i}^{n} \beta_0 + \beta_1 D + \beta_2 D^2
\end{equation}, where $\beta_i$ parameters represent species-specific coefficents. 
Values are summed across observations and the measure ultimately provides a percentage of 
stand basal area occupied by tree crowns. 

but for the purpose of including species-mixing in empirical models, 


Evidence of how species-mixing impacts tree growth can shed light on
relationships that are not currently well-understood if new research is
expanded to more forest-types. Various studies in Europe have revealed that
facilitation or competitive reduction in mixed-species stands can lead to
enhanced productivity when compared to monocultures \citep{Pretzsch2009}.
This effect is sometimes termed overyielding, with reference to the potential
for higher than anticipated biomass or volume \citep{Pretzsch2009}. 
Further evidence suggests that mixture can interact with stand density 
in the long term, and that the interplay between the two likely depends
on the characteristics of species-mixtures and stand types \citep{Brunner2020, Condes2013}.
In a study of \emph{Abies grandis} (shade-tolerant) and \emph{Pinus ponderosa} (shade-intolerant)
mixtures in Oregon, USA, mixing impacted volume growth (only) at low spacing
and was attributed to the light-use characteristics of each species \citep{Maguire2021}. 
Vospernik 2021 found that individual tree basal area increment %\citep{Vospernik2021}
was significantly modified in mixtures of species with different traits, 
compared to mixtures of species with similar traits. Concerning larch, they
observed mixing-effects on \emph{Larix decidua} in mixtures with \emph{Picea abies}, \emph{Pinus cembra}, 
\emph{Fagus sylvatica}, and \emph{Betulus spp.}, where it mutually benefited in mixtures
with *\emph{Picea abies} \citep{Vospernik2021}. These findings are similar to 
those of Z\"{o}hrer 1969 where incremental growth was increased %Z&ouml;hrer \citep{Zohrer1969}
in mixtures between shade-tolerant \emph{Picea abies} and shade-intolerant
\emph{Larix decidua}. Interactions in communities of variable- and similar- trait
species within North American \emph{Larix} forests are not well-understood, and 
thus motivate further investigation to characterize how stand species composition 
modifies western larch growth dynamics. 

\subsection{Research questions}

Given the above, I investigated the following: %lines of inquiry, hypotheses, and predictions:

\emph{How **much** does species mixing influence the growth of western larch?} 
%alternative: How does species-mixing impact basal area increment of western larch?

Since there is evidence indicating that species-mixing can impact long-term
development in temperate forests \citep{Pretzsch2009, Pretzsch2010, Zhang2012},
I posit that the different physiological drivers motivating growth that
relate to light interception (i.e. shade tolerance) within an interspecific
environment can produce appreciable differences in the growth of a species,
after accounting for tree size, inter-tree competition, site productivity, and stand density. 
This may happen through the enhancement of competition between species of
similar shade-tolerance, or competitive reduction between
species of dissimilar shade-tolerance through niche complementarity
{Callaway1997, Condes2013,Pretzsch2015, Riofrio2017}. Further, 
I suggest that complementary or competitive effects of species traits in
a stand can modify how a species interacts with stand density. For example,
it is known that the density of western larch stands impacts how western 
larch grows \citep{Schaedel2017a}. However, complementary or competitive interactions
among species have not been explicitly acknowledged within this context, and may modify
density effects on western larch growth, (e.g., a western larch in a high
density stand may grow more in a mixture with shade-tolerant species than a
western larch at the same density in a mixture with shade-intolerant species). 

I predict that the growth of western larch can respond to species-mixing
across a gradient of species, depending on how its surrounding community 
interacts with light. Specifically, I presume \emph{L. occidentalis} growth will
be modified positively in mixtures with shade-tolerant species such as 
\emph{Picea engallmanii}, \emph{Abies grandis}, and \emph{Abies lasiocarpa}. Conversely, 
I expect that \emph{L. occidentalis} growth will be negatively impacted in mixtures 
with shade-intolerant \emph{Pinus contorta} and \emph{Pinus ponderosa}. I expect that the 
roles of mid-tolerant species such as \emph{Pseudotsuga menziesii} in modifying 
\emph{L. occidentalis} growth will vary, from positive to negative, if mixing effects
are present at all. 

Therefore, my related research objectives were:
(i) to identify variables that \emph{explicitly} capture the effect of species-mixing on growth and 
quantify their respective influences on growth
% quantify the degree to which species-mixing impacts western larch growth, 
(ii) to determine whether species shade tolerance effectively captures the effects of niche complementarity on western larch
% identify whether shade-tolerance, as a measure of interspecificity, captures the effects of mixing,
(iii) compare and contrast different measures of species-mixing

\section{Methods}
\subsection{Tree growth data}

The Forest Vegetation Simulator (FVS) is a distance-independent, individual 
tree forest growth model that is widely used in the western United States 
to predict tree and stand growth as well as to evaluate management decisions 
{Dixon2020}. To establish a monitoring protocol for the FVS model,
the USDA Forest Service Region 1 developed long-term permanent growth plot
clusters (PGPs) in managed stands across the inland northwest (NW Montana and northern Idaho),
referred herein to as the PGP program. The initial goal of the PGP 
program was to remeasure the selected stands at regular increments of 
5-10 years in order to provide a robust growth increment data set. 
Various stand measurements were initialized and then remeasured between 
1980 and 2002. The program was then paused, and was only recently revisited 
in 2018 and 2021, creating a wide gap between recent measurements and reducing 
consistency of measurement intervals. 

Each PGP stand consists of 4 plot-clusters: 1 untreated control plot cluster 
and 3 treatment plot clusters, the latter were treated with commercial 
thinning or precommercial thinning, depending on stand age and maturity. 
Stand prescriptions determined target residual densities by species for
the stand in the treatment areas, providing a side-by-side comparison between
control and treatments under similar stand and site conditions. The location 
of control and treatment plots were determined by random selection of (x,y) 
coordinates on a grid laid over a map of the stand. To ensure that the control 
plots were not affected by nearby thinning treatments, an unthinned buffer was
placed around control clusters. Every cluster is comprised of three ~202$m^2$ 
large-tree, fixed-radius plots, with each plot containing three ~13.5 $m^2$ 
small tree fixed-radius sub-plots. Data for trees in large-tree plots were taken 
based on whether a tree was above a specified diameter threshold. 
The diameter thresholds varied across and within stands 
(across control and treatment plots), as well as within clusters over
time. Yet the large trees were tagged and distance and azimuth to plot center
were taken. Heights were taken on only a subset of large trees due to the
operational challenges and added time of measuring tree height. Small tree 
data were recorded for trees greater than or equal to ~15cm in height from 
the ground, and up to the specified diameter threshold. 

During the summer of 2018, a re-measurement campaign targeted various 
accessible stands with at least 3 previously recorded measurements on
the Lolo National Forest. During the summer of 2021, PGP stands on the
Lolo and Kootenai National Forests that were previously measured at least
3 times and that were composed of >50\% overstory western larch (determined
by most recent measurement) were targeted for remeasurement. Stands across 
the remeasured PGPs were spread between $46^{\circ}$ N and $49^{\circ}$ N, and 
between 800 and 1700 $m$ above sea level. Stands were primarily on north-facing aspects. 
Soil conditions were variable from site-to-site, but most were a silty-loam texture.
Species composition varied between almost pure western larch to mixed conifer
forests composed of western larch, Douglas-fir, Engelmann spruce, grand fir, 
subalpine fir, western hemlock, mountain hemlock, western red cedar,
cottonwood, and quaking aspen.

\subsection{Data analysis}

I used generalized additive mixed models (GAMMs) to model annual basal area increment (BAI) of western larch 
and to evaluate effects of predictors on BAI. 
Model selection followed the methodologies of Wykoff 1990 and Vospernik 2021 %\citep{Wykoff1990}{-Vospernik2021}
, with GAMMs used to select variables and examine 
predictor effects on the resulting modeled relationship. GAMMs allow for
flexibility in model fitting and an allowance for non-linear 
relationships across variables \citep{Zhao2005}. Contrary to traditional 
parametric modeling approaches, GAMMs let the data determine the 
shape of the functional relationships by fitting predictors with 
smooth functions instead of specific parametric forms \citep{Robinson2011}.

The following steps outline the modeling workflow that I used:
(i) evaluating and estimating potential explanatory variables 
in the available data set based on established relationships
with the dependent variable (BAI), (ii) sequentially
selecting predictor variables within pre-determined groups 
through a novel pragmatic variable selection approach to identify
a base-model structure for the GAM, (iii) evaluating random effects
due to hierarchical groupings in the sample-design, and 
(iv-a) assess whether larch growth varies across different types of mixtures
(iv-b) assessing effects produced by identified species-mixing variables. 

For (i), explanatory variables were identified based on availability 
in the PGP data set and whether they could be calculated from the 
available data. Variables contained in established and widely-used
empirical models, such as the diameter growth model in FVS \textbf{(*CITE*)},
were considered because, 1. the PGP data collection focused on such
variables, and 2. these variables are relatively easy to collect 
and commonly found in long-term data collection efforts similar to
the PGP data. This allows for the potential expansion of these 
methodologies to other, similar works, given that they produce 
reliable estimates in this study. Variables considered that were 
beyond the scope identified above, related primarily to site 
conditions. \textbf{**ADD TABLE that lists variables from the ln(DDS) model, as well as variables not in that model in BOLD text?**} 
Once explanatory variables were identified for consideration,
they were then grouped into the following categories: tree size,
density and competition, site, and species-mixing.  

The following steps outline the pragmatic variable selection
approach mentioned in step (ii) above:

\begin{enumerate}
  \item Evaluate co-linearity of within-group predictors with each other to help avoid redundant inclusion of variables. Any pair-wise linear relationship with a correlation coefficient of 0.7 or higher was not considered together. (R-squared of .49 or higher). This was chosen as the cutoff because .7 correlation means that variance is roughly 50\% accounted for between variables. Additionally, variables known to represent the same processes, like tree basal area and diameter, were not considered together to avoid redundancies and reduce model complexity. 
  \item Only necessary or inherent interactions were considered, such as an interaction between sin(aspect) and cos(aspect). 
  \item Different groups of variables within groups were compared with RMSE. 
  \item Ultimately, the lowest RMSE version within each group was chosen based on the above workflow.
  \item Once selections are made based on the above process, then a concurvity assessment is made within each group. If concurvity is greater than 0.8 for a particular set of terms, *such terms will be scrutinized.* (Johnston et al 2019 uses a very low concurvity cutoff. It oftentimes is arbitrary). 
\end{enumerate}


%2.%*These two were inherent because they are derived from the same variable, aspect, which cannot be used in its raw form due to scaling issues. The sin/cos transformation and the resulting interaction term allows this variable to represent aspect in a way that parses out east-west from north-south. Model comparisons were made with their inclusion and without.*


% 3.*For example, in the site variables group, 3 different groups were compared - heatload, site index, and raw topographic variables. The model bearing the lowest RMSE (highest predictive accuracy) was selected. These groups were derived as a result of the colinearity assessments as well as prior knowledge that heatload is derived from topographic variables and site index is meant to serve as a catch-all that accounts for all site variables. In the case of site variables as well, a stand categorization intercept was evaluated against the other within-group groups to account for site effects. *

Step (iii) Random effects

Step (iv) species mixing

\subsubsection{Within-group dimensional reduction}

Selecting variables within each group posed challenges due to the 
number of predictors, colinearity and/or concurvity among variables
and terms, and the numerous potential interactions between variables
within groups. This required a firmly-structured process where
co-variate relationships are assessed. 

**DEFINE CONCURVITY** (Hastie and Tibshirani 1990)

*curse of dimensionality of nonparametric functions* Wood(2004) 
stable and efficient multiple smoothing parameter estimation for
generalized additive models
*Sure-independence screening*

Prior to implementing the steps here, assessment of co-linearity
was performed between variables within each group, since there is
some amount of redundancy within groups. This assessment was made 
through plotting each variable with each other variable, identifying
if there is a relationship through graphical analysis, and then 
evaluating the strength of linear relationships with r-squared values. 
Additionally, if one variable is derived from another present, 
these will not be considered as covariates in the same model.

\subsubsection{Evaluating species mixing}

Once a parsimonious base-model is selected, species-mixing variables 
will then be added to detect if there is a species-mixing effect. 
Further elaboration on applying this approach will be explained in
the following text. **The following equation** (Equation...xxx) 
represents the modeling framework: 

\begin{equation}
\label{eq:}
g(E(Y)) = \beta_0 + f_1(x_1) + f_2(x_2) + ... +f_i(x_i)
\end{equation}

where $g()$ represents a link function, $E(Y)$ represents the expected 
value of a dependent variable $(Y)$ of interest, $\beta_0$ represents 
an intercept, and $f_i$ represents a non-linear function applied to an 
independent variable, $x_i$. For predictor variables displayed by groups, see Table %\@ref(tab:table2).

\subsection{Basal Area Increment Model}







Here is an equation:
\begin{align}
B & = \frac{2^x}{\sin{\theta}} \sum_{i=1}^N y_i^3 \\ \nonumber
& = 3
\end{align}

\section{A second section}
\subsection{With one subsection}

Here is a code chunk.
<<no_need_for_a_name>>=
10^3
@
and another without the call showing.
<<no_need_for_a_name,echo=F>>=
10^3
@
and you can also do inline \Sexpr{round(pi,5)}.

\chapter{Chunks of extended abstract}

Western larch (\emph{Larix occidentalis}) is an important tree species that is 
exclusive to the inland northwest region of North America %[@Knudsen1968; @Schmidt1976; @Schmidt1995]. 
\citep{Knudsen1968,Schmidt1976,Schmidt1995}.
It is very intolerant of shade, and grows across a wide range 
of communities with both shade-tolerant and -intolerant species %[@Baker1949; @Schmidt1988]. 
A growing body of evidence suggests that species traits in mixed-species 
forest communities can impact tree growth relationships %[@Forrester2017; @Riofrio2017]. 
The objectives of this research are: 
\begin{enumerate}
\item
to identify whether community species composition impacts the growth 
of western larch after accounting for other influential factors, 
\item to identify if a stand average shade-tolerance more effectively 
captures species-mixing effects on growth when compared to a less 
specific relative abundance metric, and
\item to quantify the degree to which 
species-mixing impacts the growth of western larch (if an effect is observed).
\end{enumerate}

As shown in Fig.~\ref{fig:junk}, there are many references to consider.
\begin{figure}\centering
%\includegraphics[width=\textwidth]{../extab_refs.JPG}
\includegraphics[width=2in]{../extab_refs.JPG}
\caption{This is a figure.}\label{fig:junk}
\end{figure}

Next I have a table, called Table \ref{tab:fake}.
\begin{table}\centering
\caption{This is my table.}\label{tab:fake}
\begin{tabular}{cc}
\hline
Row 1 & Column 2 \\ \hline
1 & 2 \\
3 & 4 \\ \hline
\end{tabular}
\end{table}

%%%% BACK MATTER
\backmatter
\chapter*{Literature Cited}
\addcontentsline{toc}{chapter}{Literature Cited}
\bibliography{../zotero_library}{}
% \cite{*} % use this to list all entries in bib file

\end{document}
