\documentclass[12pt, oneside, letterpaper, fleqn]{book}
% fleqn is for left aligned equations
% change oneside to twoside if chapters should all start on odd-numbered pages

%%% Import a bunch of formatting commands, packages
\SweaveInput{options.rnw}

%%% Decide if you want to have figures/tables/floats at the end, or not
\usepackage[tablesfirst,notablist,nofiglist]{endfloat} % or comment out

%%% Line numbering
\linenumbers % or comment this out to suppress line numbering

%%% Actual document begins here
\begin{document}
\SweaveOpts{concordance=TRUE}

%%%% FRONT MATTER
\frontmatter
\thispagestyle{empty} % no header, page number centered on bottom

%%%% TITLE PAGE
% ...can input separate files like this
\SweaveInput{title_page.Rnw}

\pagestyle{plain}

%%%% Other prelim sections...can instead be inserted directly in this file
\chapter*{Acknowledgements}
\addcontentsline{toc}{chapter}{Acknowledgements}

Thanks.

\chapter*{Abstract}
\addcontentsline{toc}{chapter}{Abstract}

TBD

\tableofcontents

\addcontentsline{toc}{chapter}{\listfigurename}
\listoftables

\addcontentsline{toc}{chapter}{\listtablename}
\listoffigures

%%%% BODY
\mainmatter
\setlength{\baselineskip}{22pt} % begin double spacing
\chapter{Introduction}
% \section{}



% Western larch grows within pure stands and mixed-species stands alike, 
% and is an important species that is unique to the inland northwest 
% region of north america. Evidence shows that ecological dynamics within 
% mixed species stands can lead to modified density-competition dynamics,
% leading to modified tree growth and stand productivity. 
% Ecological niche theory provides a theoretical foundation for these observed effects.
% Capturing these dynamics can improve estimates of tree growth and stand productivity, 
% aiding in management and research efforts. 
% This study aims to explore the impacts of species-mixing on 
% western larch within the context of individual tree growth models. 

Western larch (\emph{Larix occidentalis} Nutt.) is an important tree species
in the inland northwest region of the USA because of its contribution to
ecological, economic, and cultural values across the region. \emph{L. occidentalis}
is endemic and nearly exclusive to the upper Columbia river watershed within 
Montana, Idaho, Washington, Oregon, and southern British Columbia, and is
well-adapted to the historic climate of the region \citep{Knudsen1968,Schmidt1976,Schmidt1995}.
Additionally, its wood is characterized with desirable lumber qualities 
such as high specific gravity, straight grains, and tight knots 
\citep{KeeganIII1995}. It is the most productive of
the three North American larch species \citep{Rehfeldt2010} and its lumber is often 
commercially available in a mix with Douglas-fir lumber, adding a unique and
localized product value. Further, western larch and its associated
forests provide important habitat to native birds, bears, and ungulates 
\citep{McClelland1999,Schmidt1976}. In the US northern Rocky Mountains,
where fire is historically and currently prevalent, western larch is both uniquely 
fire resistant and a prolific pioneer species on sites following fire \citep{Schmidt1981}
due to its thick bark, deciduous needles, well-dispersed seeds, and germination 
preference for bare-mineral soil \citep{Schmidt1976,Crotteau2019}. 
\emph{Larix} species also provide unique aesthetic characteristics
throughout the year, coloring hillsides shades of green,
yellow, and brown, depending on the season, adding a colorful representation of
seasonality. 

% However, projected future climate scenarios are likely to impact the
% bioclimatic processes, like precipitation patterns and fire-return intervals, 
% which currently allow larch to fill its niche within this region \citep{Rehfeldt2010}. 
% Adaptive management strategies may ameliorate how these impacts translate to 
% changes in biophysical processes, like evapotranspiration, for instance, that 
% affect tree and forest dynamics \citep{Crotteau2019}. These types of strategies 
% require long-term monitoring to evaluate their efficacy, and 
% threatening these unique values. 


% Western larch naturally grows across a compositional gradient of mixed-species
% forests \citep{Schmidt1988} where interactions among species attributes could impact
% growth and development at individual tree and stand levels.

Western larch naturally grows across a gradient of species-mixtures 
in mixed-species forests \citep{Schmidt1988}. It is found in communities with:
Douglas-fir (\emph{Pseudotsuga menziesii} var.\emph{glauca}), 
lodgepole pine (\emph{Pinus contorta}), Engelmann spruce (\emph{Picea engellmanii}),
subalpine fir (\emph{Abies lasiocarpa}), ponderosa pine (\emph{Pinus ponderosa}),
western hemlock (\emph{Tsuga heterophylla}), mountain hemlock (\emph{Tsuga mertensiana}),
and western redcedar (\emph{Thuja plicata}) \citep{Schmidt1981a,Schmidt1988}. 
Western larch is classified as very intolerant of shade and one of the fastest-growing within
its communities \citep{Baker1949,Schmidt1988}. 
Larch's prolific regeneration and rapid juvenile growth allows it to 
out-compete other trees, which can lead to high stand density \citep{Schmidt1998}.  
Thus, it responds well to density management early in stand development, 
which can have lasting impacts on tree and stand growth \citep{Schaedel2017a}.
It is sometimes managed in even-aged, homogeneous plantations, but more 
typically is managed in mixed-conifer settings where interactions among species 
at tree and stand levels may occur. 

% Since stand density closely relates to tree growth \citep{Reineke1933}, 
% the effects of species-mixing on density can translate 
% to modified competition impact tree growth.

The effects that stand density has on tree and stand productivity 
can vary at different levels of species purity in a stand 
depending on community species composition \citep{Condes2013,Brunner2020}. 
Weiskittel et al. (\citeyear{Weiskittel2009a}) found that the 
density of a stand at which self-thinning occurs for a given species was positively 
associated with stand purity, meaning an increase in diversity 
could reduce a site's maximum potential density. In contrast, Pretzsch and Biber 
(\citeyear{Pretzsch2016}) showed that stand carrying capacity was 
positively impacted in more diverse stands. A similar study found that 
maximum stand density increased in shade intolerant \emph{Pinus ponderosa} and 
\emph{Pseudotsuga menziesii} when species-diversity was higher, but in 
shade-tolerant \emph{Abis grandis}, the relative impact 
of stand purity on stand density was unimportant \citep{Kimsey2019}. 

Density modifies inter-tree competition and tree growth, 
where higher density is associated with smaller tree sizes and vice versa
\citep{Oliver1996,Sjolte-Jorgensen1967,Smith1986}. However, 
since species-mixing may be positively, negatively, or not at all 
associated with stand density, the effect of species-mixing on growth can vary. 
Brunner \& Forrester (\citeyear{Brunner2020}) demonstrated that species mixture 
affected tree growth only at high densities for their studied mixture.
Concurrently, in a study of \emph{Abis grandis} and \emph{Pinus ponderosa} mixtures in Oregon,
Maguire and Mainwaring (\citeyear{Maguire2021}) found that 
mixing impacted tree size only at high density at one study site. 
At the other site, however, the number of observations suggesting no effect on growth 
outweighed those that did \citep{Maguire2021}. A study of two European 
\emph{Pinus} species showed positive growth associated with 
species-mixing for one species across densities, but no effect at 
all for the other species \citep{Riofrio2019}. Given these results, 
species-mixing effects on tree growth (albeit equivocally) may be more relevant 
at high densities, but the mechanisms that produce 
these effects must be understood for further insight.

% A common thread 
% among the findings of all of these studies is the discussion of 
% shade-tolerance and complementary or competitive relationships among species


% and was attributed 
% to the mixed shade tolerance between species
% 
% 
% resulting effects of mixing-induced density modifications on tree growth may vary
% Given this evidence, and since , and 
% 
% , 
% 
% and density can vary across mixtures, then tree growth is expected to vary 
% across species-mixtures. This effect, however, depends on the species 
% mixture type, as well as on the level of density. 
% 
% 
% 
% As the level of stand purity modifies density, it in turn can alter tree growth, 
% but this effect may vary depending on the level of stocking.
% So if density can vary depending on species-mixture, 
% then competition may be modified, leading to an impact on tree growth.


% Further evidence suggests that species-mixing can interact with stand density 
% in the long term, and that the interplay between the two likely depends
% on the characteristics of species-mixtures and stand types \citep{Brunner2020, Condes2013}.

% These conifer species collectively span the range of shade tolerance and growth rates. 
Variation in shade-tolerance, height growth rate, water use efficiency,
tree architecture, and other species characteristics within mixed-species 
communities can lead to modifications in competitive and/or complementary 
relationships among species \citep{Forrester2017}. 
In these communities, even small differences in such attributes 
can result in altered species growth rates \citep{Riofrio2017,Forrester2017}.
Moreover, ecological niche theory suggests that mixture effects are stronger 
for highly complementary species \citep{Loreau2010}.
Species shade tolerance relates to the physiological and 
morphological characteristics which drive growth \citep{Reich1998}, 
and thus relates to inter-tree competitive dynamics \citep{Canham2006}.
For example, productivity in forests can be enhanced by mixing shade tolerant and 
intolerant species \citep{Zhang2012,Williams2017} where different species' 
light requirement niches (or shade tolerances) are complementary \citep{Thurm2016}. 
Furthermore, quantifying community competition for light may sufficiently 
capture the effects of biodiversity on productivity \citep{Morin2011}, given 
that inter-tree competition for other resources is accounted for. 
For instance, \cite{Jucker2014} found that the degree of light-use  
complementarity depended on whether below-ground resources were adequate to 
sustain high rates of photosynthesis, and they showed that increases in 
competition for water negated such effects. There is also evidence indicating 
that below-ground competition for resources can be asymmetric among species \citep{Rewald2009}, 
however the resulting effects on productivity may vary 
over time with environmental conditions, as species exploit resources 
differently depending on their growth strategies \citep{delRio2014}. 
\cite{Searle2020} found that positive complementary effects on individual 
tree growth increase with both community shade-tolerance and phyologenetic 
dissimilarity, showing that shade-tolerance can encapsulate its effects on 
inter-specific competition, and that positive niche complementary 
effects on tree growth increase with competition intensity.

% \cite{delRio2014} found 
% that temporal variability may be tied to whether competitive or 
% facilitative effects on growth between species

For stands in the inland northwest region of the United States, 
where relatively low intensity management occurs over a broad area and across 
tree, stand, and site conditions, managers and researchers commonly use the 
Forest Vegetation Simulator \citep[FVS;][]{Dixon2020} variant to estimate future 
stand dynamics. FVS uses a distance-independent individual tree growth model 
\citep{Stage1973,Wykoff1990} that does not require individual tree locations 
to measure competition, and projects tree growth using tree size, stand density, 
competition, and site variables. 
Its formulation is paralleled by growth models in other regions and countries, 
like the multiple US and Canada regional variants of FVS or PROGNAUS \citep{Monserud1996} 
in Austria. These types of models are widely used because they 
provide an accurate, simple, and efficient basis for projecting tree and stand 
growth \citep{weiskittel2011forest}. 
Various studies have evaluated species-mixing effects on tree growth
using the solid framework of such models. 
One study showed that when incorporated into an individual 
tree growth model, and after accounting for tree, stand, and site conditions, 
species-mixing effects improved predictions \citep{Riofrio2019}. 
\cite{Vospernik2021} found that individual tree basal area increment %\citep{Vospernik2021}
was significantly modified in mixtures after accounting for other factors. 
They observed species-mixing effects on \emph{Larix decidua} in mixtures 
with \emph{Picea abies}, \emph{Pinus cembra}, \emph{Fagus sylvatica}, 
and \emph{Betulus spp.}, where it mutually benefited in mixtures
with \emph{Picea abies} \citep{Vospernik2021}. These findings are similar to 
those of Z\"{o}hrer (\citeyear{Zohrer1969}) where incremental growth was increased %Z&ouml;hrer \citep{Zohrer1969}
in mixtures between shade-tolerant \emph{Picea abies} and shade-intolerant
\emph{Larix decidua}.

Since individual tree growth models can be improved 
by accounting for species-mixing in addition to other variables, it may 
be pertinent to characterizing individual tree growth in mixed-conifer forests 
in the western US. Additionally, since there is evidence of this in 
photogenically similar European larch, then species-mixing effects may be relevant 
for characterizing western larch growth because it is a fast growing and 
shade-intolerant species that mixes with various other conifers across the inland northwest. 
The foci of the present study then are to describe 
(i) how community composition impacts the growth of western larch 
given other variables known to impact its growth and 
(ii) how to characterize species-mixing effects 
within the context of distance-independent, individual-tree 
growth modeling in the inland northwest. 

% Given that density is modified by species-mixing, that larch growth 
% is sensitive to density, and larch's intolerance to shade, 

The objectives of the present study then were: 
(i) to identify a 
distance-independent individual tree basal area increment (BAI) model to 
statistically control for variations in tree size, stand density, 
and site productivity in long-term forest inventory data, 
% (ii) identify different types of mixtures that western 
% larch grows in where its growth may be impacted, 
(ii) to determine if western larch BAI varies by mixture type after 
accounting for other factors, and
(iii) to compare generalizable species-mixing measures and identify 
which of these improves growth estimation. 
I expected that larch growth would be positively impacted 
when in mixtures with more shade-tolerant species, and 
negatively impacted when mixed with shade-intolerant species as well as in 
pure western larch stands. 
Additionally, I expected that species-mixing effects would best be captured by 
a measure that accounts for different species' shade tolerance, as this would 
address the primary mechanisms behind variations in growth, as opposed to 
measures of stand species purity crown density. 

% questions
% \bf{How does community composition (species-mixing) influence the growth of western larch?} 
% \bf{Comparing species-informed measures, how can the effects of species-mixing be best accounted for within an individual-tree growth model?}

% The Forest Vegetation Simulator (FVS;\cite{Dixon2020}), 
% which is used across the region for management planning and research, 
% is driven primarily by an individual tree growth model \citep(Stage1973,Wykoff1990)
 
% Since western larch forests range in species-composition 
% and occur across biophysical conditions, western larch may 
% be subject to the effects of modified competitive or complementary 
% relationships within communities that it grows. 

% due to complementary effects, quantifying community competition for 
% light can sufficiently capture the effects of biodiversity on productivity \citep{Morin2011}.
%  Lebourgeois \citep{Lebourgeois2013}
% found that species mixture modified the growth of \emph{Abies abla} through
% facilitative interactions under drought conditions. In northwestern Montana,
% facilitative and competitive interactions were found to modify growth rates 
% of \emph{Abies lasiocarpa} and \emph{Pinus albicaulis}, depending on environmental
% stressors \citep{Callaway1997}. 

% Additionally, variation of shade tolerance within a community can lead to 
% enhancements on overall community productivity \citep{Zhang2012}. 

% Thus, a shade tolerance informed metric may capture complementarity 
% effects on tree growth and lead to improved estimates thereof. 

% In the case where one focal species is dissimilar 
% from others within its community, competitive 
% dynamics may be effectively captured through a coarse 
% measure of the proportion of the focal species to all others, or stand purity.
% and capturing mixing effects with a stand purity 
% metric can provide insights into this relationship.

% When quantified, shade tolerance may aid in characterizing 
% competition and/or complementarity among species in a mixed-species forest.

% --- Niche complementarity 
% - steed and goeking 2020 talks about niche differentiation in terms of larch and climate
% - phylogenetically dissimilarity may affect tree growth through a reduction in suspeptibility to species specific pests, pathogens, predators. (quote from Searle \& Chen 2020)
% - Original papers (janzen 1970 and Connell 1978)
% - Theory etended to mature plants through resource concentration hypothesis (Parker et al. 2015, groosman et al. 2018)
% - Mature plant communities with more phylogenetically close host species are more susceptable to specialized pest and pathogen outbreak. Thus a tree with phylogenetically distant neighbors may experience less competition and may experience higher growth rates. (Searle \& Chen 2020)

% The mixing of phylogenetically dissimilar species

% Niche complementarity (CITE), or more specifically, the resource concentration 
% hypothesis (CITE parker, grossman), describes conditions where phylogenically
% dissimilar species growing together may experience higher rates 
% of growth from the mixing of traits in a mixed-species forest (CITE. .. .). 
% Previous studies have identified complementary effects among trees with
% differing shade tolerances. \citep{Searle2020} SEARLE 2020 found that such complementary 
% effects on individual tree growth increased with competition intensity. 

% point: It's important to have models that account for processes that drive tree growth which are easy to measure or acquire.
% Individual tree growth models are commonly used to estimate future stand characteristics 
% and conditions to aid in forest management and research. Such models rely on previously identified 
% empirical relationships to estimate growth from tree size, inter-tree competitive dynamics, site conditions, 
% and other readily measured or acquired attributes. Since variables in empirical tree growth models 
% are meant to represent ecological processes from relatively simple metrics and are sometimes meant to 
% be generalized across large geographical areas or conditions, they may fail to accurately estimate 
% tree growth under some conditions. ***X provides evidence here. Y says this.***

% point: empirical growth models are used to estimate future conditions 
% from variables that represent ecological dynamics

% - get after niche complementarity, shade tolerance, weighted density metrics, etc. 
% - add some kind of discussion regarding crown competition factor (ccf paper where he says something about mixed species forests)

% Capturing the effects of species-mixing can be accomplished by various 
% methods, one simply being the incorporation of species-identity into density metrics (CITE?). 
% Several such methods rely on a comparison between mixed-species stands 
% and mono-specific stands (Forrester et al? pretzsch?).
% In the north american west, empirical models such as FVS (CITE) 
% are used to estimate tree growth across a variety of conditions 
% where the model relies on averages from extensive growth samples within 
% a region to provide estimates. Under this paradigm, and where conditions vary so broadly, 
% how can the effects of species-mixing and niche complementarity best be captured in an empirical modeling framework?
% FVS uses crown competition factor (CCF; \citep{Krajicek1961}) which is a species-weighted percent of basal area
% occupied by the theoretical maximum crown area for trees of a given diameter, if they were open grown. 
% This measure is effectively a density that is informed by species crown allometry 
% from which one could infer the relative light use of trees at a site given the stand density, 
% but not the interspecific environmental effects of light-use-diversity on tree growth. 
% 
% Other measures 
% 
% CCF measures density based on a verified relationship between crown width and dbh \citep{Krajicek1961}, 
% and generally follows the following form: \begin{equation}
% \label{eq:}
% CCF = \sum\limits_{i}^{n} \beta_0 + \beta_1 D + \beta_2 D^2
% \end{equation}, where $\beta_i$ parameters represent species-specific coefficents. 
% Values are summed across observations and the measure ultimately provides a percentage of 
% stand basal area occupied by tree crowns. 
% 
% but for the purpose of including species-mixing in empirical models, 

% Evidence of how species-mixing impacts tree growth can shed light on
% relationships that are not currently well-understood if new research is
% expanded to more forest-types. Various studies in Europe have revealed that
% facilitation or competitive reduction in mixed-species stands can lead to
% enhanced productivity when compared to monocultures \citep{Pretzsch2009}.
% This effect is sometimes termed overyielding, with reference to the potential
% for higher than anticipated biomass or volume \citep{Pretzsch2009,Loreau2010}.

% Further evidence suggests that species-mixing can interact with stand density 
% in the long term, and that the interplay between the two likely depends
% on the characteristics of species-mixtures and stand types \citep{Brunner2020, Condes2013}.
% 
% Interactions in communities of variable- and similar- trait
% species within North American \emph{Larix} forests are not well-understood, and 
% thus motivate further investigation to characterize how stand species composition 
% modifies western larch growth dynamics. 

% Reich (\citeyear{Reich1998}) found that \emph{L. laricina} had high levels of growth in both high and low light conditions, compared to other coniferous trees.

% \subsection{Research questions}
% 
% \bf{How does community composition (species-mixing) influence the growth of western larch?} 
% 
% \bf{Comparing species-informed measures, how can the effects of species-mixing be best accounted for within an individual-tree growth model?}

%%% old research questions stuff %%%

% Since there is evidence indicating that species-mixing can impact long-term
% development in temperate forests \citep{Pretzsch2009, Pretzsch2010, Zhang2012},
% I posited that the different physiological drivers motivating growth that
% relate to light interception (i.e. shade tolerance) within an interspecific
% environment can produce appreciable differences in the growth of a species,
% after accounting for tree size, inter-tree competition, site productivity, and stand density. 
% This may happen through the enhancement of competition between species of
% similar shade-tolerance, or competitive reduction between
% species of dissimilar shade-tolerance through niche complementarity
% \citep{Callaway1997, Condes2013,Pretzsch2015, Riofrio2017}. Moreover, 
% complementary or competitive effects of species traits in
% a stand can modify how a species interacts with stand density, 
% and in turn, modify a tree's allometry \citep{Weiskittel2009a}. For example,
% it is known that the density of western larch stands impacts how western 
% larch grows \citep{Schaedel2017a}. However, complementary or competitive interactions
% among species have not been explicitly acknowledged within the context of western larch growth, 
% and may modify density effects on western larch growth, (e.g., a western larch in a high
% density stand may grow more in a mixture with shade-tolerant species than a
% western larch at the same density in a mixture with shade-intolerant species). 

% I predicted that the growth of western larch can respond to species-mixing
% across a gradient of species and may depend on how its surrounding community 
% interacts with light. Specifically, I presume \emph{L. occidentalis} growth will
% be modified positively in mixtures with shade-tolerant species such as 
% \emph{Picea engallmanii}, \emph{Abies grandis}, and \emph{Abies lasiocarpa}. Conversely, 
% I expect that \emph{L. occidentalis} growth will be negatively impacted in mixtures 
% with shade-intolerant \emph{Pinus contorta} and \emph{Pinus ponderosa}. I expect that the 
% roles of mid-tolerant species such as \emph{Pseudotsuga menziesii} in modifying 
% \emph{L. occidentalis} growth will vary, from positive to negative. 

% Therefore, my related research objectives were:
%(i) to identify variables that capture the effect of species-mixing on growth 
% (i) determine if western larch growth varies depending on which type of mixture it is in 
% after accounting for other factors that influence tree growth
% and quantify their respective influences on growth
% quantify the degree to which species-mixing impacts western larch growth, 
% (ii) to determine whether a species shade tolerance informed metric improves growth estimates of western larch trees
% effectively captures the effects of niche complementarity on western larch
% identify whether shade-tolerance, as a measure of interspecificity, captures the effects of mixing,
% (ii) identify, quantify, and compare different species-composition informed metrics within an empirical modelling framework
% the effectiveness of different measures of species-mixing

\chapter{Methods}
\section{Tree growth data}

% The Forest Vegetation Simulator (FVS) is a distance-independent, individual 
% tree forest growth model that is widely used in the western United States 
% to predict tree and stand growth as well as to evaluate management decisions 
% \citep{Dixon2020}. 
To establish a monitoring protocol for the FVS model,
the USDA Forest Service Northern Rocky Mountain region developed 
long-term permanent growth plot clusters (PGPs) in managed stands 
across the inland northwest (NW Montana and northern Idaho),
referred herein to as the PGP program. The PGP program was primarily set up 
to monitor long-term treatment response to precommercial thinning relative 
to projections provided by FVS. The initial goal of the PGP program was to 
remeasure the selected stands at regular increments of 
5-10 years in order to provide a robust growth increment data set. 
Various stand measurements were initialized and then remeasured between 
1980 and 2002. The program was then paused, and was only recently revisited 
in 2018 and 2021, allowing for analysis of long-term effects, albeit with 
a wide gap between recent measurements. 

Each PGP stand consists of 4 plot-clusters: 1 untreated control plot cluster 
and 3 treatment plot clusters. The latter were treated with commercial 
or precommercial thinning, depending on stand age and maturity. 
Stand prescriptions determined target residual densities by species 
in the treatment areas, providing for side-by-side comparison between
control and treatments under similar stand and site conditions. The location 
of control and treatment plots were determined by random selection of 
coordinates on a grid laid over a map of the stand. To ensure that the control 
plots were not affected by nearby thinning treatments, an unthinned buffer was
placed around control clusters. Every cluster is comprised of three 202 $\mathrm{m^2}$ 
large-tree plots, with each plot containing three 13.5 $\mathrm{m^2}$ 
small tree sub-plots. Data for trees in large-tree plots were taken 
based on whether a tree was above a specified diameter threshold. 
The diameter thresholds varied across and within stands 
(across control and treatment plots), as well as within clusters over
time. Yet the large trees were tagged and distance and azimuth to plot center
were taken. Heights were taken on only a subset of large trees due to the
operational challenges and added time of measuring tree height. Within small 
tree plots, counts by height and species were recorded for trees greater 
than or equal to 15 cm in height from 
the ground, and up to the specified diameter threshold. 

During the summer of 2018, a re-measurement campaign targeted 
stands with at least 3 previously recorded measurements on
the Lolo National Forest. During the summer of 2021, PGP stands on the
Lolo and Kootenai National Forests that were previously measured at least
3 times and that were composed of >50\% overstory western larch (determined
by most recent measurement) were targeted for re-measurement. Stands across 
the remeasured PGPs were spread between $46^{\circ}$N and $49^{\circ}$N, and 
between 800 and 1700 $m$ above sea level. Stands were primarily on north-facing aspects. 
% Soil conditions were variable from site-to-site, but most were a silty-loam texture.
Overall, species composition varied between almost pure western larch to mixed conifer
forests composed of mixtures of: western larch, Douglas-fir, Engelmann spruce, grand fir, 
subalpine fir, western hemlock, mountain hemlock, western redcedar,
cottonwood \emph{Populus balsamifera}, and quaking aspen \emph{Populus tremuloides}. 

\begin{table}[H]
\caption[Summary data counts]{Counts of data for each stand. The first 2 digits of each stand number correspond to which national forest they are in: 14 for the Kootenai NF, and 16 for the lolo national forest. }
\label{tab:sumtab}
\centering
\begin{tabular}{lrrrr}
\toprule
Stand & Plots & Unique trees & Observations & Measurements\\
\midrule
\cellcolor{gray!6}{1401} & \cellcolor{gray!6}{10} & \cellcolor{gray!6}{53} & \cellcolor{gray!6}{150} & \cellcolor{gray!6}{4}\\
1402 & 10 & 188 & 631 & 5\\
\cellcolor{gray!6}{1403} & \cellcolor{gray!6}{10} & \cellcolor{gray!6}{113} & \cellcolor{gray!6}{313} & \cellcolor{gray!6}{5}\\
1404 & 10 & 146 & 465 & 5\\
\cellcolor{gray!6}{1405} & \cellcolor{gray!6}{10} & \cellcolor{gray!6}{188} & \cellcolor{gray!6}{676} & \cellcolor{gray!6}{5}\\
\addlinespace
1406 & 10 & 99 & 304 & 5\\
\cellcolor{gray!6}{1407} & \cellcolor{gray!6}{19} & \cellcolor{gray!6}{74} & \cellcolor{gray!6}{108} & \cellcolor{gray!6}{4}\\
1408 & 10 & 77 & 212 & 4\\
\cellcolor{gray!6}{1609} & \cellcolor{gray!6}{9} & \cellcolor{gray!6}{37} & \cellcolor{gray!6}{139} & \cellcolor{gray!6}{5}\\
1610 & 10 & 129 & 416 & 5\\
\addlinespace
\cellcolor{gray!6}{1611} & \cellcolor{gray!6}{10} & \cellcolor{gray!6}{77} & \cellcolor{gray!6}{222} & \cellcolor{gray!6}{5}\\
1612 & 10 & 211 & 548 & 4\\
\cellcolor{gray!6}{1614} & \cellcolor{gray!6}{9} & \cellcolor{gray!6}{49} & \cellcolor{gray!6}{181} & \cellcolor{gray!6}{5}\\
1615 & 10 & 133 & 379 & 4\\
\cellcolor{gray!6}{1616} & \cellcolor{gray!6}{10} & \cellcolor{gray!6}{106} & \cellcolor{gray!6}{291} & \cellcolor{gray!6}{4}\\
\addlinespace
1617 & 10 & 131 & 355 & 4\\
\cellcolor{gray!6}{1618} & \cellcolor{gray!6}{9} & \cellcolor{gray!6}{30} & \cellcolor{gray!6}{66} & \cellcolor{gray!6}{4}\\
1619 & 10 & 134 & 338 & 4\\
\midrule
\cellcolor{gray!6}{Totals} & \cellcolor{gray!6}{186} & \cellcolor{gray!6}{1975} & \cellcolor{gray!6}{5794} & \cellcolor{gray!6}{ }\\
\bottomrule
\end{tabular}
\end{table}

% In all, the portion of the PGP inventory data set used here contained -A CLUSTERS-, -X PLOTS-,
% -Y TREES-. Tree size/height varied by -----INFO------, 

\section{GAM overview}

Using these data, a generalized additive mixed model (GAMM) was developed to estimate 
annual growth of western larch, quantified by basal area increment (BAI; Equation ~\ref{eq:bai}): 

\begin{equation}
\label{eq:bai}
BAI = \frac{BA_{m+1}-BA_{m}}{t_{m+1}-t_m}
\end{equation}

, where $BA_m$ refers to tree basal area at measurement $m$ and $t_m$ to the 
unique year of measurement and $m+1$ is a subsequent measurement year.
The choice to annualize BAI was made because re-measurement intervals were inconsistent 
across the data set and annulization allows for flexibility and a finer-scale measure of 
stand dynamics over time \citep{weiskittel2011forest}.

Generalized additive models \citep[GAMs][]{Hastie1990} allow for flexibility in model fitting and an allowance for non-linear 
relationships across variables \citep{Zhao2005,wood2006generalized}. Contrary to traditional 
parametric modeling approaches, GAMs let the data determine the 
shape of the functional relationships by fitting predictor effects with a sum of 
smooth functions of covariates instead of specified parameters \citep{wood2006generalized,Robinson2011}. 
%which also proved beneficial in this case due to the inconsistency of measurement intervals. 
The choice to use a mixed-model approach was made owing to the  
dependence structure that arises from repeat measurements 
on the same trees over time, and thus random effects were specified at the 
individual tree-level. %was it? should it?

%---include something visual about dependence structure?---

GAMMs were fit using the mgcv package \citep{Wood2011} in R \citep{RCoreTeam2021}. 
The mgcv package allows for the specification of smooth functions (or smoothers). 
Smoothers are a sum of fitted estimated basis 
functions that characterize the conditional relationship between the predictor 
and independent variable. They are penalized by a smoothing parameter, which 
constrains a smoother as its complexity grows higher \citep{Pedersen2019}. 
The mgcv package allows smoothing parameters to be estimated via likelihood, information 
theoretical methods, or cross-validation-based methods \citep{wood2006generalized}. 
The maximum likelihood method was used in this study because it allows for 
likelihood-based comparison across models with different fixed terms and smoothing parameters. 
Random effects may also be coded as penalized smooths in this format \citep{Pedersen2019}. 
% , however, 
% when fitting large numbers of intercepts (as done in this study) 
% computation can extremely slow . %%%more here?? do I talk about using both methods since the way random effects are handled with the gamm case is kinda weird? (see pedersen 2019 page 34)
With mgcv, the thin-plate regression spline (TPRS) type
is the default owing to its simple and effective behavior \citep{Wood2003},
and was used for all terms. 
% GAMs in mgcv also allow for 


The model formulation described here was developed with a training 
data set which allowed for varying conditions across all variables. 
Data for two measurement plots out of each stand were withheld for 
the purpose of model validation and assessment.
The model formulation resulting from the selection process described below
was used to evaluate effects of predictors 
on BAI across the entire data set. The formula was also used to assess smooths
across different species mixtures, where the model was re-fit with a subset 
of the training data set where species mixture type was categorized.  
In this case, models were fit using restricted maximum likelihood criteria (REML) 
approach (CITE: patterson and thompson 1971) because it reduces computation time and 
models were not compared in the across-mixture analyses. 
%also reduces bias in variance component estimation

\section{Base model selection}

Predictor selection followed the logic of \cite{Wykoff1990}, 
(\cite{Monserud1996}), and \cite{Vospernik2021} where predictors were 
grouped together based on the following categories: 
(i) size, (ii) density and competition, and (iii) site predictors. 
Size variables considered were tree diameter at breast 
height ($DBH$) and tree basal area ($BA$). 
Density and competition variables considered were: plot basal area ($BAH$), 
plot basal area larger than the subject tree (BAL; expressed as a ratio of BAH), 
plot quadratic mean diameter ($QMD$), ratio of tree DBH to QMD ($D_q$), 
and trees per hectare ($TPH$). Site variables initially considered were: 
slope, aspect, elevation, mean site index, and heatload \citep{Theobald2015}. 
These initial explanatory variables were identified based on availability 
in the PGP data set, whether they could be calculated from the 
available data, and if they have been used in predicting 
BAI in previous empirical modeling efforts. 

% crown competition factor (CCF;\cite{Krajicek1961}), remove??
%-TABLE HERE- table of all variables considered prior to modeling including definitions and how they were calculated?--

A pair-wise collinearity assessment was 
then performed within each group of variables to avoid including 
highly correlated variables together in the model. 
Any predictors with a pair-wise correlation of 
0.7 or higher were not considered in a model together. Although somewhat arbitrary, 
this threshold was selected because a 0.7 correlation indicates that  
variables are closely related. Additionally, variables 
known to represent the same processes, even if not highly linearly correlated 
(such as heatload and aspect, for instance), were not considered together to 
avoid redundancies and reduce model complexity.

GAMs were used to select predictors and visually examine 
predictor partial effects on BAI. % as well as examine residual structure. 
Models were fit in iterations of predictor grouping. 
% including non-correlated variables together 
% respective of grouping while maximizing model accuracy and avoiding overlap. 
The order of this group-wise selection process was based on 
previously identified contributions of these predictor groups 
in estimating BAI \citep{Wykoff1990,Monserud1996}. Highly 
correlated same-group variables were compared in alternative models.
For example, alternative models were fit for both tree DBH 
and BA, selecting whichever best predicted BAI. 
Then, with the selected size variable present in the model, 
competition variables were evaluated and selected 
based on maximizing model accuracy and reducing overlap between variables. 
The same process was used for site variables thereafter, 
finalizing the base model formulation: 

\begin{equation}
\label{eq:baiform}
ln[E(BAI)] = \beta_0 + \sum_j f_{1j}(x_{1j}) + \sum_j f_{2j}(x_{2j}) + \sum_j f_{3j}(x_{3j})\\
\end{equation}

where $ln$ represents the logarithmic link function, $E(BAI)$ represents the expected 
value of BAI, $\beta_0$ represents an intercept, $\sum_j$ represents summation 
of smooth functions for a given group, $x_1$, $x_2$, $x_3$ represent 
size, competition, and site predictor variables, respectively, and $f_1$, $f_2$, $f_3$ 
are smooth functions for each, respectively. 

Root mean squared error (RMSE; Eq. ~\ref{eq:rmse}) was calculated to assess 
model accuracy: 

\begin{equation}
\label{eq:rmse}
RMSE = \sqrt{\frac{\sum_k (\widehat{BAI_k} - BAI_k)^2}{n_{df}}}
\end{equation}

where $\widehat{BAI_k}$ is the model prediction, 
$BAI_k$ is the observed value, and $n_{df}$ is the model residual 
degrees of freedom (number of increments less model effective degrees of freedom).

When comparing models, a model formulation with the lowest RMSE (highest predictive accuracy) 
was selected over alternatives. RMSE was calculated using residual degrees of 
freedom to provide an unbiased estimate. The proportion of null deviance 
explained by the model (or deviance explained) \citep{wood2006generalized} was also 
considered for ensuring acceptable model fit, %Do i even say this?
but was not used as a primary selection criterion. 


\section{Assessing species-mixing impacts on growth}

% - Once a model exists, we can use it on subsets of the data set to 
% determine types of species-mixing effects and their effects on BAI

In order to test for differences in larch growth between different 
species mixtures, distinct mixtures were determined based on species 
proportional share of plot basal area.%BAH. 
To qualify as a specific mixture-type, a minimum of 20\% of the total plot 
basal area had to be in western larch trees and a minimum of 20\% 
in either Douglas-fir or lodgepole pine. This was to ensure that there was a minimal 
representation by both species. To ensure that neither species was  
over-represented in a plot, neither larch nor the other species 
could exceed 65\% of plot BA. Also, both species combined basal area had 
to occupy at least 70\% of total plot BA. 
% This ensured that a range of each mixture-type was captured while prohibiting over-representation of either species within the mixture. 
A pure larch condition was defined as at least 70\% of plot BA in western larch. 

The mgcv package allows for smooth functions that vary across different 
groups \citep{Pedersen2019}. A variation of this method was employed to 
contrast western larch growth across each identified type of mixture against 
the pure larch stand condition. Thus, the identified 
base model formula was fit but where each mixture was allowed an offset for the intercept
and for each smooth term, resulting in a model containing a reference smooth 
for each predictor, and a \emph{difference smooth} for species-mixture 
\citep{wood2006generalized}: 

\begin{equation}
\label{eq:mixes}
\begin{aligned}
ln[E(BAI)] =& \beta_0 + \sum_j f_{j}(x_{j}) + \sum_s \delta_s(\alpha_s + \sum_j g_{j,s}x_j) \\
\delta_s =& 
\begin{cases}
0 & \text{if pure larch}\\
1 & \text{if species mix } s
\end{cases}
\end{aligned}
\end{equation}
% \beta_{1j} + f_{j}(x_{n})

where $s$ is a species-mix indicator, $\alpha_s$ is an offset on the intercept 
$\beta_0$ and $g_{j,s}$ is an offset on a smooth for species $s$ and predictor $j$.
These difference smooths were evaluated 
against the pure larch reference smooth using a hypothesis test 
to identify evidence that a difference is non-zero. 
% where $\beta_0$ is the model intercept, representing the mean value
% of $BAI$ for pure larch conditions, 
% $\beta_{1j}$ represents the difference between $\beta_0$ and the intercept 
% for mixture $j$, $f_{j}$ is a smooth function for model predictor 
% $x_n$ in a mixture. 

%%look at "using generalized additive models to analyze single case designs" paper 2014. maybe has something citable. 
%% also look at the gavin simpson paper about lakes
%% zuur might talk about it to

% After identifying these conditions in the PGP data 
% 
% Since the data was subset in favor 
% of specific scenarios, it was important to consider the size of subsets 
% before fitting models with them to ensure sample size was large enough. 
% Ultimately, mixtures chosen were composed of 
% larch with lodgepole pine, douglas-fir, and Engallmann spruce, spanning 
% from shade intolerant to shade-tolerant. 

% To identify differences between 
% 
% 
% Using each resulting model, 
% growth was predicted from a data set holding every variable except DBH constant 
% to isolate the effects of tree size on growth across mixtures. Resulting curves respective of 
% species-mix type were then plotted and visually examined. 
% 
% Additionally, 
% the DBH-BAI relationship was evaluated at different 
% levels of each other variable to examine how the size-growth relationship 
% is modified across densities, competitive symmetries, crown ratios, and aspects.

% It was of interest to examine these relationships of larch growth in mixtures 
% with species that span the shade-tolerance spectrum, including stands  
% that are predominantly composed of larch as well as stands where larch was mixed 
% with a different species. 


% Figure (XXX) shows the distribution 
% of each mixture type across to other species identified. 

% A hypothesis test was conducted to identify differences between predicted values 
% of BAI across the range of DBH. 
% There is a level of uncertainty associated 
% with smoothing parameter estimation in the mgcv package 
% which is not accounted for . 95\% confidence intervals for each predicted 
% value were calculated based on a simulation of the posterior distribution at 
% each value of DBH. This ensures that the uncertainty 

%may be able to get away with adding unconditional = T to the predict function to generate intervals that account for the fact that smoothing parameters were estiamted. 
%additionally, I can add sewithmean=T to the plot command, save the plot object, and then inspect the object and see that its a list with one comoponentper smooth. 
%% see this post: https://stats.stackexchange.com/questions/33327/confidence-interval-for-gam-model/33328#33328
%% simultaneous confidence intervals 

%%see also: https://stats.stackexchange.com/questions/503819/confidence-intervals-for-derivatives-from-gam-predictions
%% https://stats.stackexchange.com/questions/190348/can-i-use-bootstrapping-to-estimate-the-uncertainty-in-a-maximum-value-of-a-gam/191489#191489
%%  https://stats.stackexchange.com/questions/464961/issues-with-posterior-simulation-from-gam - simon wood on SE

% make figure or table that describes the range of conditions for each mixture type
%% including minimum and maximum percent of each species in a mixture, while including their combined basal area. 
%%% perhaps a stacked barchart where each bar totaled to the percent mixture, 
%%% and with one color representing larch ba, and other color for each species representing BA.  
%%%% Or boxplots of each mixture type
%%%% jittered points for each mixture, where x is mixture type and y is larch:spp mixture ratio
% visualize the BA thresholds for selecting different mixture-types?

% occupied by larch 
% had to be at least  and likewise for a given species.
% Identifying different mixtures 
% 
% Different categories of species-mixtures were identified by evaluating 
% the amount of plot basal area 
% 
% impacted at different levels other variables, 
% the same 
% process was repeated for 
% For example, predictions were made 
% across a range of tree diameters for each of the mixture models
% 
% Furthermore, additional variables 
% were categorized

% 
% -how to do this: 
% -first see the comments on this post from Gavin S. :https://stats.stackexchange.com/questions/470980/continuously-test-where-two-generalized-additive-models-differ
% - I want to test the difference of expected values across a given range of x (whichever covariate).
% -- https://fromthebottomoftheheap.net/2016/12/15/simultaneous-interval-revisited/
% -- extract baysian covariacne matrix with vcov()
% -- define new data with dubbed values of whichever covariate
% -- predict from that
% -- pull the se.fit object

%can i use by variable to test for differences in spp mix?
% To determine 
% if growth was characterized differently across different mixtures, 
% 
% - Explain and rationalize how subsets were identified
% - Fit model to data subsets
% - Use resulting models to predict on a static data set where only one (or two)
% variables are changing
% - Explain basis of comparison (how do i compare these things)
% --do i compare visually? Is there a hypothesis testing?
% --- do i compare pointwise, based on the confidence interval?


\section{Comparing species-mixing measures}

Three different species-informed measures were identified for comparison: 
crown competition factor, proportion of basal area occupied by larch, and 
proportion of basal area weighted by species-shade tolerance values. 

Crown competition factor (CCF) is a species-informed density measure that 
is based on tree crown allometry \citep{Krajicek1961}. In this measure, 
each species has an identified maximum crown width in open-grown conditions for 
a given DBH. Crown width is associated with a tree's maximum crown area 
(MCA), and can be estimated as a proportion of stand area using species-specific 
coefficients in a polynomial equation.  
These maximum crown area values are summed within a stand to express 
overall competition for crown space, or CCF:

\begin{equation}
\label{eq:ccf}
CCF = \sum_k w_k h(DBH_k, s_k)
\end{equation}

where $w_k$ is the area expansion factor (TPH) for tree $k$, and $h()$ is a 
function of the DBH of tree $k$, given its species $s$. This study used the 
species-specific coefficient values identified by the FVS-IE variant \citep{Keyser2008}.
This data is normalized such that a CCF value of 100 means that all trees 
in a stand have theoretically achieved their maximum crown area and 
canopy closure is achieved, i.e., any value in excess of 100 
theoretically describes the threshold of competition for crown space. 


% A stand where trees are similarly-sized and of species A would theoretically 
% achieve crown closure sooner than a stand with similarly sized mixture of 
% species A and B, given that species B has lower MCA values. 
% 
% For instance, trees of a given diameter in a stand, whose species-specific MCA values 
% are high relative to others, 


% 
% Theoretically, trees of a given diameter with high crown widths mixed together 
% would drive the CCF value well over 100\%, representing high competition.  
% In contrary, a stratification of trees of different sizes composed of large and 
% small crown widths could increase utilization of crown space, 
% reducing competition. CCF weighs species identity by species-specific 
% diameter-crown allometry -based parameters. This study used the species 
% parameters used by the FVS Inland Empire regional variant (Table ~\ref{tb:ccfvals}; \cite{Keyser2008}).
% The CCF equation is shown in equation (~\ref{eq:ccf}):

% That is, 100\% stand CCF 
% means that in open-grown conditions that there is absolutely  and all tree crowns in a stand would be close 
% enough to barely touch. 

% 
% \begin{equation}
% \label{eq:ccf}
% \begin{aligned}
% &CCF_{jt}& = &\sum CCF_{tree} \\
% &CCF_{it}& = &r_1 + r_2 DBH + r_3 \ DBH^2 + r_4 + DBH^{r_5} 
% \end{aligned}
% \begin{cases} r_1, r_2, r_3 = 0\ \text{if}\ DBH > 10" \\ r_4, r_5 = 0\ 
% \text{if}\ 0.1" < DBH < 10" \end{cases}
% \end{equation}
% 
% where $CCF_{jt}$ is plot $j$ crown competition factor calculated at 
% a given measurement $t$ which is the sum of crown competition factor values at 
% $CCF{it}$ across trees $i$ within the plot $j$. $r_{n}$ coefficients represent parameters 
% provided for each species.

% \begin{table}[!h]
% \centering
% \caption[CCF parameters]{Crown competition (CCF) parameters used. These values were taken from the documentation for the inland empire variant of FVS \citep{Keyser2008}}
% \label{tb:ccfvals}
% \begin{tabular}{llrrrrr}
% \toprule
% Species abbr. & r1 & r2 & r3 & r4 & r5\\
% \midrule
% \cellcolor{gray!6}{THPL} & \cellcolor{gray!6}{0.03000} & \cellcolor{gray!6}{0.02380} & \cellcolor{gray!6}{0.00490} & \cellcolor{gray!6}{0.008915} & \cellcolor{gray!6}{1.7800}\\
% TSHE & 0.03000 & 0.02150 & 0.00363 & 0.011109 & 1.7250\\
% \cellcolor{gray!6}{PIEN} & \cellcolor{gray!6}{0.03000} & \cellcolor{gray!6}{0.01730} & \cellcolor{gray!6}{0.00259} & \cellcolor{gray!6}{0.007875} & \cellcolor{gray!6}{1.7360}\\
% ABLA & 0.03000 & 0.02160 & 0.00405 & 0.011402 & 1.7560\\
% \cellcolor{gray!6}{ABGR} & \cellcolor{gray!6}{0.04000} & \cellcolor{gray!6}{0.02700} & \cellcolor{gray!6}{0.00405} & \cellcolor{gray!6}{0.015248} & \cellcolor{gray!6}{1.7333}\\
% \addlinespace
% PIMO3 & 0.03000 & 0.01670 & 0.00230 & 0.009884 & 1.6667\\
% \cellcolor{gray!6}{PSME} & \cellcolor{gray!6}{0.11000} & \cellcolor{gray!6}{0.03330} & \cellcolor{gray!6}{0.00259} & \cellcolor{gray!6}{0.017299} & \cellcolor{gray!6}{1.5571}\\
% PIPO & 0.03000 & 0.01800 & 0.00281 & 0.007813 & 1.7680\\
% \cellcolor{gray!6}{LAOC} & \cellcolor{gray!6}{0.02000} & \cellcolor{gray!6}{0.01480} & \cellcolor{gray!6}{0.00338} & \cellcolor{gray!6}{0.007244} & \cellcolor{gray!6}{1.8182}\\
% PICO & 0.01925 & 0.01676 & 0.00365 & 0.009187 & 1.7600\\
% \addlinespace
% \cellcolor{gray!6}{POTR5} & \cellcolor{gray!6}{0.03000} & \cellcolor{gray!6}{0.02380} & \cellcolor{gray!6}{0.00490} & \cellcolor{gray!6}{0.008915} & \cellcolor{gray!6}{1.7800}\\
% POPUL & 0.03000 & 0.02150 & 0.00363 & 0.011109 & 1.7250\\
% \cellcolor{gray!6}{BEPA} & \cellcolor{gray!6}{0.03000} & \cellcolor{gray!6}{0.02380} & \cellcolor{gray!6}{0.00490} & \cellcolor{gray!6}{0.008915} & \cellcolor{gray!6}{1.7800}\\
% TSME & 0.03000 & 0.02150 & 0.00363 & 0.011109 & 1.7250\\
% \cellcolor{gray!6}{JUSC2} & \cellcolor{gray!6}{0.01925} & \cellcolor{gray!6}{0.01676} & \cellcolor{gray!6}{0.00365} & \cellcolor{gray!6}{0.009187} & \cellcolor{gray!6}{1.7600}\\
% \addlinespace
% PIAL & 0.02000 & 0.01480 & 0.00338 & 0.007244 & 1.8182\\
% \cellcolor{gray!6}{TABR2} & \cellcolor{gray!6}{0.01925} & \cellcolor{gray!6}{0.01676} & \cellcolor{gray!6}{0.00365} & \cellcolor{gray!6}{0.009187} & \cellcolor{gray!6}{1.7600}\\
% 2TE & 0.03000 & 0.02150 & 0.00363 & 0.011109 & 1.7250\\
% \bottomrule
% \end{tabular}
% \end{table}

As an alternative to CCF, the proportion of basal area occupied by larch 
is a measure of species purity within a stand. It is simply calculated as a 
ratio of plot basal area occupied by western larch ($BA_{s_km}$) to total plot 
basal area $BAH_m$: 

\begin{equation}
\label{eq:purity}
L = \frac{\sum\limits_{k} BA_{s_k}}{\sum\limits_{k} BA_{k}}
\end{equation}

where $L$ denotes the plot larch purity value at measurement $m$, for species $s$ 
and $BA_{s_k}$ is the basal area of tree $k$, given its species identity, which 
is western larch in this case. 

%  \frac{\sum_{i}{BA_{ijt}\ I_{ijt}}}{\sum_{i}{BA_{ijt}}}\ \ \ I_{ijt} = \begin{cases} 1,\ \text{if}\ i\ \text{is western larch}\\0,\ \text{otherwise}\end{cases}
% \end{equation}

% \begin{equation}
% \label{eq:purity}
% L_{jt} = \frac{\sum_{i}{BA_{ijt}\ I_{ijt}}}{\sum_{i}{BA_{ijt}}}\ \ \ I_{ijt} = \begin{cases} 1,\ \text{if}\ i\ \text{is western larch}\\0,\ \text{otherwise}\end{cases}
% \end{equation}
% 
% where $L_{jt}$ denotes the ratio, $BA_{ijt}$ is the of basal 
% area of a tree $i$, $I_{ijt}$ is a binary operator which indicates whether a 
% tree $i$ is western larch ($I_{ijt} = 1$), or otherwise ($I_{ijt} = 0$)

The third species-informed measure makes use of a shade-tolerance index 
\citep{Lienard2015} where different species are assigned with values 
ranging between 0 and 1, 0 being very shade-tolerant, and 1 being very 
shade-intolerant. Since this study focused on shade-intolerant western larch, 
these values were inverted so that they could be easily compared with the 
purity metric. The resulting values are shown in Table ~\ref{tab:shade}. 
Shade intolerance values were multiplied by individual tree 
basal area values, and then summed: 

\begin{equation}
\label{eq:shade}
T = \frac{\sum\limits_{k}{\rho_{s} BA_{s_k}}}{\sum\limits_{k} BA_k}
\end{equation}

where $T$ represents plot shade intolerance at a given measurement and 
$\rho_{s}$ represents the species $s$ shade intolerance value for  
tree $k$ \citep{Lienard2015}. $T$ effectively describes community 
shade-intolerance through a proportion of plot basal area, where a $T$ value of 1 
means that a plot at a given measurement is composed completely of shade intolerant 
species, and a value of 0 means a plot is composed completely of shade tolerant 
species. 
% Since the subject trees across this model are western larch, it is not 
% possible for a value to be zero. 


\begin{table}
\caption[Shade intolerance values]{Shade intolerance values, which are the inverse of shade tolerance values provided by Lienard (\citeyear{Lienard2015})}
\label{tab:shade}
\centering
\begin{tabular}[t]{>{}l>{}lr}
\toprule
Genus & Species & Shade intolerance\\
\midrule
\em{\cellcolor{gray!6}{Larix}} & \em{\cellcolor{gray!6}{occidentalis}} & \cellcolor{gray!6}{1.00}\\
\em{Pinus} & \em{contorta} & 1.00\\
\em{\cellcolor{gray!6}{Pinus}} & \em{\cellcolor{gray!6}{ponderosa}} & \cellcolor{gray!6}{0.75}\\
\em{Pinus} & \em{monticola} & 0.50\\
\em{\cellcolor{gray!6}{Pseudotsuga}} & \em{\cellcolor{gray!6}{menziesii}} & \cellcolor{gray!6}{0.50}\\
\addlinespace
\em{Abies} & \em{grandis} & 0.25\\
\em{\cellcolor{gray!6}{Abies}} & \em{\cellcolor{gray!6}{lasiocarpa}} & \cellcolor{gray!6}{0.25}\\
\em{Picea} & \em{engelmannii} & 0.25\\
\em{\cellcolor{gray!6}{Thuja}} & \em{\cellcolor{gray!6}{plicata}} & \cellcolor{gray!6}{0}\\
\em{Tsuga} & \em{heterophylla} & 0\\
\bottomrule
\end{tabular}
\end{table}

% - Using them in a model
% - comparing models based on RMSE, quantifying accuracy improvements by each

To evaluate and compare these measures, each was added as an additional smooth 
to the identified base model formulation. Models then compared on the basis of 
accuracy (RMSE) and fit \citep[deviance explained;][]{wood2006generalized}, quantifying 
each predictor's relative improvement to model performance. RMSE values were 
calculated using data that were withheld from model fitting to provide an independent 
estimation of model accuracy. Deviance explained values were extracted from 
model summary outputs. 

% To calculate 
% RMSE, BAI was predicted by each model from the withheld portion data set, 
% and model prediction errors were calculated. 


\chapter{Results}




\section{BAI model}

\begin{table}[!h]
\caption[Base model selection criteria]{Table of effective degrees of freedom (EDF) for each variable, displayed by group. Deviance explained and RMSE values displayed reflect their respective values at the time of model selection, e.g., size, size + competition, etc. RMSE for model selection was calculated on the data used to train models in the selection period, but was degrees of freedom as to avoid bias.}
\label{tab:rmse}
\centering
\begin{tabular}{>{\raggedright\arraybackslash}m{9em}>{\raggedleft\arraybackslash}m{4em}>{\raggedleft\arraybackslash}m{5em}>{\raggedleft\arraybackslash}m{5em}}
\toprule
\hspace{1em}Smooth & EDF & Deviance explained & RMSE ($\mathrm{cm^2}/yr.$)\\
\midrule
\addlinespace[0.3em]
\multicolumn{2}{l}{\textbf{Size}} & 30.82 & 5.64312 \\
\hspace{1em}\cellcolor{gray!6}{DBH} & \cellcolor{gray!6}{8} & \cellcolor{gray!6} & \cellcolor{gray!6} \\
\addlinespace[0.3em]
\multicolumn{2}{l}{\textbf{Competition}} & 62.87 & 4.31 \\
\hspace{1em}\cellcolor{gray!6}{Crown ratio} & \cellcolor{gray!6}{2} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{}\\
\hspace{1em}BAL & 8 & & \\
\hspace{1em}\cellcolor{gray!6}{BA} & \cellcolor{gray!6}{9} & \cellcolor{gray!6} & \cellcolor{gray!6} \\
\addlinespace[0.3em]
\multicolumn{2}{l}{\textbf{Site}} & 67.39 & 4.01197\\
\hspace{1em}\cellcolor{gray!6}{Aspect} & \cellcolor{gray!6}{26} & \cellcolor{gray!6} & \cellcolor{gray!6} \\
\addlinespace[0.3em]
\textbf{Base model} & 1389 & 84.91 & 3.32142 \\
\hspace{1em}\cellcolor{gray!6}{Random intercept} & \cellcolor{gray!6}{1337} & \cellcolor{gray!6} & \cellcolor{gray!6} \\
\bottomrule
\end{tabular}
\end{table}

A basal area increment model was specified with the following predictors: 
DBH, crown ratio (CR), basal area larger than the subject (BAL; expressed as a ratio), 
plot basal area (BA), aspect, and a tree-level random effect. 
The model was fit with a gamma distribution family because it allows for 
increasing dispersion in the response variable. A log-link function was chosen 
to ensure that predictions of growth were positive and non-zero.
The model training data set consisted of %training data set?
5,792 basal area increments across 1,975 individual western larch trees. 
The base model RMSE was ~3.34 $\mathrm{cm^2}/yr.$ Fixed effects terms used 
~53 degrees of freedom, and total model deviance explained was 84.9\%. 
Random effects were accounted for using a spline basis 
\citep{wood2006generalized}, and thus had an associated degrees of 
freedom, which was ~1338. Model residual 
degrees of freedom was ~4401. Model statistics are reported in Table 
\ref{tab:rmse}.

Tree DBH and basal area were highly correlated (0.938) and were 
evaluated in separate models. DBH as a predictor yielded higher 
accuracy in predicting BAI than tree BA, with model RMSE values  
of 5.64 $\mathrm{cm^2}/yr.$ and 5.70 $\mathrm{cm^2}/yr.$, respectively. 

Competition variables were partitioned into two sub-groups:  
variables representing a tree's competitive position in a stand, and variables 
that represent the overall competitive environment. Highly collinear variable 
combinations were were TPA-$D_q$ (0.732) and BA-QMD (0.684).  %, CCF-BA (0.95)
Tree-level variables reduced RMSE to 4.50 $\mathrm{cm^2}/yr.$, and then to 
4.31 $\mathrm{cm^2}/yr.$ with plot BA included.

Topographic variables (slope, aspect, elevation) were evaluated as 
potential predictors separately from site index and heatload. Since aspect
is a circular measure, both sin (easting) and cosine (northing) 
transformations were applied as in previous works \citep{Stage1976}. Aspect was best 
accounted for as an interaction term in the form of an isotropic smooth, a 
reduced rank version of thin-plate splines \citep{wood2006generalized}. 
Slope and elevation contributed little to prediction accuracy 
when included with aspect and were associated with concurvity values 
beyond the established threshold. Thus, building on the model and 
comparing aspect, site index, and heatload, aspect was selected as 
the best term, further reducing model RMSE to 4.01 $\mathrm{cm^2}/yr.$

By group, Competition metrics contributed the most in 
deviance explained, followed by size. However, considering 
variables individually, DBH explained more deviance and reduced RMSE 
more than any other variable in the model. 

Partial response curves are shown in Figure \ref{fig:basesmooths}. DBH had an 
overall increasing effect on BAI, eventually tapering at values larger 
than 30cm. Crown ratio was penalized to a near-linear increasing effect that 
was relatively small overall, going from negative to positive at values near 
0.7. BAL showed a modest positive effect which decreased to a slightly 
larger negative effect as western larch became less dominant in a plot. 
Basal area (BA) was represented by an overall decreasing effect, where densities greater 
than 10 $\mathrm{m^2}/ha$ were associated with an increasingly negative effect on growth, 
that tapered off and became less certain at values exceeding 40 $m^2/ha$. As 
aspect varied, the partial effect on growth varied, where positive effects 
were associated with N-NW, N-NE, and NE aspects. NW and SE aspects were associated 
with some negative growth. Data was not sufficient for esimating aspect effects 
for south-facing aspects. 

\begin{figure}
\centering
% \begin{subfigure}[b]{0.7\textwidth}
\includegraphics[width=0.7\textwidth]{../17.figures_saved/base_smooths.png}
% \end{subfigure}
% \begin{subfigure}[b]{0.7\textwidth}
% \includegraphics[width=\textwidth]{../17.figures_saved/base_aspect.png}
% \end{subfigure}
\caption[Base model smooths]{Smoothed effects fitted by the selected base model. The top 4 plots show the 1 dimensional smooth effects for diameter at breast height (DBH), tree crown ratio, ratio of basal area larger than a subject (BAL), and plot basal area (BA). Effect scales vary by smooth.}
\label{fig:basesmooths}
\end{figure}

% -- model fitting rmse table -- 



% Furthermore, aspect effects were evaluated in the model separately as easting, 
% northing, as a joint interaction term, and as a decomposed tensor 
% product interaction term (CITE - wood?).
% to ensure that multi-level competitive effects were captured

\section{Assessing species-mixing impacts on growth}

% modeling mixtures
%% maybe i should constrain plotted curves to only pure larch that lie between west and north?
The model fitted for western larch growth compared across mixtures 
was informed by a variety of conditions as displayed in table 
(Table ~\ref{tab:mixsummary}). Species compositions can vary with 
variations in aspect due to species preference to different niches, so it was 
important to consider where data was modeled from. 
Pure larch stands evaluated sat on northerly aspects spanning from west to east
(Fig. ~\ref{fig:asp}), and both mixtures evaluated showed some preference towards northwest 
facing slopes, but ultimately data spanned a similar range to the pure conditions. 
The reference curve captured variability in each 
predictor with high certainty. Crown ratio was penalized to a linear effect, 
but still held a non-zero effect. The reference smooths fit for each term closely 
resembled those of the base model, and thus are not displayed. 

Model intercepts and difference intercepts are reported at the bottom of 
Table ~\ref{tab:mixsummary}. Here, there is some evidence for the mean response 

The intercept for the pure larch reference 
condition represents the mean response of that condition, and the difference 
intercepts represent the difference between the reference and each respective 
condition being compared. 

%% present results from summary output table. 
\subsection{Western larch-lodgepole pine mixtures}
% Western larch growth varied in mixture type compared to homogeneous conditions 
% in response to each variable. 
There was strong evidence indicating a departure of growth response from pure conditions
as tree size (DBH), symmetry of competition (BAL), and stand density (BA) varied
when mixed with lodgepole pine, and modest  
evidence for such in crown ratio and aspect (Table ~\ref{tab:diff}). 
In these mixtures, growth was even less in smaller western larch trees, 
but became even greater when larch diameters exceeded ~12cm, compared to pure stands. 
A similarly-shaped difference effect is displayed as western larch takes up more growing space 
in its community to taking up less space than lodgepole pine 
(as BAL increases from zero). The difference curve for BAL 
(Fig. ~\ref{fig:diffsmooths}), practically 
outweighs the reference curve respective of the line of 0 difference,
indicating that asymmetric competition that is in favor of larch may negatively 
impact it's growth and in favor of lodgepole pine may drive an increase in growth, 
given that other variables remain constant. Furthermore, basal area effects were 
hardly different for this mixture type, but were positively and negatively 
intensified at very low densities and higher densities, respectively, 
although the uncertainty becomes somewhat unmanageable at higher densities, 
likely due to a lack of high-density data for this mixture type. 

\subsection{Western larch-Douglas-fir mixtures}

For larch-Douglas-fir mixtures, growth deviated from the pure stands 
as crown ratio, stand density, and aspect varied, but little to no variation was 
observed in response to different levels of tree size or symmetry of competition. 
The growth difference in response to crown ratio were slightly elevated 
for larch-Douglas-fir mixtures and only in mid-range values of CR (Fig. ~\ref{fig:diffsmooths}), 
but the slight change likely doesn't have any important interpretation due to 
the small impact. Similar to the lodgepole pine mixtures, basal area impacts on 
growth in Douglas-fir mixed larch were were intensified at higher densities. 
This impact, however, was comparatively smaller than that of the lodgepole pine 
mixtures; the rate of this magnifying effect may require further investigation 
using methodologies appropriate for such comparisons. 



%Table of mixtures, min, max, mean for each variable in model

\begin{table}[H]
\caption[Mixtures data summary]{Summary table for different species-mixture data subsets.}
\label{tab:mixsummary}
\centering
\begin{tabular}{llrrr}
\toprule
Variable & & Pure larch & Larch-lodgepole & Larch-Douglas-fir\\
\midrule
\multicolumn{1}{c|}{\cellcolor{gray!6}}& \cellcolor{gray!6}{min} & \cellcolor{gray!6}{0.05} & \cellcolor{gray!6}{0.03} & \cellcolor{gray!6}{0.10}\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & max & 53.3 & 29.7 & 36.2\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & \cellcolor{gray!6}{sd} & \cellcolor{gray!6}{7.69} & \cellcolor{gray!6}{5.76} & \cellcolor{gray!6}{5.48}\\
\hhline{~|}
\multicolumn{1}{c|}{\multirow[c|]{-4}{*}{\cellcolor{gray!6} BAI($\mathrm{cm^2}$)}} & mean & 8.94 & 7.53 & 6.05\\
\hhline{-|----}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & min & 0.5 & 0.8 & 0.5\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & \cellcolor{gray!6}{max} & \cellcolor{gray!6}{57.7} & \cellcolor{gray!6}{22.6} & \cellcolor{gray!6}{38.9}\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & sd & 11.7 & 4.3 & 6.2\\
\hhline{~|}
\multicolumn{1}{c|}{\multirow[c|]{-4}{*}{\cellcolor{gray!6} DBH($cm$)}} & \cellcolor{gray!6}{mean} & \cellcolor{gray!6}{13.6} & \cellcolor{gray!6}{9.2} & \cellcolor{gray!6}{12.4}\\
\hhline{-|----}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & \cellcolor{gray!6}{min} & \cellcolor{gray!6}{0.08} & \cellcolor{gray!6}{0.20} & \cellcolor{gray!6}{0.08}\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & max & 0.93 & 0.93 & 0.93\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & \cellcolor{gray!6}{sd} & \cellcolor{gray!6}{0.25} & \cellcolor{gray!6}{0.18} & \cellcolor{gray!6}{0.24}\\
\hhline{~|}
\multicolumn{1}{c|}{\multirow[c|]{-4}{*}{\cellcolor{gray!6} Crown ratio}} & mean & 0.61 & 0.78 & 0.53\\
\hhline{-|----}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & min & 0.00 & 0.00 & 0.00\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & \cellcolor{gray!6}{max} & \cellcolor{gray!6}{1.00} & \cellcolor{gray!6}{1.00} & \cellcolor{gray!6}{1.00}\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & sd & 0.30 & 0.27 & 0.29\\
\hhline{~|}
\multicolumn{1}{c|}{\multirow[c|]{-4}{*}{\cellcolor{gray!6} BAL (ratio)}} & \cellcolor{gray!6}{mean} & \cellcolor{gray!6}{0.59} & \multicolumn{1}{c|}{\cellcolor{gray!6}}{0.64} & \cellcolor{gray!6}{0.58}\\
\hhline{-|----}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & \cellcolor{gray!6}{min} & \cellcolor{gray!6}{0.23} & \cellcolor{gray!6}{0.13} & \cellcolor{gray!6}{0.67}\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & max & 55.9 & 23.4 & 69.1\\
\hhline{~|}
\multicolumn{1}{c|}{\cellcolor{gray!6}} & \cellcolor{gray!6}{sd} & \cellcolor{gray!6}{11.5} & \cellcolor{gray!6}{5.4} & \cellcolor{gray!6}{16.0}\\
\hhline{~|}
\multicolumn{1}{c|}{\multirow[c|]{-4}{*}{\cellcolor{gray!6} BA($ft^2/ha$)}} & mean & 12.8 & 9.2 & 21.7\\
\hhline{-|----}
\multicolumn{2}{c}{\cellcolor{gray!6}{Observations}} & \cellcolor{gray!6}{1358} & \cellcolor{gray!6}{396} & \cellcolor{gray!6}{638}\\
\hhline{~|}
\multicolumn{2}{c}{Unique trees} & 497 & 211 & 320\\
\bottomrule
\end{tabular}
\end{table}

%figure showing dist. for aspect? maybe switch to other variable?
% \begin{figure}
% \centering
% \begin{subfigure}[b]{0.75\textwidth}
% \includegraphics[width=\textwidth]{../17.figures_saved/compass_laoc.png}
% \end{subfigure}
% \begin{subfigure}[b]{0.75\textwidth}
% \includegraphics[width=\textwidth]{../17.figures_saved/compass_pico.png}
% \end{subfigure}
% \begin{subfigure}[b]{0.75\textwidth}
% \includegraphics[width=\textwidth]{../17.figures_saved/compass_psme.png}
% \end{subfigure}
% \caption[Mixture aspects]{Distribution of aspect values for each species-mixture evaluated, respective of their values on a $0-360^{\circ}$ compass.}
% \label{fig:asp}
% \end{figure}

\begin{figure}
\centering
\includegraphics[width=0.75\textwidth]{../17.figures_saved/compass_all.png}
\caption[Mixture aspects]{Distribution of aspect values for each species-mixture evaluated, respective of their values on a $0-360^{\circ}$ compass.}
\label{fig:asp}
\end{figure}


%state which values are significant and for which term

% table of significances
\begin{table}
\centering
\caption[Difference smooths table]{Table of effective degrees of freedom for difference smooths and p-values. P-values < 0.001 indicate strong evidence for a difference, < 0.01 indicate moderately strong evidence, < 0.05 indicate some evidence, and > 0.05 indicate little to no evidence. Estimated intercept values for the reference smooth and two conditions are shown in the lower portion, where the reference p-value indicates if the mean bai (response) for pure conditions differs from zero, and if each mixture's average values differ from the mean value of the reference.}
\label{tab:diff}
\begin{tabular}{lcrcr}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{Larch-lodgepole} & \multicolumn{2}{c}{Larch-Douglas-fir} \\
\cmidrule(l{3pt}r{3pt}){2-3} \cmidrule(l{3pt}r{3pt}){4-5} 
Smooth & EDF & p-value & EDF & p-value\\
\midrule
\cellcolor{gray!6}{DBH} & \cellcolor{gray!6}{2.75} & \cellcolor{gray!6}{$< 0.001$} & \cellcolor{gray!6}{2.14} & \cellcolor{gray!6}{0.398}\\
Crown ratio & 2.78 & 0.031 & 3.74 & 0.004\\
\cellcolor{gray!6}{BAL ratio} & \cellcolor{gray!6}{3.12} & \cellcolor{gray!6}{$< 0.001$} & \cellcolor{gray!6}{2.11} & \cellcolor{gray!6}{0.122}\\
BA & 4.69 & $< 0.001$ & 2.23 & 0.001\\ %0.0012
\cellcolor{gray!6}{Aspect} & \cellcolor{gray!6}{6.61} & \cellcolor{gray!6}{0.014} & \cellcolor{gray!6}{10.7} & \cellcolor{gray!6}{$< 0.001$}\\
\bottomrule
\multicolumn{1}{l}{Intercept} & \multicolumn{2}{c}{Estimate} & \multicolumn{2}{c}{p-value}  \\
\midrule
\multicolumn{1}{l}{\cellcolor{gray!6}{Reference}} & \multicolumn{2}{c}{\cellcolor{gray!6}{-0.0452}} & \multicolumn{2}{c}{\cellcolor{gray!6}{$0.018$}} \\
\multicolumn{1}{l}{Larch-lodgepole} & \multicolumn{2}{c}{-0.256} & \multicolumn{2}{c}{0.694} \\
\multicolumn{1}{l}{\cellcolor{gray!6}{Larch-Douglas-fir}} & \multicolumn{2}{c}{\cellcolor{gray!6}{-0.138}} & \multicolumn{2}{c}{\cellcolor{gray!6}{$0.778$}} \\
\bottomrule
\end{tabular}
\end{table}

%% given those results, here are some partial response curves 
%show smooths
\begin{figure}
\centering
\includegraphics[width=\textwidth]{../17.figures_saved/mix_diff_smooths.png}
\caption[Difference smooths]{Smoothed differences for Larch-lodgepole pine mixtures and Larch-Douglas-fir mixtures are shown on the right and reference curves are shown on the left for visual comparison.}
\label{fig:diffsmooths}
\end{figure}


\section{Comparing species-mixing measures}

%
Models were specified for each species-informed measure. 
Both shade intolerance and purity were fit as additional 
predictors in respective models. CCF and basal area 
were found to be highly correlated with one-another, so ccf was included 
in its respective model in place of BA, as to avoid issues of collinearty 
among predictors. 

%Table w/ rmseand stuff (is below)
Model accuracy was best improved by the addition of stand purity, followed by 
plot shade intolerance and plot crown competition factor (Table ~\ref{tab:mixvarsrmse}). 
Every term in each respective model was backed by a p-value < 0.001, indicating 
that each was non-zero, provided that smoothing parameter estimation and model 
selection were moderately error-free. Changes in RMSE were modest, all of which 
were at the sub-square centimeter per year -level. Model fit increased in concert with 
improvements to accuracy except for with CCF, which 
showed a small decrease in deviance explained (Table ~\ref{tab:mixvarsrmse}) and 
$R^2$.

CCF displayed the largest effect on tree growth, followed by purity and 
shade intolerance (Fig.~\ref{fig:ccf_pur_shd}). However, since CCF is a measure of stand 
density, it appears very similar to the basal area smooth in the base model. 
Both purity and shade intolerance were characterized by positive effects on 
growth for lower values, and slightly negative effects on growth for positive 
values. Shade intolerance effects appear highly uncertain compared to those of 
purity and CCF, and non-zero effects are hard to identify with this model. 
Smooths for purity and shade intolerance were generously fit with numerous 
basis functions, or perhaps minimal penalization, which contributes to their wiggliness 
and uncertainties. As a result, shade intolerance effects are difficult to 
interpret. 

%Show smooths for each measure

\begin{figure}
\centering
\includegraphics[width=\textwidth]{../17.figures_saved/ccf_pur_shd.png}
\caption[CCF, purity, shade intolerance smooths]{Fitted smooths for crown competition factor (CCF), purtiy (of larch), and shade intolerance. Error bars represent 2 standard deviations and account for uncertainty in smoothing parameter estimation.}
\label{fig:ccf_pur_shd}
\end{figure}


% -table of RMSE, dev.expl values for each model-

\begin{table}[!h]
\caption[CCF, purity, shade intolerance table]{RMSE, deviance explained, and adjusted $R^2$ values for the base model, and models includeing each species-informed variables}
\label{tab:mixvarsrmse}
\centering
\begin{tabular}{lrrr}
\toprule
Model & RMSE ($\mathrm{cm^2}/yr.$) & Deviance explained (\%) & $R^2$\\
\midrule
\cellcolor{gray!6}{Base} & \cellcolor{gray!6}{4.814} & \cellcolor{gray!6}{84.91} & \cellcolor{gray!6}{0.77886}\\
CCF & 4.801 & 84.42 & 0.77597\\
\cellcolor{gray!6}{Purity} & \cellcolor{gray!6}{4.595} & \cellcolor{gray!6}{85.07} & \cellcolor{gray!6}{0.77942}\\
Shade intol. & 4.627 & 85.02 & 0.77946\\
\bottomrule
\end{tabular}
\end{table}

%bullet point list of results
 % - competition and density metrics contributed the most in deviance explained, followed by size.
 % -- DBH was the best individual predictor
 % -

\chapter{Discussion}

\section{GAMs and model selection}

--- A blurb about GAMs, their usage, the pros, the cons. 
- The use of generalized additive models is becoming more prevalent in 
ecological research to capture non-linear patterns that exist in 
ecosystems.

 -- Since the models fit here estimate BAI conditional on a gamma 
 distribution with a log-link function, the model terms together may be considered 
 to have a multiplicative effect, allowing for interpretation 
 of terms as interactive with one another. 
 
 % \[g(E(BAI)) \~ \Gamma(\mu,\alpha)\]
 
 --- Therefore, a one-unit change in a value of diameter will have a multiplicative 
 effect on the response. 
 
 --- This provides the flexibility to remark on 

 -- but it is not a panacea 
 
 -- Discuss bias-variance tradeoffs in GAMs
 
 -- complexity-computation time tradeoffs
 
 -- difficulty with p-values and interpretability
 
--- Now contextualize with the results reported above 

--- 1. Point: The tradeoffs discussed above were encountered/considered

 -- The inclusion of individual tree REs instead of capturing variation 
 at every stand level. 
 % Residual dependence structure  (provide figure with boxplots of normalized residuals across sites?)
 
 -- The base model formulation used a global smoother for each term 
 
 -- The random effect produced intercepts for each individual tree, each
 sharing one general smoother. 
 
 -- this limits variance and produces tree and site-specific biases which
 can result in overfitting if smooths are not constrained by penalties.
 
 % -- shrinkage penalty approach was used here. No apparent patterns missed 
 % in residuals. (plot?)
 
 -- - Fitting smooths for each individual tree would not only 
 up complexity and computation time. It also wouldn't work 
 because each tree only has a few observations. 
 
 % -- Further, bias may be created for fitting smooths for each site.
 
 % --- However, upping complexity for the sake of allowing for 
 % stand-specific variability to occur may not have been particularly 
 % useful since there is a model term that accounts for variation in site. ? 
 
 --- BUT - allowing site-growth relationships to vary by stand could 
 be useful. 

 
 -- When comparing growth response across mixtures, we allowed for 
 group-specific smooths to be evaluated (rather, smooth differences), reducing bias in estimation, 
 but increasing variance for each group-level. this is appropriate, 
 given that comparing across groups was the goal. this, however can 
 lead to higher computational demand to fit the model, especially as 
 the amount of observations increase. 
 
 -- Since these models were fit with their generalization in mind, 
 comparing species-informed measures, all fit with global smooth terms, 
 was appropriate in order to be able to determine if such a measure 
 could be of use in future growth modelling efforts. 

- The p-values reported for smooth term significance are uncertain because 
 there is uncertainty in both model selection as well as in smoothing parameter 
 estimation
 -Zuur suggests that anything below 0.001 is still 'significant', 
 and anything greater than 0.01 should be handled with caution. 

---- model selection ----- 

-The model formula specified here is more or less in concurence with others efforts. 

- Vospernik 2020 found that only including BAL as a competition measure 
was sufficient in capturing competitive effects. That option was 
excluded here because it was thought important to consider tree-level 
competitive effects in addition to community effects. 

- Intially ccf was considered as a Competition measure, 
and CCF was selected in a model formulation with slope as well, however 
the benefit to RMSE that this formula provided was marginal compared 
to the formula that included BA. Further, to accommodate analyses which 
recognized CCF as a species composition informed measure, 
it was deemed more practical to compare non-species informed BA to CCF

% - These results are more or less concurrent with previous studies on the matter.
%  -- perhaps important to highlight the fact it was different from others
%   -- contrast with other bai models
%   -- gam fitted bai models in particular?


\section{Assessing species-mixing impacts on growth}

Point: The difference between larch growth in the lodgepole-mixed and 
pure larch conditions is suggestive that interspecific competitive dynamics 
between western larch and lodgepole pine are different from intra-specific 
dynamics for pure larch stands. 

 -- This is shown by an amplified negative growth effect for small diameter  
 larch and similarly increased positive effect for larger diameter larch 
 when mixed with lodgepole pine.
 -- These diameter-related effects are similar/different to:
  -- x 
  -- y 
  -- z

 -- Also, larch-mixed with lodgepole had far less growth when the larch were 
 larger than neighboring lodgepole pine, and higher rates of growth when the 
 lodgepole pine were larger. %look at where the predictions are coming from 
 -- this is similar/different to:
  -- riofrio, other papers. 
  -- likely depends on basal area
  -- and/or diam.
  -- investigate other vars changing..
  
  
 -- Discuss theory behind why this might happen
 --- competition for light/above ground comp (usually posited for inter-specific comp.)
 --- below-ground competition (usually posited for intra-specific comp.)
 --- 
 
 Caveat:
 -- Difficult to draw conclusions due to 
 -A. uncertainty in estimation (although p-values aren't too bad)
 -B. Because the variations in one covariate could relate to 
 the variations in a different covariate (despite the collinearity assessment)
  - thus these types of analyses require careful consideration of 
  i. choice of covariates in model and the processes they account for
  ii. model selection. 
  
 -- Its been suggested that defining different mixtures with proportion of 
 basal area alone can lead to inaccurate estimations of individual tree growth
 since mixture effects depend on site conditions \citep{Huber2014}. 
 Here, mixing was defined by either weighted or unweighted proportions of 
 basal area. Although different mixture types were not weighted specifically 
 by site conditions or stocking potentials as the literature suggests, 
 site conditions were considered in the model as a separate term, aspect. 
 Furthermore, since the model was specified with a log link function, 
 changes in one predictor have a multiplicative effect 
 on growth with the other predictors, so a change in mixing proportion relates 
 to growth in such a way that is dependent on the value of aspect. Therefore, 
 given that aspect represents site potential - an assumption made here based 
 on previously identified empirical studies \citep{Stage1976,Kimsey2019}, 
 then no such weighting is necessary. 
 
 Relying on aspect as the sole predictor relating to site conditions, however, 
 may be a limitation of the current study. Aspect was selected in the model 
 because it outweighed alternative measures, including a more comprehensive 
 heatload metric, which is based on a combination of slope, aspect, and 
 elevation. Including additional site variables to 
 aspect was associated with a high degree of interdependence among variables, 
 represented by model concurvity. For example, as a first pass, aspect, slope, 
 and elevation were compared to determine the best of the three. After selecting 
 aspect, the addition of slope and/or elevation both drove concurvity higher 
 than the established maximum threshold. Aspect on its own, was then compared 
 against heatload and stand-specific intercepts. The stand intercept version 
 had the lowest RMSE value, but was associated with a high degree of concurvity.
 
 These points highlight an overarching consideration: model selection is 
 associated with uncertainty. 
 -- Talk about different methods of model selection
 -- Mention that mgcv has options for selection, but I did not use them because 
 1. wanted to ensure that all effects are captured
 2. avoid using black-box methods
 -- wood says: "The more thought is given to appropriate model structure up front, the more successful model selection is likely to be. Simply starting with a hugely flexible model with ‘everything in’ and hoping that automatic selection will find the right structure is not often successful."
 -- Perhaps it could make sense to apply further penalties as a check once the base model is identified?
 
 -- Point about random forests ?
 -- point?
 

-- CCF, Purity, shade intol. --

Point: CCF is already widely used in regional growth models, but implementing other measures 
could improve model performance in its place. 

 -- In this study, a model with purity of stand (the ratio of a given species) 
 out-predicted and out-fit models with alternative measures.  
 --- This more or less is in alignment with the findings of:
  --- Weiskittel2009 - stand composition can influence max. size-density relationship
  --- Huber2014 - different stocking potentials of species in mixtures 
  (for a given site) should be taken into consideration prior to comparing growth
  ---- and: mixture effects depend on site conditions
  % --- Perhaps the base model selection methods implemented here did not 
  % adequately take into consideration the effects of site on tree growth?
  --- There may be some indication in model predictions of growth across the 
  range of basal area (Figure?) that purity has some influence on the effect 
  of density on western larch growth. 
  ----- in figure .... We see that at low levels of purity, there are higher 
  predicted values of BAI compared to high levels of western larch purity, 
  which resulted in lower growth rates. 
  ----- A similar trend may be observed across the range of BAL. 
  --- This is somewhat concurrent with 
  
  
 -- The results here indicate that shade tolerance was also useful in estimating 
 larch growth, however, its fitted relationship with growth was highly variable 
 and had minimal confidence in predictions
 
 --- Both these studies said shade tol. dissimilarity is useful: Chen2016 and Searle2020
 ---- They found that shade tolerance dissimilarity reduced competition
 ---- also found that smaller trees benefited more than larger trees from 
 increased diversity. 
 
 --- The findings of this study were inconclusive to make such determinations. 
 --- evaluating predictions of BAI at varying levels of basal area across the 
 range of observed shade intolerance values did provide some visual evidence 
 that the constant predicted value of BAI changes at different levels basal 
 area, and that the magnitude of effect that shade intolerance had on growth 
 may vary at different values of basal area. 
 --- looking across the range of basal area, lower values of shade intolerance 
 are associated with higher growth across the range of basal area, but due to 
 high uncertainty in predictions, conclusive evidence for a difference does not 
 exist. 
 --- similarly, across the range of BAL, lower values of shade intolerance 
 are associated with higher values of predicted growth, holding everything 
 else constant, but the certainty of predictions do not allow for extrapolation 
 beyond this case. 
 --- There simply was not enough data to provide detailed evidence for a shade 
 intolerance effect on larch growth
 
 % Speculating on the fitted curve may be similarly suggestive that 
 %dissimilarity is beneficial to growth, but hard to say. 
 
 



% - The p-values are not strictly valid (Wood 2006)
% - We did not explicitly select model degrees of freedom, so that's in our favor
% - fitting the model unpenalized could ameliorate issues, but this may render 
% the test pointless because we're trying to describe ecological dynamics
%  -- sorta like in the case of 
 
 

 
%  
% -- Discuss the discrepancy between the rate at which the negative ba-provoked 
% growth difference becomes more negative, comparing douglas fir and lodgepole mixed larch
% -- discuss the limitations of this approach, as it does not offer pairwise comparisons 
% among all conditions. 

% -Acquah2020 discusses competition modification by species mixing
%   -- points
%   --- Higher intra*specific comp. for smaller douglas fir
%   --- no general pattern in larger trees. 
%   --- main driver limiting growth in the stands is aboveground competition for light
% 
% -Contreres said BAL is good for all trees in the study
 
% 
% \subsection{Comparing species-mixing measures}
% 
% - discussion on BA proportion as a measure of species-mixing
% - pros and cons of ccf as a mixture variable
% - using ba as a versatile variable to do things? look in mixed species book



\chapter{Conclusions}

TBD


% \captionof{equation}{Root mean squared error (RMSE) equation, where \hat{y} 
% represents a predicted value, y represents an observed value, and n_{df} 
% represents model residual degrees of freedom}

% The following steps outline the pragmatic variable selection
% approach mentioned in step (ii) above:
% \begin{enumerate}
%   \item Evaluate co-linearity of within-group predictors with each other to help avoid redundant inclusion of variables. 
%   \item Only necessary or inherent interactions were considered, such as an interaction between sin(aspect) and cos(aspect). 
%   \item Different groups of variables within groups were compared with RMSE. 
%   \item Ultimately, the lowest RMSE version within each group was chosen based on the above workflow.
%   \item A concurvity \citep{Hastie1990} assessment was then conducted between variables within each group. If concurvity was greater than 0.8 for a particular set of terms, then an alternative not including both terms was evaluated. 
% \end{enumerate}
% 
% The following steps outline the implemented selection framework:
% (i) evaluating and estimating potential explanatory variables 
% in the available data set based on established relationships
% with the dependent variable (BAI), (ii) sequentially
% selecting predictor variables within the pre-determined groups 
% through a pragmatic variable selection approach to identify
% a base-model structure for the GAM, and (iii) evaluating random effects.
% 




% The order of these variable groups is 
% the order in which the model formulation was iteratively constructed, 
% based on their previously identified relative importance 
% in estimating BAI .


% (iv-a) assess whether larch growth varies across different types of mixtures
% (iv-b) assessing effects produced by identified species-mixing variables. 

% For (i), explanatory variables were identified based on availability 
% in the PGP data set and whether they could be calculated from the 
% available data. 
% Variables contained in established and widely-used
% empirical models, such as the diameter growth model in FVS \textbf{(*CITE*)},
% were considered because, 1. the PGP data collection focused on such
% variables, and 2. these variables are relatively easy to collect 
% and commonly found in long-term data collection efforts similar to
% the PGP data. 
% This allows for the potential expansion of these 
% methodologies to other, similar works. 
% Variables considered that were beyond the scope identified above, related primarily to site conditions. 

% \textbf{**ADD TABLE that lists variables from the ln(DDS) model, as well as variables not in that model in BOLD text?**} 
% Once explanatory variables were identified for consideration,
% they were then grouped into the following categories: tree size,
% density and competition, and site.




% The following steps outline the pragmatic variable selection
% approach mentioned in step (ii) above:
% 
% \begin{enumerate}
%   \item Evaluate co-linearity of within-group predictors with each other to help avoid redundant inclusion of variables. Any pair-wise linear relationship with a correlation coefficient of 0.7 or higher was not considered together. (R-squared of .49 or higher). This was chosen as the cutoff because .7 correlation means that variance is roughly 50\% accounted for between variables. Additionally, variables known to represent the same processes, like tree basal area and diameter, were not considered together to avoid redundancies and reduce model complexity. 
%   \item Only necessary or inherent interactions were considered, such as an interaction between sin(aspect) and cos(aspect). 
%   \item Different groups of variables within groups were compared with RMSE. 
%   \item Ultimately, the lowest RMSE version within each group was chosen based on the above workflow.
%   \item A concurvity \citep{Hastie1990} assessment was then conducted between variables within each group. If concurvity was greater than 0.8 for a particular set of terms, then an alternative not including both terms was evaluated. 
% \end{enumerate}

% -FIGRE/TABLE of colinearity assessment?- (maybe include in table of variables?) tile plot? table of corrs?--


% , *such terms will be scrutinized.* (Johnston et al 2019 uses a very low concurvity cutoff. It oftentimes is arbitrary). 

%2.%*These two were inherent because they are derived from the same variable, aspect, which cannot be used in its raw form due to scaling issues. The sin/cos transformation and the resulting interaction term allows this variable to represent aspect in a way that parses out east-west from north-south. Model comparisons were made with their inclusion and without.*


% 3.*For example, in the site variables group, 3 different groups were compared - heatload, site index, and raw topographic variables. The model bearing the lowest RMSE (highest predictive accuracy) was selected. These groups were derived as a result of the colinearity assessments as well as prior knowledge that heatload is derived from topographic variables and site index is meant to serve as a catch-all that accounts for all site variables. In the case of site variables as well, a stand categorization intercept was evaluated against the other within-group groups to account for site effects. *

% Step (iii) Random effects
% 
% Step (iv) species mixing

% \subsubsection{Within-group dimensional reduction}
% 
% Selecting variables within each group posed challenges due to the 
% number of predictors, colinearity and/or concurvity among variables
% and terms, and the numerous potential interactions between variables
% within groups. This required a firmly-structured process where
% co-variate relationships are assessed. 
% 
% **DEFINE CONCURVITY** (Hastie and Tibshirani 1990)
% 
% *curse of dimensionality of nonparametric functions* Wood(2004) 
% stable and efficient multiple smoothing parameter estimation for
% generalized additive models
% *Sure-independence screening*
% 
% Prior to implementing the steps here, assessment of co-linearity
% was performed between variables within each group, since there is
% some amount of redundancy within groups. This assessment was made 
% through plotting each variable with each other variable, identifying
% if there is a relationship through graphical analysis, and then 
% evaluating the strength of linear relationships with r-squared values. 
% Additionally, if one variable is derived from another present, 
% these will not be considered as covariates in the same model.

% \subsubsection{Evaluating species mixing}

% Once a parsimonious base-model is selected, species-mixing variables 
% will then be added to detect if there is a species-mixing effect. 
% Further elaboration on applying this approach will be explained in
% the following text. **The following equation** (Equation...xxx) 
% represents the modeling framework: 



% \subsection{Basal Area Increment Model}

% Here is an equation:
% \begin{align}
% B & = \frac{2^x}{\sin{\theta}} \sum_{i=1}^N y_i^3 \\ \nonumber
% & = 3
% \end{align}
% 
% \section{A second section}
% \subsection{With one subsection}

% Here is a code chunk.
% 
% <<no_need_for_a_name>>=
% 10^3
% @
% and another without the call showing.
% 
% <<no_need_for_a_name,echo=F>>=
% 10^3
% @
% and you can also do inline \Sexpr{round(pi,5)}.
@

% \chapter{Chunks of extended abstract}
% 
% Western larch (\emph{Larix occidentalis}) is an important tree species that is 
% exclusive to the inland northwest region of North America %[@Knudsen1968; @Schmidt1976; @Schmidt1995]. 
% \citep{Knudsen1968,Schmidt1976,Schmidt1995}.
% It is very intolerant of shade, and grows across a wide range 
% of communities with both shade-tolerant and -intolerant species %[@Baker1949; @Schmidt1988]. 
% A growing body of evidence suggests that species traits in mixed-species 
% forest communities can impact tree growth relationships %[@Forrester2017; @Riofrio2017]. 
% The objectives of this research are: 
% \begin{enumerate}
% \item
% to identify whether community species composition impacts the growth 
% of western larch after accounting for other influential factors, 
% \item to identify if a stand average shade-tolerance more effectively 
% captures species-mixing effects on growth when compared to a less 
% specific relative abundance metric, and
% \item to quantify the degree to which 
% species-mixing impacts the growth of western larch (if an effect is observed).
% \end{enumerate}
% 
% As shown in Fig.~~\ref{fig:junk}, there are many references to consider.
% \begin{figure}\centering
% %\includegraphics[width=\textwidth]{../extab_refs.JPG}
% \includegraphics[width=2in]{../extab_refs.JPG}
% \caption{This is a figure.}\label{fig:junk}
% \end{figure}
% 
% Next I have a table, called Table ~\ref{tab:fake}.
% \begin{table}\centering
% \caption{This is my table.}\label{tab:fake}
% \begin{tabular}{cc}
% \hline
% Row 1 & Column 2 \\ \hline
% 1 & 2 \\
% 3 & 4 \\ \hline
% \end{tabular}
% \end{table}

%%%% BACK MATTER
\backmatter
\chapter*{Literature Cited}
\addcontentsline{toc}{chapter}{Literature Cited}
\bibliography{../zotero_library}{}
% \cite{*} % use this to list all entries in bib file

\end{document}
