\documentclass[12pt, oneside, letterpaper, fleqn]{book}
% fleqn is for left aligned equations
% change oneside to twoside if chapters should all start on odd-numbered pages

%%% Import a bunch of formatting commands, packages
\SweaveInput{options.rnw}

%%% Decide if you want to have figures/tables/floats at the end, or not
\usepackage[tablesfirst,notablist,nofiglist]{endfloat} % or comment out

%%% Line numbering
\linenumbers % or comment this out to suppress line numbering

%%% Actual document begins here
\begin{document}
\SweaveOpts{concordance=TRUE}

%%%% FRONT MATTER
\frontmatter
\thispagestyle{empty} % no header, page number centered on bottom

%%%% TITLE PAGE
% ...can input separate files like this
\SweaveInput{title_page.Rnw}

\pagestyle{plain}

%%%% Other prelim sections...can instead be inserted directly in this file
\chapter*{Acknowledgements}
\addcontentsline{toc}{chapter}{Acknowledgements}

Thanks.

\chapter*{Abstract}
\addcontentsline{toc}{chapter}{Abstract}

The abstract.

\tableofcontents

\addcontentsline{toc}{chapter}{\listfigurename}
\listoftables

\addcontentsline{toc}{chapter}{\listtablename}
\listoffigures

%%%% BODY
\mainmatter
\setlength{\baselineskip}{22pt} % begin double spacing
\chapter{}
\section{Introduction}



% Western larch grows within pure stands and mixed-species stands alike, 
% and is an important species that is unique to the inland northwest 
% region of north america. Evidence shows that ecological dynamics within 
% mixed species stands can lead to modified density-competition dynamics,
% leading to modified tree growth and stand productivity. 
% Ecological niche theory provides a theoretical foundation for these observed effects.
% Capturing these dynamics can improve estimates of tree growth and stand productivity, 
% aiding in management and research efforts. 
% This study aims to explore the impacts of species-mixing on 
% western larch within the context of individual tree growth models. 

Western larch (\emph{Larix occidentalis} Nutt.) is an important tree species
in the inland northwest region of the USA because of its contribution to
ecological, economic, and cultural values across the region. \emph{L. occidentalis}
is endemic and nearly exclusive to the upper Columbia river watershed throughout
Montana, Idaho, Washington, Oregon, and southern British Columbia, and is
well-adapted to the historic climate of the region \citep{Knudsen1968,Schmidt1976,Schmidt1995}.
Additionally, its wood possesses desirable qualities such as high specific gravity,
straight grains, and tight knots \citep{KeeganIII1995}, and it is the most productive of
the three North American larch species \citep{Rehfeldt2010}, adding a unique and
localized product value in the region. Further, western larch and its associated
forests provide important habitat to native birds, bears, and ungulates 
\citep{McClelland1999,Schmidt1976}. In a setting where fire is historically and
currently prevalent, western larch is the most fire resistant of the Northern
Rocky Mountain conifers due to its thick bark and uniquely deciduous needles
\citep{Schmidt1976}. \emph{Larix} species also provide unique aesthetic characteristics
throughout the year, coloring hillsides shades of green,
yellow, and brown, depending on the season, adding a colorful representation of
seasonality. However, projected climate scenarios are likely to impact the
biophysical processes that allow larch to fill its niche within this region \citep{Rehfeldt2010},
threatening these unique values. 


% Western larch naturally grows across a compositional gradient of mixed-species
% forests \citep{Schmidt1988} where interactions among species attributes could impact
% growth and development at individual tree and stand levels.

Western larch naturally grows across a gradient in of species-mixtures 
in mixed-species forests \citep{Schmidt1988}. It is sometimes managed 
in even-aged, homogeneous plantations, but more typically is managed in mixed-conifer settings
where interactions among species attributes that impact
growth and development at tree and stand levels may occur.
Western larch is classified as very intolerant of shade and one of the fastest-growing within
its communities \citep{Baker1949,Schmidt1988}. It is found in communities with:
Douglas-fir (\emph{Pseudotsuga menziesii}(Mirb.) Franco var. \emph{glauca}), 
lodgepole pine (\emph{Pinus contorta}(Dougl.)), Engelmann spruce (Picea engellmanii),
subalpine fir (\emph{Abies lasiocarpa}), ponderosa pine (\emph{Pinus ponderosa}),
western hemlock (\emph{Tsuga heterophylla}), mountain hemlock (\emph{Tsuga mertensiana}),
and western redcedar (\emph{Thuja plicata}) \citep{Schmidt1981a,Schmidt1988}. 


% Since stand density closely relates to tree growth \citep{Reineke1933}, 
% the effects of species-mixing on density can translate 
% to modified competition impact tree growth.

Stand density can be modified at different levels of species 
purity in a stand, depending on the species and/or mixture 
\citep{Condes2013,Brunner2020}. 
Weiskittel et al. (\citeyear{Weiskittel2009a}) found that the 
density of a stand at which self-thinning occurs for a given species was positively 
associated with stand purity, meaning an increase in diversity 
could reduce a site's maximum potential density. In contrast, Pretzsch and Biber 
(\citeyear{Pretzsch2016}) showed that stand carrying capacity was 
positively impacted in more diverse stands. A similar study found that 
maximum stand density increased in shade intolerant ponderosa pine and 
Douglas-fir when species-diversity was higher, but in 
shade-tolerant grand fir, the relative impact 
of stand purity on stand density was unimportant \citep{Kimsey2019}. 

Density modifies inter-tree competition and tree growth, 
where higher density is associated with smaller tree sizes and vice versa
\citep{Oliver1996,Sjolte-Jorgensen1967,Smith1986}. However, 
since species-mixing may be positively, negatively, or not at all 
associated with stand density, then the effect of 
species-mixing on growth can vary. 
Brunner \& Forrester (\citeyear{Brunner2020}) demonstrated that mixture 
affected tree growth only at high densities for their studied mixture.
Concurrently, in a study of grand fir and ponderosa pine mixtures in Oregon,
Maguire and Mainwaring (\citeyear{Maguire2021}) found that 
mixing impacted tree size only at high density at one study site. 
At the other site, however, the number of observations suggesting no effect on growth 
outweighed those that did \citep{Maguire2021}. A study of two European 
\emph{Pinus} species showed positive growth associated with 
species-mixing for one species across densities, but no effect at 
all for the other pine species \citep{Riofrio2019}. Given these results, 
species-mixing effects on tree growth (albeit equivocally) may be more relevant 
at high densities, but the mechanisms that produce 
these effects can provide further insight.

% A common thread 
% among the findings of all of these studies is the discussion of 
% shade-tolerance and complementary or competitive relationships among species


% and was attributed 
% to the mixed shade tolerance between species
% 
% 
% resulting effects of mixing-induced density modifications on tree growth may vary
% Given this evidence, and since , and 
% 
% , 
% 
% and density can vary across mixtures, then tree growth is expected to vary 
% across species-mixtures. This effect, however, depends on the species 
% mixture type, as well as on the level of density. 
% 
% 
% 
% As the level of stand purity modifies density, it in turn can alter tree growth, 
% but this effect may vary depending on the level of stocking.
% So if density can vary depending on species-mixture, 
% then competition may be modified, leading to an impact on tree growth.


% Further evidence suggests that species-mixing can interact with stand density 
% in the long term, and that the interplay between the two likely depends
% on the characteristics of species-mixtures and stand types \citep{Brunner2020, Condes2013}.

% These conifer species collectively span the range of shade tolerance and growth rates. 
A combination of shade-tolerance, height growth rate, water use efficiency,
tree architecture, and other species characteristics within mixed-species 
communities can lead to modifications in competitive and/or complementary 
relationships among species \citep{Forrester2017}. 
In these communities, even small differences in such attributes 
can result in altered species growth rates \citep{Riofrio2017,Forrester2017}.
Moreover, ecological niche theory suggests that mixture effects are stronger 
for highly complementary species \citep{Loreau2010}.
In particular, species shade tolerance relates to the physiological and 
morphological characteristics which drive growth \citep{Reich1998}, 
and thus relates to inter-tree competitive dynamics \citep{Canham2006}.
Additionally, productivity in forests can be enhanced by mixing shade tolerant and 
intolerant species \citep{Zhang2012,Williams2017}, where different species' 
light requirement niches (or shade tolerances) are complementary \citep{Thurm2016}. 
Furthermore, quantifying community competition for light can sufficiently 
capture the effects of biodiversity on productivity \citep{Morin2011}.
Searle and Chen (\citeyear{Searle2020}) found that 
positive complementary effects on individual tree growth increase with both community 
shade-tolerance and phyologenetic dissimilarity. This not only shows that  
shade tolerance can encapsulate its effects on inter-specific competition, 
but also provides evidence for its theoretical foundation.


For stands in the inland northwest, where relatively low intensity 
management occurs over a broad area and across tree, stand, and site conditions, 
managers and researchers use the forest vegetation simulator 
(FVS;\cite{Dixon2020} to estimate future stand dynamics. 
FVS applies a distance-independent individual tree growth model \citep(Stage1973,Wykoff1990) 
to measured tree, density, competition, and site variables to project growth. 
Its formulation is paralelled by growth models in other regions and countries, 
and studies have shown effects of species-mixing using these types of models. 
One european study showed that when incorporated into an indivudal 
tree growth model, and after accounting for tree, stand, and site condtions, 
species-mixing effects effectively improved predictions \citep{Riofrio2019}. 
Vospernik (\citeyear{Vospernik2021}) found that individual tree basal area increment %\citep{Vospernik2021}
was significantly modified in mixtures after accounting for other factors. 
They observed species-mixing effects on \emph{Larix decidua} in mixtures 
with \emph{Picea abies}, \emph{Pinus cembra}, \emph{Fagus sylvatica}, 
and \emph{Betulus spp.}, where it mutually benefited in mixtures
with \emph{Picea abies} \citep{Vospernik2021}. These findings are similar to 
those of Z\"{o}hrer (\citeyear{Zohrer1969}) where incremental growth was increased %Z&ouml;hrer \citep{Zohrer1969}
in mixtures between shade-tolerant \emph{Picea abies} and shade-intolerant
\emph{Larix decidua}.

Given that individual tree growth models can be improved 
by accounting for species-mixing in addition to other variables,
and since there is evidence of this in phylogenetically similar European larch,
then species-mixing effects may be pertinent to
characterizing western larch growth since western 
larch is a shade-intolerant, fast growing species that mixes with 
various other conifers across the inland northwest. 
The focuses of the present study then are to describe 
(i) how community composition impacts the growth of western larch 
given other variables known to impact its growth and 
(ii) how to effectively characterize species-mixing effects 
within the context of distance-independent, individual-tree 
growth modeling in the inland northwest. 
The objectives of the study then are to identify a 
distance-independent individual tree growth model using a data set 
which holds data for varying conditions and mixtures, identify different 
types of mixtures that western larch grows in where its growth may be impacted, 
then determine if western larch growth varies depending 
on mixture type after accounting for other factors, and finally
identify the relative importance of species-mixing in estimating growth, 
while comparing different measures of species-mixing to determine if 
one is better at capturing an effect than others. 

% questions
% \bf{How does community composition (species-mixing) influence the growth of western larch?} 
% \bf{Comparing species-informed measures, how can the effects of species-mixing be best accounted for within an individual-tree growth model?}

% The Forest Vegetation Simulator (FVS;\cite{Dixon2020}), 
% which is used across the region for management planning and research, 
% is driven primarily by an individual tree growth model \citep(Stage1973,Wykoff1990)
 
% Since western larch forests range in species-composition 
% and occur across biophysical conditions, western larch may 
% be subject to the effects of modified competitive or complementary 
% relationships within communities that it grows. 

% due to complementary effects, quantifying community competition for 
% light can sufficiently capture the effects of biodiversity on productivity \citep{Morin2011}.
%  Lebourgeois \citep{Lebourgeois2013}
% found that species mixture modified the growth of \emph{Abies abla} through
% facilitative interactions under drought conditions. In northwestern Montana,
% facilitative and competitive interactions were found to modify growth rates 
% of \emph{Abies lasiocarpa} and \emph{Pinus albicaulis}, depending on environmental
% stressors \citep{Callaway1997}. 

% Additionally, variation of shade tolerance within a community can lead to 
% enhancements on overall community productivity \citep{Zhang2012}. 

% Thus, a shade tolerance informed metric may capture complementarity 
% effects on tree growth and lead to improved estimates thereof. 

% In the case where one focal species is dissimilar 
% from others within its community, competitive 
% dynamics may be effectively captured through a coarse 
% measure of the proportion of the focal species to all others, or stand purity.
% and capturing mixing effects with a stand purity 
% metric can provide insights into this relationship.

% When quantified, shade tolerance may aid in characterizing 
% competition and/or complementarity among species in a mixed-species forest.

% --- Niche complementarity 
% - steed and goeking 2020 talks about niche differentiation in terms of larch and climate
% - phylogenetically dissimilarity may affect tree growth through a reduction in suspeptibility to species specific pests, pathogens, predators. (quote from Searle \& Chen 2020)
% - Original papers (janzen 1970 and Connell 1978)
% - Theory etended to mature plants through resource concentration hypothesis (Parker et al. 2015, groosman et al. 2018)
% - Mature plant communities with more phylogenetically close host species are more susceptable to specialized pest and pathogen outbreak. Thus a tree with phylogenetically distant neighbors may experience less competition and may experience higher growth rates. (Searle \& Chen 2020)

% The mixing of phylogenetically dissimilar species

% Niche complementarity (CITE), or more specifically, the resource concentration 
% hypothesis (CITE parker, grossman), describes conditions where phylogenically
% dissimilar species growing together may experience higher rates 
% of growth from the mixing of traits in a mixed-species forest (CITE. .. .). 
% Previous studies have identified complementary effects among trees with
% differing shade tolerances. \citep{Searle2020} SEARLE 2020 found that such complementary 
% effects on individual tree growth increased with competition intensity. 

% point: It's important to have models that account for processes that drive tree growth which are easy to measure or acquire.
% Individual tree growth models are commonly used to estimate future stand characteristics 
% and conditions to aid in forest management and research. Such models rely on previously identified 
% empirical relationships to estimate growth from tree size, inter-tree competitive dynamics, site conditions, 
% and other readily measured or acquired attributes. Since variables in empirical tree growth models 
% are meant to represent ecological processes from relatively simple metrics and are sometimes meant to 
% be generalized across large geographical areas or conditions, they may fail to accurately estimate 
% tree growth under some conditions. ***X provides evidence here. Y says this.***

% point: empirical growth models are used to estimate future conditions 
% from variables that represent ecological dynamics

% - get after niche complementarity, shade tolerance, weighted density metrics, etc. 
% - add some kind of discussion regarding crown competition factor (ccf paper where he says something about mixed species forests)

% Capturing the effects of species-mixing can be accomplished by various 
% methods, one simply being the incorporation of species-identity into density metrics (CITE?). 
% Several such methods rely on a comparison between mixed-species stands 
% and mono-specific stands (Forrester et al? pretzsch?).
% In the north american west, empirical models such as FVS (CITE) 
% are used to estimate tree growth across a variety of conditions 
% where the model relies on averages from extensive growth samples within 
% a region to provide estimates. Under this paradigm, and where conditions vary so broadly, 
% how can the effects of species-mixing and niche complementarity best be captured in an empirical modeling framework?
% FVS uses crown competition factor (CCF; \citep{Krajicek1961}) which is a species-weighted percent of basal area
% occupied by the theoretical maximum crown area for trees of a given diameter, if they were open grown. 
% This measure is effectively a density that is informed by species crown allometry 
% from which one could infer the relative light use of trees at a site given the stand density, 
% but not the interspecific environmental effects of light-use-diversity on tree growth. 
% 
% Other measures 
% 
% CCF measures density based on a verified relationship between crown width and dbh \citep{Krajicek1961}, 
% and generally follows the following form: \begin{equation}
% \label{eq:}
% CCF = \sum\limits_{i}^{n} \beta_0 + \beta_1 D + \beta_2 D^2
% \end{equation}, where $\beta_i$ parameters represent species-specific coefficents. 
% Values are summed across observations and the measure ultimately provides a percentage of 
% stand basal area occupied by tree crowns. 
% 
% but for the purpose of including species-mixing in empirical models, 

% Evidence of how species-mixing impacts tree growth can shed light on
% relationships that are not currently well-understood if new research is
% expanded to more forest-types. Various studies in Europe have revealed that
% facilitation or competitive reduction in mixed-species stands can lead to
% enhanced productivity when compared to monocultures \citep{Pretzsch2009}.
% This effect is sometimes termed overyielding, with reference to the potential
% for higher than anticipated biomass or volume \citep{Pretzsch2009,Loreau2010}.

% Further evidence suggests that species-mixing can interact with stand density 
% in the long term, and that the interplay between the two likely depends
% on the characteristics of species-mixtures and stand types \citep{Brunner2020, Condes2013}.
% 
% Interactions in communities of variable- and similar- trait
% species within North American \emph{Larix} forests are not well-understood, and 
% thus motivate further investigation to characterize how stand species composition 
% modifies western larch growth dynamics. 

% Reich (\citeyear{Reich1998}) found that \emph{L. laricina} had high levels of growth in both high and low light conditions, compared to other coniferous trees.

% \subsection{Research questions}
% 
% \bf{How does community composition (species-mixing) influence the growth of western larch?} 
% 
% \bf{Comparing species-informed measures, how can the effects of species-mixing be best accounted for within an individual-tree growth model?}

%%% old research questions stuff %%%

% Since there is evidence indicating that species-mixing can impact long-term
% development in temperate forests \citep{Pretzsch2009, Pretzsch2010, Zhang2012},
% I posited that the different physiological drivers motivating growth that
% relate to light interception (i.e. shade tolerance) within an interspecific
% environment can produce appreciable differences in the growth of a species,
% after accounting for tree size, inter-tree competition, site productivity, and stand density. 
% This may happen through the enhancement of competition between species of
% similar shade-tolerance, or competitive reduction between
% species of dissimilar shade-tolerance through niche complementarity
% \citep{Callaway1997, Condes2013,Pretzsch2015, Riofrio2017}. Moreover, 
% complementary or competitive effects of species traits in
% a stand can modify how a species interacts with stand density, 
% and in turn, modify a tree's allometry \citep{Weiskittel2009a}. For example,
% it is known that the density of western larch stands impacts how western 
% larch grows \citep{Schaedel2017a}. However, complementary or competitive interactions
% among species have not been explicitly acknowledged within the context of western larch growth, 
% and may modify density effects on western larch growth, (e.g., a western larch in a high
% density stand may grow more in a mixture with shade-tolerant species than a
% western larch at the same density in a mixture with shade-intolerant species). 

% I predicted that the growth of western larch can respond to species-mixing
% across a gradient of species and may depend on how its surrounding community 
% interacts with light. Specifically, I presume \emph{L. occidentalis} growth will
% be modified positively in mixtures with shade-tolerant species such as 
% \emph{Picea engallmanii}, \emph{Abies grandis}, and \emph{Abies lasiocarpa}. Conversely, 
% I expect that \emph{L. occidentalis} growth will be negatively impacted in mixtures 
% with shade-intolerant \emph{Pinus contorta} and \emph{Pinus ponderosa}. I expect that the 
% roles of mid-tolerant species such as \emph{Pseudotsuga menziesii} in modifying 
% \emph{L. occidentalis} growth will vary, from positive to negative. 

% Therefore, my related research objectives were:
%(i) to identify variables that capture the effect of species-mixing on growth 
% (i) determine if western larch growth varies depending on which type of mixture it is in 
% after accounting for other factors that influence tree growth
% and quantify their respective influences on growth
% quantify the degree to which species-mixing impacts western larch growth, 
% (ii) to determine whether a species shade tolerance informed metric improves growth estimates of western larch trees
% effectively captures the effects of niche complementarity on western larch
% identify whether shade-tolerance, as a measure of interspecificity, captures the effects of mixing,
% (ii) identify, quantify, and compare different species-composition informed metrics within an empirical modelling framework
% the effectiveness of different measures of species-mixing

\section{Methods}
\subsection{Tree growth data}

The Forest Vegetation Simulator (FVS) is a distance-independent, individual 
tree forest growth model that is widely used in the western United States 
to predict tree and stand growth as well as to evaluate management decisions 
\citep{Dixon2020}. To establish a monitoring protocol for the FVS model,
the USDA Forest Service northern rocky mountain region developed long-term permanent growth plot
clusters (PGPs) in managed stands across the inland northwest (NW Montana and northern Idaho),
referred herein to as the PGP program. The initial goal of the PGP 
program was to remeasure the selected stands at regular increments of 
5-10 years in order to provide a robust growth increment data set. 
Various stand measurements were initialized and then remeasured between 
1980 and 2002. The program was then paused, and was only recently revisited 
in 2018 and 2021, creating a wide gap between recent measurements and reducing 
consistency of measurement intervals. 

Each PGP stand consists of 4 plot-clusters: 1 untreated control plot cluster 
and 3 treatment plot clusters, the latter were treated with commercial 
thinning or precommercial thinning, depending on stand age and maturity. 
Stand prescriptions determined target residual densities by species for
the stand in the treatment areas, providing a side-by-side comparison between
control and treatments under similar stand and site conditions. The location 
of control and treatment plots were determined by random selection of (x,y) 
coordinates on a grid laid over a map of the stand. To ensure that the control 
plots were not affected by nearby thinning treatments, an unthinned buffer was
placed around control clusters. Every cluster is comprised of three ~202$m^2$ 
large-tree, fixed-radius plots, with each plot containing three ~13.5 $m^2$ 
small tree fixed-radius sub-plots. Data for trees in large-tree plots were taken 
based on whether a tree was above a specified diameter threshold. 
The diameter thresholds varied across and within stands 
(across control and treatment plots), as well as within clusters over
time. Yet the large trees were tagged and distance and azimuth to plot center
were taken. Heights were taken on only a subset of large trees due to the
operational challenges and added time of measuring tree height. Small tree 
data were recorded for trees greater than or equal to ~15cm in height from 
the ground, and up to the specified diameter threshold. 

During the summer of 2018, a re-measurement campaign targeted various 
accessible stands with at least 3 previously recorded measurements on
the Lolo National Forest. During the summer of 2021, PGP stands on the
Lolo and Kootenai National Forests that were previously measured at least
3 times and that were composed of >50\% overstory western larch (determined
by most recent measurement) were targeted for remeasurement. Stands across 
the remeasured PGPs were spread between $46^{\circ}$ N and $49^{\circ}$ N, and 
between 800 and 1700 $m$ above sea level. Stands were primarily on north-facing aspects. 
% Soil conditions were variable from site-to-site, but most were a silty-loam texture.
Species composition varied between almost pure western larch to mixed conifer
forests composed of mixtures of: western larch, Douglas-fir, Engelmann spruce, grand fir, 
subalpine fir, western hemlock, mountain hemlock, western red cedar,
cottonwood, and quaking aspen. 

\begin{table}[ht]
\centering
\begin{tabular}{rlrrrr}
  \hline
 & stand & number.plots & number.trees & number.obs & n.meas \\ 
  \hline
1 & 1401 &  10 &  53 & 150 & 4.00 \\ 
  2 & 1402 &  10 & 188 & 631 & 5.00 \\ 
  3 & 1403 &  10 & 113 & 313 & 5.00 \\ 
  4 & 1404 &  10 & 146 & 465 & 5.00 \\ 
  5 & 1405 &  10 & 188 & 676 & 5.00 \\ 
  6 & 1406 &  10 &  99 & 304 & 5.00 \\ 
  7 & 1407 &  19 &  74 & 108 & 4.00 \\ 
  8 & 1408 &  10 &  77 & 212 & 4.00 \\ 
  9 & 1609 &   9 &  37 & 139 & 5.00 \\ 
  10 & 1610 &  10 & 129 & 416 & 5.00 \\ 
  11 & 1611 &  10 &  77 & 222 & 5.00 \\ 
  12 & 1612 &  10 & 211 & 548 & 4.00 \\ 
  13 & 1614 &   9 &  49 & 181 & 5.00 \\ 
  14 & 1615 &  10 & 133 & 379 & 4.00 \\ 
  15 & 1616 &  10 & 106 & 291 & 4.00 \\ 
  16 & 1617 &  10 & 131 & 355 & 4.00 \\ 
  17 & 1618 &   9 &  30 &  66 & 4.00 \\ 
  18 & 1619 &  10 & 134 & 338 & 4.00 \\ 
   \hline
\end{tabular}
\end{table}

% In all, the portion of the PGP inventory data set used here contained -A CLUSTERS-, -X PLOTS-,
% -Y TREES-. Tree size/height varied by -----INFO------, 

\subsection{PGP Data}

Using these data, a generalized additive mixed model (GAMM) was developed to estimate 
annual growth of western larch, quantified by basal area increment (BAI; \ref{eq:bai}).

\begin{equation}
\label{eq:bai}
BAI = \frac{BA_{m+1}-BA_{m}}{(m+1)-m}
\end{equation}

GAMs allow for flexibility in model fitting and an allowance for non-linear 
relationships across variables \citep{Zhao2005}. Contrary to traditional 
parametric modeling approaches, GAMs let the data determine the 
shape of the functional relationships by fitting predictors with 
smooth functions instead of specified parameters \citep{Robinson2011}, 
which also proved beneficial in this case due to the inconsistency of measurement intervals. 
The choice to use a mixed-model approach was made due to the  
residual dependence structure that arises from repeat measurements 
on the same trees over time, and thus for each mixed model (GAMM) 
fit, a random effect was specified at the individual tree-level.

---include something visual about dependence structure?---

GAMMs were fit using using the mgcv package \citep{Wood2011} in R \citep{RCoreTeam2021}. 
The mgcv package allows for the specification of smooth functions (or smoothers). 
Smoothers are a sum of fitted estimated basis 
functions that characterize the conditional relationship between the predictor 
and independent variable. They are penalized by a smoothing parameter, which 
constrains a smoother's complexity as it grows higher \citaep{Pedersen2019}. 
Mgcv allows for smoothing parameters to be estimated via different methods - 
the maximum likelihood method was used in this study because it allows for 
better comparison across models that use different terms. 
Random effects may be coded as smooths in this format, 
which is essentially equivalent to other mixed-model approaches, however, 
when fitting large numbers intercepts (as done in this study) 
computation can extremely slow \citep{Pedersen2019}. %%%more here?? do I talk about using both methods since the way random effects are handled with the gamm case is kinda weird? (see pedersen 2019 page 34)
With mgcv, the thin-plate regression smoother (TPRS) type
is the default due to its simple and effective behavior \citep{Wood2003}
and is what was used in the present study for all terms including interactions. 
GAMs in mgcv also allow for 


The model formulation described here was developed with a training 
data set which allowed for varying conditions across all variables. 
Data for 2 measurement plots out of each stand were withheld for 
the purpose of model validation and quantifying variable effect size.
The model formulation resulting from the selection process described below
was used to evaluate effects of predictors 
on BAI across the entire data set and was also used to assess 
growth across different species mixtures, where the model was re-fit 
with subsets of the training data set, depending on the type of mixture. 

% 
% -DISTRIBUTION OF BAI HERE-
% 
% -Figure showing distribution of bai?-

\subsection{Base model selection}

Variable selection followed the logic of Wykoff (\citeyear{Wykoff1990}), 
Monserud \& Sterba (\citeyear{Monserud1996}), and 
Vospernik (\citeyear{Vospernik2021}) where variables were grouped together 
based on the following categories: 
size, density \& competition, and site. 
Initial size variables considered were tree diameter at breast 
height (DBH) and tree basal area ($BA_t$). 
Density and competition variables considered were: plot basal area (BA), 
basal area larger than the 
subject tree (BAL; expressed as a ratio of plot basal area), 
plot quadratic mean diameter (QMD), ratio of tree DBH to QMD ($D_q$), and trees per acre (tpa).
Site variables initially considered were: slope, aspect, elevation, 
mean site index (CITE), and heatload \citep{Theobald2015}. 
These initial explanatory variables were identified based on availability 
in the PGP data set, whether they could be calculated from the 
available data, and if they have been used in predicting 
BAI in previous empirical modeling efforts. 

% crown competition factor (CCF;\cite{Krajicek1961}), remove??
-TABLE HERE- table of all variables considered prior to modeling including definitions and how they were calculated?--

A pair-wise colinearity assessment was 
then performed among each group of variables to avoid including 
highly correlated variables together in the model. 
Any pair-wise linear relationship with a correlation of 
0.65 or higher were not considered together. Although somewhat arbitrary, 
this threshold was selected because a 0.65 correlation means that 
variation shared between variables exceeds 40\%. Additionally, variables 
known to represent the same processes, even if not highly linearly correlated 
(such as heatload and aspect, for instance), were not considered together to 
avoid redundancies and reduce model complexity.

GAMs were used to select variables and visually examine 
predictor partial effects on the BAI as well as examine residual structure. 
Models were iteratively fit by group, including non-correlated variables together 
respective of grouping while maximizing model accuracy and avoiding overlap. 
The order of this group-wise selection process was based on 
previously identified contribution of these variable group-types 
to estimating BAI \citep{Wykoff1990,Monserud1996}. Highly 
correlated same-group variables were compared in alternative models.
For example, alternative models were fit for both tree diameter 
and tree basal area, selecting whichever best predicted BAI. 
Then, with the selected size variable present in the model, 
competition and density variables were evaluated and selected 
based on maximizing model accuracy and reducing overlap between variables. 
The same process was used for site variables thereafter, 
finalizing the base model formulation (\ref{eq:baiform}). 

\begin{equation}
\label{eq:baiform}
g(E(BAI)) = \beta_0 + f_1(Size) + f_2(Density \& Competition) + f_3(Site) \\
\text{$g()$ represents a link function, $E(BAI)$ represents the expected 
value of BAI of interest, $\beta_0$ represents 
an intercept, and $f_i$ represents a non-linear function applied to an 
independent variable, $x_i$.}
\end{equation}

Root mean squared error (RMSE; \ref{eq:rmse}) was 
calculated to assess model accuracy, where when comparing models, 
a model formulation with the lowest RMSE (highest predictive accuracy) 
was selected over alternatives. RMSE was calculated using residual degrees of 
freedom to reduce bias. Explained deviance (CITE??) and AIC (CITE?) were also 
considered for ensuring acceptable model fit, %Do i even say this?
but they were not used as strict selection criteria because
each improved proportionally to RMSE. %Do i even say this?

\begin{equation}
\label{eq:rmse}
RMSE = \sqrt{\frac{\sum (\hat{y} - y)^2}{n_{df}}}
\end{equation}

\subsection{Assessing species-mixing impacts on growth}

% - Once a model exists, we can use it on subsets of the data set to 
% determine types of species-mixing effects and their effects on BAI

After establishing a parsimonious base model structure, 
subsets of the PGP data for different types of species-mixtures were determined 
and fit using the same model formulation. Using each resulting model, 
growth was predicted from a data set holding every variable except DBH constant 
to isolate the effects of tree size on growth across mixtures. Resulting curves respective of 
species-mix type were then plotted and visually examined. Additionally, 
the DBH-BAI relationship was evaluated at different 
levels of each other variable to examine how the size-growth relationship 
is modified across densities, competitive symmetries, crown ratios, and aspects.

% It was of interest to examine these relationships of larch growth in mixtures 
% with species that span the shade-tolerance spectrum, including stands  
% that are predominantly composed of larch as well as stands where larch was mixed 
% with a different species. 
Mixture-types were identified by  
proportions of plot basal area occupied by larch and species it was mixed with. 
For instance, to qualify as a specific mixture-type, a minimum of 20\% total plot 
basal area had to be in western larch trees and a minimum of 20\% plot basal 
area in the other species, where neither larch nor the other species percent 
BA could exceed 65\% in a plot, and both species combined basal area had 
to be at least 70\% of total plot BA. This ensured that a range of 
each mixture-type was captured while prohibiting over-representation of 
either species within the mixture. Additionally, pure larch  
conditions were identified by selecting plots where basal area was composed of 
at least 90\% western larch. Since the data was subset in favor 
of specific scenarios, it was important to consider the size of subsets 
before fitting models with them to ensure sample size was large enough. 
Ultimately, mixtures chosen were composed of 
larch with lodgepole pine, douglas-fir, and Engallmann spruce, spanning 
from shade intolerant to shade-tolerant. 

% Figure (XXX) shows the distribution 
% of each mixture type across to other species identified. 

A hypothesis test was conducted to identify differences between predicted values 
of BAI across the range of DBH. There is a level of uncertainty associated 
with smoothing parameter estimation in the mgcv package which is not accounted for . 95\% confidence intervals for each predicted 
value were calculated based on a simulation of the posterior distribution at 
each value of DBH. This ensures that the uncertainty 

%may be able to get away with adding unconditional = T to the predict function to generate intervals that account for the fact that smoothing parameters were estiamted. 
%additionally, I can add sewithmean=T to the plot command, save the plot object, and then inspect the object and see that its a list with one comoponentper smooth. 
%% see this post: https://stats.stackexchange.com/questions/33327/confidence-interval-for-gam-model/33328#33328
%% simultaneous confidence intervals 

%%see also: https://stats.stackexchange.com/questions/503819/confidence-intervals-for-derivatives-from-gam-predictions
%% https://stats.stackexchange.com/questions/190348/can-i-use-bootstrapping-to-estimate-the-uncertainty-in-a-maximum-value-of-a-gam/191489#191489
%%  https://stats.stackexchange.com/questions/464961/issues-with-posterior-simulation-from-gam - simon wood on SE

% make figure or table that describes the range of conditions for each mixture type
%% including minimum and maximum percent of each species in a mixture, while including their combined basal area. 
%%% perhaps a stacked barchart where each bar totaled to the percent mixture, 
%%% and with one color representing larch ba, and other color for each species representing BA.  
%%%% Or boxplots of each mixture type
%%%% jittered points for each mixture, where x is mixture type and y is larch:spp mixture ratio
% visualize the BA thresholds for selecting different mixture-types?

occupied by larch 
had to be at least  and likewise for a given species.
Identifying different mixtures 

Different categories of species-mixtures were identified by evaluating 
the amount of plot basal area 

impacted at different levels other variables, 
the same 
process was repeated for 
For example, predictions were made 
across a range of tree diameters for each of the mixture models

Furthermore, additional variables 
were categorized



% 
% -how to do this: 
% -first see the comments on this post from Gavin S. :https://stats.stackexchange.com/questions/470980/continuously-test-where-two-generalized-additive-models-differ
% - I want to test the difference of expected values across a given range of x (whichever covariate).
% -- https://fromthebottomoftheheap.net/2016/12/15/simultaneous-interval-revisited/
% -- extract baysian covariacne matrix with vcov()
% -- define new data with dubbed values of whichever covariate
% -- predict from that
% -- pull the se.fit object




%can i use by variable to test for differences in spp mix?
To determine 
if growth was characterized differently across different mixtures, 

- Explain and rationalize how subsets were identified
- Fit model to data subsets
- Use resulting models to predict on a static data set where only one (or two)
variables are changing
- Explain basis of comparison (how do i compare these things)
--do i compare visually? Is there a hypothesis testing?
--- do i compare pointwise, based on the confidence interval?


\subsection{Capturing and comparing species-mixing measures}

Three different species-informed measures were identified for comparison: 
crown competition factor, proportion of basal area occupied by larch, and 
proportion of basal area weighted by species-shade tolerance values. 

Crown competition factor (CCF) is a species-informed density measure that 
is based on tree crown allometry \citep{Krajicek1961}. In this measure, 
each species has an identified maximum crown width in open-grown conditions for 
a given diameter. These values are expressed as a percentage of 
area that could be occupied by open grown tree crowns, and summed within 
a stand to express overall competition for crown space. Theoretically, 
different tree species of a given diameter with high maximum crown widths mixed together 
would drive the CCF value well over 100\% representing high competition.  
In contrary, a mixture of species of a given size composed of large and 
small crown widths could increase utilization of crown space, 
reducing competition. This measure does not explicitly  
represent different species proportions, so interpreting species-mixing 
effects from it can be challenging. 

-- CCF equation here --

The proportion of basal area occupied by larch is a measure of species 
purity within a stand, and is simply calculated as a ratio of plot basal 
area occupied by western larch. 

\begin{equation}
\label{eq:purity}
L_{jt} = \frac{\sum_{i}{BA_{ijt}\ I_{ijt}}}{\sum_{i}{BA_{ijt}}}\ \ \ I_{ijt} = \begin{cases} 1,\ \text{if}\ i\ \text{is western larch}\\0,\ \text{otherwise}\end{cases}
\end{equation}

\text{$L_{jt}$ denotes the ratio, $BA_{ijt}$ is the of basal area of a tree $i$, $I_{ijt}$ is a binary operator which indicates whether a tree $i$ is western larch ($I_{ijt} = 1$), or otherwise ($I_{ijt} = 0$)}

The third species-informed measure makes use of a shade-tolerance index 
\citep{Lienard2015} where different species are assigned with values 
ranging between 0 and 1, 0 being very shade-tolerant, and 1 being very 
shade-intolerant. Since this study focused on shade-intolerant western larch, 
these values were inverted so that they could be easily compared with the 
purity metric (REFERENCE SHADE INTOLERANCE TABLE). Shade tolerance values were multiplied by individual tree 
basal area values, and then summed, effectively describing community 
shade-intolerance through a proportion of basal area. 

\begin{table}
\caption{shade intolerance}
\centering
\begin{tabular}[t]{>{}l>{}lr}
\toprule
Genus & Species & Shade intolerance\\
\midrule
\em{\cellcolor{gray!6}{Larix}} & \em{\cellcolor{gray!6}{occidentalis}} & \cellcolor{gray!6}{1.00}\\
\em{Pinus} & \em{contorta} & 1.00\\
\em{\cellcolor{gray!6}{Pinus}} & \em{\cellcolor{gray!6}{ponderosa}} & \cellcolor{gray!6}{0.75}\\
\em{Pinus} & \em{monticola} & 0.50\\
\em{\cellcolor{gray!6}{Pseudotsuga}} & \em{\cellcolor{gray!6}{menziesii}} & \cellcolor{gray!6}{0.50}\\
\addlinespace
\em{Abies} & \em{grandis} & 0.25\\
\em{\cellcolor{gray!6}{Abies}} & \em{\cellcolor{gray!6}{lasiocarpa}} & \cellcolor{gray!6}{0.25}\\
\em{Picea} & \em{engelmannii} & 0.25\\
\em{\cellcolor{gray!6}{Thuja}} & \em{\cellcolor{gray!6}{plicata}} & \cellcolor{gray!6}{0}\\
\em{Tsuga} & \em{heterophylla} & 0\\
\bottomrule
\end{tabular}
\end{table}



\begin{equation}
\label{eq:shade}
T_{jt} = \frac{\sum_{i}{\rho_{ijt}\ BA_{ijt}}}{\sum_{ijt}{BA_{ijt}}}
\text{$\rho_{ijt}$ represents the species specific shade-tolerance ranking of tree $i$ \citep{Lienard2015}.}
\end{equation}

% - Using them in a model
% - comparing models based on RMSE, quantifying accuracy improvements by each

To evaluate and compare these measures they were added as predictors 
to the identified base model formulation, each in its own respective model, 
and fit with the same data. Models were then compared on the basis of 
accuracy (RMSE) and fit (explained deviance; CITE?), quantifying 
each predictor's relative improvement to model performance. To calculate 
RMSE, BAI was predicted by each model from the withheld portion data set, 
and model prediction errors were calculated. 




\section{Results}

\subsection{BAI model}

A basal area increment model was specified with the following predictors: 
DBH, crown ratio (CR), basal area larger than the subject (BAL; expressed as a ratio), 
plot basal area (BA), aspect, and a tree-level random effect. 
The model was fit with a gamma distribution because BAI is bounded by zero  and log-link. 
The model training data set consisted of 
5,792 basal area increments across 1,975 individual western larch trees. 
The base model RMSE was ~3.34 $cm^2/yr.$ Fixed effects terms used 
~53 degrees of freedom, and total model deviance explained was 84.9\%. 
Random effects were accounted for using a spline basis \citep{Wood2017}, and thus 
had an associated degrees of freedom of ~1338. Model residual 
degrees of freedom was ~4401.

Tree DBH and basal area were highly correlated (0.938) and were 
evaluated in separate models. DBH as a predictor yielded higher 
accuracy in predicting BAI than tree BA, with model RMSE values  
of 5.64 $cm^2/yr.$ and 5.70 $cm^2/yr.$, respectively. 

Competition and density variables were partitioned into two sub-groups:  
variables representing a tree's competitive position in a stand, and variables 
that represent the overall competitive environment. High-collinear variable 
combinations were were TPA-$D_q$ (0.732) and BA-QMD (0.684).  %, CCF-BA (0.95)
Tree-level variables reduced RMSE to 4.50 $cm^2/yr.$, and then to 
4.31 $cm^2/yr.$ with plot BA included.

Topographic variables (slope, aspect, elevation) were evaluated as 
potential predictors separately from site index and heatload. Since aspect
is a circular measure, both sin (easting) and cosine (northing) 
transformations were applied as in previous works (CITE). Aspect was best 
accounted for as an interaction term in the form of an isotropic smooth \citep{Wood2017}. 
Slope and elevation contributed little to prediction accuracy 
when included with aspect and were associated with concurvity values 
beyond the established threshold. Thus, building on the model and 
comparing aspect, site index, and heatload, aspect was selected as 
the best term, further reducing model RMSE to 4.01 $cm^2/yr.$

Given the order in which variables were included, 
competition and density metrics contributed the most in deviance explained, 
followed by size. However, considering variables individually, 
DBH explained more deviance and reduced RMSE more than any other 
variable in the model. These results are more or less concurrent with 
previous studies on the matter.

-- model fitting rmse table -- 

% Furthermore, aspect effects were evaluated in the model separately as easting, 
% northing, as a joint interaction term, and as a decomposed tensor 
% product interaction term (CITE - wood?).
% to ensure that multi-level competitive effects were captured

\subsection{Assessing species-mixing impacts on growth}

\subsection{Capturing and comparing species-mixing measures}



-Plot BA and CCF were highly correlated with one 
another, so CCF was included in place of BA in the model formulation. 
Larch purity and shade intolerance were simply added as an additional 
predictors in separate models. 

-table of RMSE, dev.expl values for each model


\section{Discussion}

\subsection{BAI model selection}

- Intially ccf was considered as a competition and density measure, 
and CCF was selected in a model formulation with slope as well, however 
the benefit to RMSE that this formula provided was marginal compared 
to the formula that included BA. Further, to accommodate analyses which 
recognized CCF as a species composition informed measure, 
it was deemed more practical to compare non-species informed BA to CCF

- The use of generalized additive models is becoming more prevalent in 
forest ecological research. 
- using generalized additive models for each task in this study presented 
challenges. One such challenge was the time that it took to fit models 
with random effects. 
- One benefit was the realized 

\subsection{Assessing species-mixing impacts on growth}



\subsection{Comparing species-mixing measures}

- discussion on BA proportion as a measure of species-mixing
- pros and cons of ccf as a mixture variable
-


\section{Conclusions}




% \captionof{equation}{Root mean squared error (RMSE) equation, where \hat{y} 
% represents a predicted value, y represents an observed value, and n_{df} 
% represents model residual degrees of freedom}

% The following steps outline the pragmatic variable selection
% approach mentioned in step (ii) above:
% \begin{enumerate}
%   \item Evaluate co-linearity of within-group predictors with each other to help avoid redundant inclusion of variables. 
%   \item Only necessary or inherent interactions were considered, such as an interaction between sin(aspect) and cos(aspect). 
%   \item Different groups of variables within groups were compared with RMSE. 
%   \item Ultimately, the lowest RMSE version within each group was chosen based on the above workflow.
%   \item A concurvity \citep{Hastie1990} assessment was then conducted between variables within each group. If concurvity was greater than 0.8 for a particular set of terms, then an alternative not including both terms was evaluated. 
% \end{enumerate}
% 
% The following steps outline the implemented selection framework:
% (i) evaluating and estimating potential explanatory variables 
% in the available data set based on established relationships
% with the dependent variable (BAI), (ii) sequentially
% selecting predictor variables within the pre-determined groups 
% through a pragmatic variable selection approach to identify
% a base-model structure for the GAM, and (iii) evaluating random effects.
% 




% The order of these variable groups is 
% the order in which the model formulation was iteratively constructed, 
% based on their previously identified relative importance 
% in estimating BAI .


% (iv-a) assess whether larch growth varies across different types of mixtures
% (iv-b) assessing effects produced by identified species-mixing variables. 

% For (i), explanatory variables were identified based on availability 
% in the PGP data set and whether they could be calculated from the 
% available data. 
% Variables contained in established and widely-used
% empirical models, such as the diameter growth model in FVS \textbf{(*CITE*)},
% were considered because, 1. the PGP data collection focused on such
% variables, and 2. these variables are relatively easy to collect 
% and commonly found in long-term data collection efforts similar to
% the PGP data. 
% This allows for the potential expansion of these 
% methodologies to other, similar works. 
% Variables considered that were beyond the scope identified above, related primarily to site conditions. 

% \textbf{**ADD TABLE that lists variables from the ln(DDS) model, as well as variables not in that model in BOLD text?**} 
% Once explanatory variables were identified for consideration,
% they were then grouped into the following categories: tree size,
% density and competition, and site.




% The following steps outline the pragmatic variable selection
% approach mentioned in step (ii) above:
% 
% \begin{enumerate}
%   \item Evaluate co-linearity of within-group predictors with each other to help avoid redundant inclusion of variables. Any pair-wise linear relationship with a correlation coefficient of 0.7 or higher was not considered together. (R-squared of .49 or higher). This was chosen as the cutoff because .7 correlation means that variance is roughly 50\% accounted for between variables. Additionally, variables known to represent the same processes, like tree basal area and diameter, were not considered together to avoid redundancies and reduce model complexity. 
%   \item Only necessary or inherent interactions were considered, such as an interaction between sin(aspect) and cos(aspect). 
%   \item Different groups of variables within groups were compared with RMSE. 
%   \item Ultimately, the lowest RMSE version within each group was chosen based on the above workflow.
%   \item A concurvity \citep{Hastie1990} assessment was then conducted between variables within each group. If concurvity was greater than 0.8 for a particular set of terms, then an alternative not including both terms was evaluated. 
% \end{enumerate}

% -FIGRE/TABLE of colinearity assessment?- (maybe include in table of variables?) tile plot? table of corrs?--


% , *such terms will be scrutinized.* (Johnston et al 2019 uses a very low concurvity cutoff. It oftentimes is arbitrary). 

%2.%*These two were inherent because they are derived from the same variable, aspect, which cannot be used in its raw form due to scaling issues. The sin/cos transformation and the resulting interaction term allows this variable to represent aspect in a way that parses out east-west from north-south. Model comparisons were made with their inclusion and without.*


% 3.*For example, in the site variables group, 3 different groups were compared - heatload, site index, and raw topographic variables. The model bearing the lowest RMSE (highest predictive accuracy) was selected. These groups were derived as a result of the colinearity assessments as well as prior knowledge that heatload is derived from topographic variables and site index is meant to serve as a catch-all that accounts for all site variables. In the case of site variables as well, a stand categorization intercept was evaluated against the other within-group groups to account for site effects. *

% Step (iii) Random effects
% 
% Step (iv) species mixing

% \subsubsection{Within-group dimensional reduction}
% 
% Selecting variables within each group posed challenges due to the 
% number of predictors, colinearity and/or concurvity among variables
% and terms, and the numerous potential interactions between variables
% within groups. This required a firmly-structured process where
% co-variate relationships are assessed. 
% 
% **DEFINE CONCURVITY** (Hastie and Tibshirani 1990)
% 
% *curse of dimensionality of nonparametric functions* Wood(2004) 
% stable and efficient multiple smoothing parameter estimation for
% generalized additive models
% *Sure-independence screening*
% 
% Prior to implementing the steps here, assessment of co-linearity
% was performed between variables within each group, since there is
% some amount of redundancy within groups. This assessment was made 
% through plotting each variable with each other variable, identifying
% if there is a relationship through graphical analysis, and then 
% evaluating the strength of linear relationships with r-squared values. 
% Additionally, if one variable is derived from another present, 
% these will not be considered as covariates in the same model.

% \subsubsection{Evaluating species mixing}

% Once a parsimonious base-model is selected, species-mixing variables 
% will then be added to detect if there is a species-mixing effect. 
% Further elaboration on applying this approach will be explained in
% the following text. **The following equation** (Equation...xxx) 
% represents the modeling framework: 



% \subsection{Basal Area Increment Model}

% Here is an equation:
% \begin{align}
% B & = \frac{2^x}{\sin{\theta}} \sum_{i=1}^N y_i^3 \\ \nonumber
% & = 3
% \end{align}
% 
% \section{A second section}
% \subsection{With one subsection}

% Here is a code chunk.
% 
% <<no_need_for_a_name>>=
% 10^3
% @
% and another without the call showing.
% 
% <<no_need_for_a_name,echo=F>>=
% 10^3
% @
% and you can also do inline \Sexpr{round(pi,5)}.
@

% \chapter{Chunks of extended abstract}
% 
% Western larch (\emph{Larix occidentalis}) is an important tree species that is 
% exclusive to the inland northwest region of North America %[@Knudsen1968; @Schmidt1976; @Schmidt1995]. 
% \citep{Knudsen1968,Schmidt1976,Schmidt1995}.
% It is very intolerant of shade, and grows across a wide range 
% of communities with both shade-tolerant and -intolerant species %[@Baker1949; @Schmidt1988]. 
% A growing body of evidence suggests that species traits in mixed-species 
% forest communities can impact tree growth relationships %[@Forrester2017; @Riofrio2017]. 
% The objectives of this research are: 
% \begin{enumerate}
% \item
% to identify whether community species composition impacts the growth 
% of western larch after accounting for other influential factors, 
% \item to identify if a stand average shade-tolerance more effectively 
% captures species-mixing effects on growth when compared to a less 
% specific relative abundance metric, and
% \item to quantify the degree to which 
% species-mixing impacts the growth of western larch (if an effect is observed).
% \end{enumerate}
% 
% As shown in Fig.~\ref{fig:junk}, there are many references to consider.
% \begin{figure}\centering
% %\includegraphics[width=\textwidth]{../extab_refs.JPG}
% \includegraphics[width=2in]{../extab_refs.JPG}
% \caption{This is a figure.}\label{fig:junk}
% \end{figure}
% 
% Next I have a table, called Table \ref{tab:fake}.
% \begin{table}\centering
% \caption{This is my table.}\label{tab:fake}
% \begin{tabular}{cc}
% \hline
% Row 1 & Column 2 \\ \hline
% 1 & 2 \\
% 3 & 4 \\ \hline
% \end{tabular}
% \end{table}

%%%% BACK MATTER
\backmatter
\chapter*{Literature Cited}
\addcontentsline{toc}{chapter}{Literature Cited}
\bibliography{../zotero_library}{}
% \cite{*} % use this to list all entries in bib file

\end{document}
